# Generated by dev-hub/tools/generate-openapi-sdk.mjs from api/openapi.yaml.
# Do not edit manually.

import json
from urllib import error, parse, request as urllib_request


open_api_version = "4.16.190-2026-05-29"


class LeopardoApiError(Exception):
    def __init__(self, message, *, status, body):
        super().__init__(message)
        self.status = status
        self.body = body


class LeopardoClient:
    def __init__(self, *, base_url, token=None, timeout=30):
        if not base_url:
            raise ValueError("base_url is required")

        self.base_url = base_url.rstrip("/")
        self.token = token
        self.timeout = timeout

    def _build_path(self, path_template, path_params=None):
        path_params = path_params or {}
        rendered = path_template

        for key, value in path_params.items():
            rendered = rendered.replace("{" + key + "}", parse.quote(str(value), safe=""))

        if "{" in rendered or "}" in rendered:
            raise ValueError("Missing path parameter in " + path_template)

        return rendered

    def _build_url(self, path_template, *, path_params=None, query=None):
        url = self.base_url + self._build_path(path_template, path_params)
        clean_query = {}

        for key, value in (query or {}).items():
            if value is None:
                continue
            clean_query[key] = value

        if clean_query:
            url += "?" + parse.urlencode(clean_query, doseq=True)

        return url

    def request(self, method, path_template, *, path_params=None, query=None, body=None, headers=None):
        request_headers = {
            "Accept": "application/json",
            **(headers or {}),
        }

        if self.token:
            request_headers["Authorization"] = "Bearer " + self.token

        data = None
        if body is not None:
            request_headers.setdefault("Content-Type", "application/json")
            data = json.dumps(body).encode("utf-8")

        req = urllib_request.Request(
            self._build_url(path_template, path_params=path_params, query=query),
            data=data,
            headers=request_headers,
            method=method,
        )

        try:
            with urllib_request.urlopen(req, timeout=self.timeout) as response:
                raw = response.read()
                content_type = response.headers.get("content-type", "")
                if "application/json" in content_type:
                    return json.loads(raw.decode("utf-8")) if raw else None
                return raw.decode("utf-8")
        except error.HTTPError as exc:
            raw = exc.read()
            body_text = raw.decode("utf-8") if raw else ""
            try:
                parsed_body = json.loads(body_text) if body_text else None
            except json.JSONDecodeError:
                parsed_body = body_text

            raise LeopardoApiError(
                "Leopardo API request failed with status " + str(exc.code),
                status=exc.code,
                body=parsed_body,
            ) from exc

    def get_absences(self, **kwargs):
        """Lister les absences"""
        return self.request("GET", "/absences", **kwargs)

    def post_absences(self, **kwargs):
        """Demander une absence"""
        return self.request("POST", "/absences", **kwargs)

    def delete_absences_by_absence(self, **kwargs):
        """Annuler une absence (employe proprietaire)"""
        return self.request("DELETE", "/absences/{absence}", **kwargs)

    def get_absences_by_absence(self, **kwargs):
        """Voir une absence"""
        return self.request("GET", "/absences/{absence}", **kwargs)

    def put_absences_by_absence_approve(self, **kwargs):
        """Approuver une absence (manager)"""
        return self.request("PUT", "/absences/{absence}/approve", **kwargs)

    def put_absences_by_absence_reject(self, **kwargs):
        """Rejeter une absence (manager)"""
        return self.request("PUT", "/absences/{absence}/reject", **kwargs)

    def get_ai_analytics_costs(self, **kwargs):
        """Couts IA par periode"""
        return self.request("GET", "/ai/analytics/costs", **kwargs)

    def get_ai_analytics_errors(self, **kwargs):
        """Erreurs IA recentes"""
        return self.request("GET", "/ai/analytics/errors", **kwargs)

    def get_ai_analytics_tools(self, **kwargs):
        """Usage des outils IA"""
        return self.request("GET", "/ai/analytics/tools", **kwargs)

    def get_ai_analytics_usage(self, **kwargs):
        """Metriques d'usage IA"""
        return self.request("GET", "/ai/analytics/usage", **kwargs)

    def post_ai_chat(self, **kwargs):
        """Envoyer un message au chatbot IA"""
        return self.request("POST", "/ai/chat", **kwargs)

    def delete_ai_chat_by_conversationid(self, **kwargs):
        """Supprimer une conversation IA"""
        return self.request("DELETE", "/ai/chat/{conversationId}", **kwargs)

    def get_ai_chat_history(self, **kwargs):
        """Historique des conversations IA"""
        return self.request("GET", "/ai/chat/history", **kwargs)

    def get_ai_tools(self, **kwargs):
        """Liste des outils IA disponibles"""
        return self.request("GET", "/ai/tools", **kwargs)

    def get_approval_workflows(self, **kwargs):
        """Lister les workflows d'approbation"""
        return self.request("GET", "/approval-workflows", **kwargs)

    def post_approval_workflows(self, **kwargs):
        """Creer un workflow"""
        return self.request("POST", "/approval-workflows", **kwargs)

    def delete_approval_workflows_by_approvalworkflow(self, **kwargs):
        """Supprimer un workflow"""
        return self.request("DELETE", "/approval-workflows/{approvalWorkflow}", **kwargs)

    def put_approval_workflows_by_approvalworkflow(self, **kwargs):
        """Modifier un workflow"""
        return self.request("PUT", "/approval-workflows/{approvalWorkflow}", **kwargs)

    def post_approvals_by_approvalrequest_approve(self, **kwargs):
        """Approuver une demande"""
        return self.request("POST", "/approvals/{approvalRequest}/approve", **kwargs)

    def post_approvals_by_approvalrequest_reject(self, **kwargs):
        """Rejeter une demande"""
        return self.request("POST", "/approvals/{approvalRequest}/reject", **kwargs)

    def get_approvals_history(self, **kwargs):
        """Historique des approbations"""
        return self.request("GET", "/approvals/history", **kwargs)

    def get_approvals_pending(self, **kwargs):
        """Approbations en attente"""
        return self.request("GET", "/approvals/pending", **kwargs)

    def get_attendance(self, **kwargs):
        """Historique de pointage"""
        return self.request("GET", "/attendance", **kwargs)

    def put_attendance_by_attendancelog(self, **kwargs):
        """Modifier directement un pointage"""
        return self.request("PUT", "/attendance/{attendanceLog}", **kwargs)

    def get_attendance_by_attendancelog_punch_photo(self, **kwargs):
        """Telecharger la photo de pointage d'un log"""
        return self.request("GET", "/attendance/{attendanceLog}/punch-photo", **kwargs)

    def get_attendance_anomalies(self, **kwargs):
        """Anomalies de pointage"""
        return self.request("GET", "/attendance/anomalies", **kwargs)

    def post_attendance_check_in(self, **kwargs):
        """Check-in"""
        return self.request("POST", "/attendance/check-in", **kwargs)

    def post_attendance_check_out(self, **kwargs):
        """Check-out"""
        return self.request("POST", "/attendance/check-out", **kwargs)

    def get_attendance_corrections(self, **kwargs):
        """Lister les demandes de correction de pointage"""
        return self.request("GET", "/attendance/corrections", **kwargs)

    def post_attendance_corrections(self, **kwargs):
        """Demander une correction de pointage"""
        return self.request("POST", "/attendance/corrections", **kwargs)

    def put_attendance_corrections_by_correction_approve(self, **kwargs):
        """Appliquer une demande de correction de pointage"""
        return self.request("PUT", "/attendance/corrections/{correction}/approve", **kwargs)

    def put_attendance_corrections_by_correction_reject(self, **kwargs):
        """Refuser une demande de correction de pointage"""
        return self.request("PUT", "/attendance/corrections/{correction}/reject", **kwargs)

    def get_attendance_monthly_report(self, **kwargs):
        """Rapport mensuel de pointage"""
        return self.request("GET", "/attendance/monthly-report", **kwargs)

    def get_attendance_today(self, **kwargs):
        """Etat du jour"""
        return self.request("GET", "/attendance/today", **kwargs)

    def get_audit_logs(self, **kwargs):
        """Journal d'audit"""
        return self.request("GET", "/audit-logs", **kwargs)

    def get_audit_logs_by_auditlog(self, **kwargs):
        """Voir un evenement d'audit"""
        return self.request("GET", "/audit-logs/{auditLog}", **kwargs)

    def get_audit_logs_export_csv(self, **kwargs):
        """Exporter le journal d'audit en CSV"""
        return self.request("GET", "/audit-logs/export-csv", **kwargs)

    def get_auth_biometric_enrollment(self, **kwargs):
        """Derniere demande biometrie de l'utilisateur courant"""
        return self.request("GET", "/auth/biometric-enrollment", **kwargs)

    def post_auth_biometric_enrollment(self, **kwargs):
        """Soumettre une demande biometrie"""
        return self.request("POST", "/auth/biometric-enrollment", **kwargs)

    def post_auth_change_password(self, **kwargs):
        """Changer le mot de passe"""
        return self.request("POST", "/auth/change-password", **kwargs)

    def post_auth_google_token(self, **kwargs):
        """Connexion Google OAuth"""
        return self.request("POST", "/auth/google/token", **kwargs)

    def patch_auth_language(self, **kwargs):
        """Changer la langue"""
        return self.request("PATCH", "/auth/language", **kwargs)

    def post_auth_login(self, **kwargs):
        """Connexion employee"""
        return self.request("POST", "/auth/login", **kwargs)

    def post_auth_logout(self, **kwargs):
        """Deconnexion employee"""
        return self.request("POST", "/auth/logout", **kwargs)

    def get_auth_me(self, **kwargs):
        """Profil authentifie"""
        return self.request("GET", "/auth/me", **kwargs)

    def patch_auth_profile(self, **kwargs):
        """Mettre a jour le profil courant"""
        return self.request("PATCH", "/auth/profile", **kwargs)

    def post_auth_refresh_token(self, **kwargs):
        """Rafraichir le token"""
        return self.request("POST", "/auth/refresh-token", **kwargs)

    def post_auth_register(self, **kwargs):
        """Inscription employe"""
        return self.request("POST", "/auth/register", **kwargs)

    def get_bank_exports(self, **kwargs):
        """Lister les exports bancaires"""
        return self.request("GET", "/bank-exports", **kwargs)

    def post_bank_exports(self, **kwargs):
        """Generer un export bancaire"""
        return self.request("POST", "/bank-exports", **kwargs)

    def get_bank_exports_by_bankexport_download(self, **kwargs):
        """Telecharger un export bancaire"""
        return self.request("GET", "/bank-exports/{bankExport}/download", **kwargs)

    def createbillingcheckoutsession(self, **kwargs):
        """Creer une session Stripe Checkout pour souscrire/upgrader (manager)"""
        return self.request("POST", "/billing/checkout", **kwargs)

    def get_billing_invoices(self, **kwargs):
        """Lister les factures"""
        return self.request("GET", "/billing/invoices", **kwargs)

    def get_billing_invoices_by_id(self, **kwargs):
        """Voir une facture"""
        return self.request("GET", "/billing/invoices/{id}", **kwargs)

    def get_billing_invoices_by_id_pdf(self, **kwargs):
        """Telecharger facture PDF"""
        return self.request("GET", "/billing/invoices/{id}/pdf", **kwargs)

    def createbillingportalsession(self, **kwargs):
        """Creer une session Stripe Customer Portal pour gerer l'abonnement (manager)"""
        return self.request("GET", "/billing/portal", **kwargs)

    def get_billing_subscription(self, **kwargs):
        """Voir l'abonnement courant"""
        return self.request("GET", "/billing/subscription", **kwargs)

    def cancelsubscription(self, **kwargs):
        """Annuler l'abonnement (manager)"""
        return self.request("POST", "/billing/subscription/cancel", **kwargs)

    def renewsubscription(self, **kwargs):
        """Renouveler l'abonnement (manager)"""
        return self.request("POST", "/billing/subscription/renew", **kwargs)

    def upgradesubscription(self, **kwargs):
        """Upgrader l'abonnement (manager)"""
        return self.request("POST", "/billing/subscription/upgrade", **kwargs)

    def get_biometric_enrollment_requests(self, **kwargs):
        """Lister les demandes biometrie de la company"""
        return self.request("GET", "/biometric-enrollment-requests", **kwargs)

    def post_biometric_enrollment_requests_by_id_approve(self, **kwargs):
        """Approuver une demande biometrie"""
        return self.request("POST", "/biometric-enrollment-requests/{id}/approve", **kwargs)

    def post_biometric_enrollment_requests_by_id_reject(self, **kwargs):
        """Rejeter une demande biometrie"""
        return self.request("POST", "/biometric-enrollment-requests/{id}/reject", **kwargs)

    def get_cabinet_documents(self, **kwargs):
        """Lister les documents"""
        return self.request("GET", "/cabinet/documents", **kwargs)

    def post_cabinet_documents(self, **kwargs):
        """Uploader un document"""
        return self.request("POST", "/cabinet/documents", **kwargs)

    def delete_cabinet_documents_by_cabinetdocument(self, **kwargs):
        """Supprimer un document"""
        return self.request("DELETE", "/cabinet/documents/{cabinetDocument}", **kwargs)

    def get_cabinet_documents_by_cabinetdocument(self, **kwargs):
        """Voir un document"""
        return self.request("GET", "/cabinet/documents/{cabinetDocument}", **kwargs)

    def put_cabinet_documents_by_cabinetdocument(self, **kwargs):
        """Modifier un document"""
        return self.request("PUT", "/cabinet/documents/{cabinetDocument}", **kwargs)

    def get_cabinet_documents_by_cabinetdocument_download(self, **kwargs):
        """Telecharger un document"""
        return self.request("GET", "/cabinet/documents/{cabinetDocument}/download", **kwargs)

    def post_cabinet_documents_by_cabinetdocument_move(self, **kwargs):
        """Deplacer un document"""
        return self.request("POST", "/cabinet/documents/{cabinetDocument}/move", **kwargs)

    def get_cabinet_folders(self, **kwargs):
        """Lister les dossiers"""
        return self.request("GET", "/cabinet/folders", **kwargs)

    def post_cabinet_folders(self, **kwargs):
        """Creer un dossier"""
        return self.request("POST", "/cabinet/folders", **kwargs)

    def delete_cabinet_folders_by_cabinetfolder(self, **kwargs):
        """Supprimer un dossier"""
        return self.request("DELETE", "/cabinet/folders/{cabinetFolder}", **kwargs)

    def get_cabinet_folders_by_cabinetfolder(self, **kwargs):
        """Voir un dossier"""
        return self.request("GET", "/cabinet/folders/{cabinetFolder}", **kwargs)

    def put_cabinet_folders_by_cabinetfolder(self, **kwargs):
        """Modifier un dossier"""
        return self.request("PUT", "/cabinet/folders/{cabinetFolder}", **kwargs)

    def get_cameras(self, **kwargs):
        """Lister les cameras"""
        return self.request("GET", "/cameras", **kwargs)

    def post_cameras(self, **kwargs):
        """Creer une camera"""
        return self.request("POST", "/cameras", **kwargs)

    def delete_cameras_by_camera(self, **kwargs):
        """Desactiver une camera"""
        return self.request("DELETE", "/cameras/{camera}", **kwargs)

    def get_cameras_by_camera(self, **kwargs):
        """Voir une camera"""
        return self.request("GET", "/cameras/{camera}", **kwargs)

    def patch_cameras_by_camera(self, **kwargs):
        """Patch camera"""
        return self.request("PATCH", "/cameras/{camera}", **kwargs)

    def put_cameras_by_camera(self, **kwargs):
        """Mettre a jour une camera"""
        return self.request("PUT", "/cameras/{camera}", **kwargs)

    def get_cameras_by_camera_access_logs(self, **kwargs):
        """Lister les logs d'acces camera"""
        return self.request("GET", "/cameras/{camera}/access-logs", **kwargs)

    def get_cameras_by_camera_access_tokens(self, **kwargs):
        """Lister les tokens de partage"""
        return self.request("GET", "/cameras/{camera}/access-tokens", **kwargs)

    def post_cameras_by_camera_access_tokens(self, **kwargs):
        """Creer un token de partage"""
        return self.request("POST", "/cameras/{camera}/access-tokens", **kwargs)

    def delete_cameras_by_camera_access_tokens_by_token(self, **kwargs):
        """Revoquer un token de partage"""
        return self.request("DELETE", "/cameras/{camera}/access-tokens/{token}", **kwargs)

    def get_cameras_by_camera_permissions(self, **kwargs):
        """Lister les permissions internes"""
        return self.request("GET", "/cameras/{camera}/permissions", **kwargs)

    def post_cameras_by_camera_permissions(self, **kwargs):
        """Creer ou remplacer une permission interne"""
        return self.request("POST", "/cameras/{camera}/permissions", **kwargs)

    def delete_cameras_by_camera_permissions_by_permission(self, **kwargs):
        """Supprimer une permission interne"""
        return self.request("DELETE", "/cameras/{camera}/permissions/{permission}", **kwargs)

    def get_cameras_by_camera_stream_token(self, **kwargs):
        """Regenerer un stream token client"""
        return self.request("GET", "/cameras/{camera}/stream-token", **kwargs)

    def post_cameras_test_rtsp(self, **kwargs):
        """Tester une URL RTSP"""
        return self.request("POST", "/cameras/test-rtsp", **kwargs)

    def post_client_events(self, **kwargs):
        """Persister un evenement UX client tenant-scope"""
        return self.request("POST", "/client-events", **kwargs)

    def get_communication_analytics(self, **kwargs):
        """Analytics communication tenant"""
        return self.request("GET", "/communication/analytics", **kwargs)

    def get_company_branding(self, **kwargs):
        """Lire l'identite visuelle de l'entreprise courante"""
        return self.request("GET", "/company/branding", **kwargs)

    def patch_company_branding(self, **kwargs):
        """Mettre a jour l'identite visuelle entreprise"""
        return self.request("PATCH", "/company/branding", **kwargs)

    def get_company_qr_onboarding(self, **kwargs):
        """Generer le QR onboarding entreprise"""
        return self.request("GET", "/company/qr-onboarding", **kwargs)

    def post_company_qr_onboarding_create_employee(self, **kwargs):
        """Creer un employe depuis QR"""
        return self.request("POST", "/company/qr-onboarding/create-employee", **kwargs)

    def post_company_qr_onboarding_scan_employee(self, **kwargs):
        """Lire un QR employe pour pre-remplir l'ajout manager"""
        return self.request("POST", "/company/qr-onboarding/scan-employee", **kwargs)

    def get_contracts(self, **kwargs):
        """Lister les contrats"""
        return self.request("GET", "/contracts", **kwargs)

    def post_contracts(self, **kwargs):
        """Creer un contrat"""
        return self.request("POST", "/contracts", **kwargs)

    def get_contracts_by_contract(self, **kwargs):
        """Voir un contrat"""
        return self.request("GET", "/contracts/{contract}", **kwargs)

    def put_contracts_by_contract(self, **kwargs):
        """Modifier un contrat"""
        return self.request("PUT", "/contracts/{contract}", **kwargs)

    def post_contracts_by_contract_activate(self, **kwargs):
        """Activer un contrat draft"""
        return self.request("POST", "/contracts/{contract}/activate", **kwargs)

    def get_contracts_by_contract_amendments(self, **kwargs):
        """Lister les avenants"""
        return self.request("GET", "/contracts/{contract}/amendments", **kwargs)

    def post_contracts_by_contract_amendments(self, **kwargs):
        """Creer un avenant"""
        return self.request("POST", "/contracts/{contract}/amendments", **kwargs)

    def get_contracts_by_contract_generate_pdf(self, **kwargs):
        """Donnees PDF du contrat"""
        return self.request("GET", "/contracts/{contract}/generate-pdf", **kwargs)

    def post_contracts_by_contract_renew(self, **kwargs):
        """Renouveler un contrat"""
        return self.request("POST", "/contracts/{contract}/renew", **kwargs)

    def post_contracts_by_contract_suspend(self, **kwargs):
        """Suspendre un contrat actif"""
        return self.request("POST", "/contracts/{contract}/suspend", **kwargs)

    def post_contracts_by_contract_terminate(self, **kwargs):
        """Resilier un contrat"""
        return self.request("POST", "/contracts/{contract}/terminate", **kwargs)

    def get_contracts_expiring(self, **kwargs):
        """Contrats expirant bientot"""
        return self.request("GET", "/contracts/expiring", **kwargs)

    def simulatecotisations(self, **kwargs):
        """Simuler les cotisations sociales employe/employeur pour un salaire brut donne, sans persister (manager)"""
        return self.request("POST", "/cotisation-simulation", **kwargs)

    def get_dashboard_kpi(self, **kwargs):
        """KPIs detailles"""
        return self.request("GET", "/dashboard/kpi", **kwargs)

    def get_dashboard_manager_digest(self, **kwargs):
        """Lire les signaux manager du jour"""
        return self.request("GET", "/dashboard/manager-digest", **kwargs)

    def get_dashboard_recent_activity(self, **kwargs):
        """Activite recente"""
        return self.request("GET", "/dashboard/recent-activity", **kwargs)

    def get_dashboard_summary(self, **kwargs):
        """Resume dashboard"""
        return self.request("GET", "/dashboard/summary", **kwargs)

    def delete_device_tokens(self, **kwargs):
        """Supprimer le token FCM du device courant au logout"""
        return self.request("DELETE", "/device-tokens", **kwargs)

    def get_device_tokens(self, **kwargs):
        """Lister les tokens push actifs de l'utilisateur courant"""
        return self.request("GET", "/device-tokens", **kwargs)

    def post_device_tokens(self, **kwargs):
        """Enregistrer ou rafraichir le token FCM du device courant"""
        return self.request("POST", "/device-tokens", **kwargs)

    def get_employees(self, **kwargs):
        """Lister les employes"""
        return self.request("GET", "/employees", **kwargs)

    def post_employees(self, **kwargs):
        """Creer un employe"""
        return self.request("POST", "/employees", **kwargs)

    def get_employees_by_employee(self, **kwargs):
        """Voir un employe"""
        return self.request("GET", "/employees/{employee}", **kwargs)

    def patch_employees_by_employee(self, **kwargs):
        """Patch employe"""
        return self.request("PATCH", "/employees/{employee}", **kwargs)

    def put_employees_by_employee(self, **kwargs):
        """Mettre a jour un employe"""
        return self.request("PUT", "/employees/{employee}", **kwargs)

    def post_employees_by_employee_archive(self, **kwargs):
        """Archiver un employe"""
        return self.request("POST", "/employees/{employee}/archive", **kwargs)

    def get_employees_by_employee_certificate_of_employment(self, **kwargs):
        """Certificat de travail PDF (fin de contrat, F-08)"""
        return self.request("GET", "/employees/{employee}/certificate-of-employment", **kwargs)

    def get_employees_by_employee_daily_summary(self, **kwargs):
        """Resume journalier d'un employe"""
        return self.request("GET", "/employees/{employee}/daily-summary", **kwargs)

    def get_employees_by_employee_end_of_contract(self, **kwargs):
        """Solde de tout compte (fin de contrat, F-08)"""
        return self.request("GET", "/employees/{employee}/end-of-contract", **kwargs)

    def get_employees_by_employee_quick_estimate(self, **kwargs):
        """Estimation sur periode"""
        return self.request("GET", "/employees/{employee}/quick-estimate", **kwargs)

    def get_employees_by_employee_receipt(self, **kwargs):
        """Telecharger le PDF d'estimation"""
        return self.request("GET", "/employees/{employee}/receipt", **kwargs)

    def post_employees_import(self, **kwargs):
        """Importer des employes par CSV"""
        return self.request("POST", "/employees/import", **kwargs)

    def get_employees_import_template(self, **kwargs):
        """Template CSV import"""
        return self.request("GET", "/employees/import-template", **kwargs)

    def get_evaluations(self, **kwargs):
        """Lister les evaluations"""
        return self.request("GET", "/evaluations", **kwargs)

    def post_evaluations(self, **kwargs):
        """Creer une evaluation"""
        return self.request("POST", "/evaluations", **kwargs)

    def delete_evaluations_by_evaluation(self, **kwargs):
        """Supprimer une evaluation"""
        return self.request("DELETE", "/evaluations/{evaluation}", **kwargs)

    def get_evaluations_by_evaluation(self, **kwargs):
        """Voir une evaluation"""
        return self.request("GET", "/evaluations/{evaluation}", **kwargs)

    def patch_evaluations_by_evaluation(self, **kwargs):
        """Mettre a jour partiellement une evaluation"""
        return self.request("PATCH", "/evaluations/{evaluation}", **kwargs)

    def put_evaluations_by_evaluation(self, **kwargs):
        """Mettre a jour une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}", **kwargs)

    def put_evaluations_by_evaluation_acknowledge(self, **kwargs):
        """Accuser reception d'une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}/acknowledge", **kwargs)

    def put_evaluations_by_evaluation_submit(self, **kwargs):
        """Soumettre une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}/submit", **kwargs)

    def get_expense_claims(self, **kwargs):
        """Lister les notes de frais"""
        return self.request("GET", "/expense-claims", **kwargs)

    def post_expense_claims(self, **kwargs):
        """Creer une note de frais"""
        return self.request("POST", "/expense-claims", **kwargs)

    def get_expense_claims_by_expenseclaim(self, **kwargs):
        """Voir une note de frais"""
        return self.request("GET", "/expense-claims/{expenseClaim}", **kwargs)

    def post_expense_claims_by_expenseclaim_approve(self, **kwargs):
        """Approuver une note de frais"""
        return self.request("POST", "/expense-claims/{expenseClaim}/approve", **kwargs)

    def post_expense_claims_by_expenseclaim_reject(self, **kwargs):
        """Rejeter une note de frais"""
        return self.request("POST", "/expense-claims/{expenseClaim}/reject", **kwargs)

    def post_expense_claims_by_expenseclaim_submit(self, **kwargs):
        """Soumettre une note de frais"""
        return self.request("POST", "/expense-claims/{expenseClaim}/submit", **kwargs)

    def exportpayslips(self, **kwargs):
        """Exporter les bulletins de paie de l'entreprise (JSON ou CSV encode en JSON) - manager uniquement"""
        return self.request("GET", "/export/pay-slips", **kwargs)

    def get_exports_absences(self, **kwargs):
        """Exporter les absences"""
        return self.request("GET", "/exports/absences", **kwargs)

    def get_exports_attendance(self, **kwargs):
        """Exporter le pointage"""
        return self.request("GET", "/exports/attendance", **kwargs)

    def get_exports_contracts(self, **kwargs):
        """Exporter les contrats"""
        return self.request("GET", "/exports/contracts", **kwargs)

    def get_exports_employees(self, **kwargs):
        """Exporter les employes"""
        return self.request("GET", "/exports/employees", **kwargs)

    def get_exports_history(self, **kwargs):
        """Historique des exports"""
        return self.request("GET", "/exports/history", **kwargs)

    def get_exports_pay_slips(self, **kwargs):
        """Exporter les bulletins"""
        return self.request("GET", "/exports/pay-slips", **kwargs)

    def get_exports_training(self, **kwargs):
        """Exporter les formations"""
        return self.request("GET", "/exports/training", **kwargs)

    def get_exports_vehicles(self, **kwargs):
        """Exporter la flotte"""
        return self.request("GET", "/exports/vehicles", **kwargs)

    def checkfeatureflag(self, **kwargs):
        """Verifier si une fonctionnalite est activee pour le plan de l'entreprise courante"""
        return self.request("GET", "/feature-flags/check/{featureKey}", **kwargs)

    def getfeatureflagmatrix(self, **kwargs):
        """Voir la matrice complete feature x plan"""
        return self.request("GET", "/feature-flags/matrix", **kwargs)

    def updatefeatureflagmatrix(self, **kwargs):
        """Modifier la matrice feature x plan (reserve a l'administration plateforme)"""
        return self.request("PUT", "/feature-flags/matrix", **kwargs)

    def getfeaturebykey(self, **kwargs):
        """Voir le detail d'une fonctionnalite du registre"""
        return self.request("GET", "/features/{key}", **kwargs)

    def getfeatureregistrystatistics(self, **kwargs):
        """Statistiques du registre de fonctionnalites (admin)"""
        return self.request("GET", "/features/admin/statistics", **kwargs)

    def synchronizefeatureregistry(self, **kwargs):
        """Synchroniser manuellement le registre de fonctionnalites (admin)"""
        return self.request("POST", "/features/admin/synchronize", **kwargs)

    def getcompatiblefeatures(self, **kwargs):
        """Lister les fonctionnalites compatibles avec une version mobile donnee"""
        return self.request("GET", "/features/compatible/{version}", **kwargs)

    def getfeaturemanifest(self, **kwargs):
        """Obtenir le manifeste des fonctionnalites disponibles pour l'utilisateur courant"""
        return self.request("GET", "/features/manifest", **kwargs)

    def get_fleet_live_map(self, **kwargs):
        """Carte temps reel des vehicules"""
        return self.request("GET", "/fleet/live-map", **kwargs)

    def get_fleet_overview(self, **kwargs):
        """Vue d'ensemble de la flotte"""
        return self.request("GET", "/fleet/overview", **kwargs)

    def get_fleet_reports_fuel(self, **kwargs):
        """Rapport consommation carburant"""
        return self.request("GET", "/fleet/reports/fuel", **kwargs)

    def get_fleet_reports_maintenance_due(self, **kwargs):
        """Vehicules necessitant une maintenance"""
        return self.request("GET", "/fleet/reports/maintenance-due", **kwargs)

    def get_fleet_reports_mileage(self, **kwargs):
        """Rapport kilometrage"""
        return self.request("GET", "/fleet/reports/mileage", **kwargs)

    def get_health(self, **kwargs):
        """Healthcheck live + ready"""
        return self.request("GET", "/health", **kwargs)

    def get_i18n_by_locale(self, **kwargs):
        """Traductions pour une locale"""
        return self.request("GET", "/i18n/{locale}", **kwargs)

    def get_internal_camera_token_verify(self, **kwargs):
        """Verification interne MediaMTX"""
        return self.request("GET", "/internal/camera-token/verify", **kwargs)

    def get_invitations(self, **kwargs):
        """Lister les invitations de l'entreprise"""
        return self.request("GET", "/invitations", **kwargs)

    def post_invitations_by_invitation_resend(self, **kwargs):
        """Renvoyer une invitation"""
        return self.request("POST", "/invitations/{invitation}/resend", **kwargs)

    def post_kiosks(self, **kwargs):
        """Enregistrer un kiosk"""
        return self.request("POST", "/kiosks", **kwargs)

    def post_kiosks_by_devicecode_punch(self, **kwargs):
        """Pointage via kiosk"""
        return self.request("POST", "/kiosks/{deviceCode}/punch", **kwargs)

    def get_kiosks_by_devicecode_roster(self, **kwargs):
        """Roster biometrie d'un kiosk"""
        return self.request("GET", "/kiosks/{deviceCode}/roster", **kwargs)

    def post_kiosks_by_devicecode_sync(self, **kwargs):
        """Synchroniser des evenements offline"""
        return self.request("POST", "/kiosks/{deviceCode}/sync", **kwargs)

    def get_launch_readiness(self, **kwargs):
        """Lire le score de readiness lancement du tenant"""
        return self.request("GET", "/launch-readiness", **kwargs)

    def get_leave_accruals(self, **kwargs):
        """Lister les accruals"""
        return self.request("GET", "/leave-accruals", **kwargs)

    def post_leave_accruals(self, **kwargs):
        """Creer un accrual"""
        return self.request("POST", "/leave-accruals", **kwargs)

    def get_leave_balances(self, **kwargs):
        """Soldes de conges globaux (manager)"""
        return self.request("GET", "/leave-balances", **kwargs)

    def get_leave_policies(self, **kwargs):
        """Lister les politiques de conges"""
        return self.request("GET", "/leave-policies", **kwargs)

    def post_leave_policies(self, **kwargs):
        """Creer une politique de conges"""
        return self.request("POST", "/leave-policies", **kwargs)

    def delete_leave_policies_by_leavepolicy(self, **kwargs):
        """Supprimer une politique"""
        return self.request("DELETE", "/leave-policies/{leavePolicy}", **kwargs)

    def get_leave_policies_by_leavepolicy(self, **kwargs):
        """Voir une politique"""
        return self.request("GET", "/leave-policies/{leavePolicy}", **kwargs)

    def put_leave_policies_by_leavepolicy(self, **kwargs):
        """Modifier une politique"""
        return self.request("PUT", "/leave-policies/{leavePolicy}", **kwargs)

    def get_loans(self, **kwargs):
        """Lister les prets"""
        return self.request("GET", "/loans", **kwargs)

    def post_loans(self, **kwargs):
        """Demander un pret"""
        return self.request("POST", "/loans", **kwargs)

    def get_loans_by_employeeloan(self, **kwargs):
        """Voir un pret"""
        return self.request("GET", "/loans/{employeeLoan}", **kwargs)

    def post_loans_by_employeeloan_approve(self, **kwargs):
        """Approuver un pret"""
        return self.request("POST", "/loans/{employeeLoan}/approve", **kwargs)

    def post_loans_by_employeeloan_disburse(self, **kwargs):
        """Decaisser un pret"""
        return self.request("POST", "/loans/{employeeLoan}/disburse", **kwargs)

    def get_marketing_social_account(self, **kwargs):
        """Compte social connecte du tenant"""
        return self.request("GET", "/marketing/social-account", **kwargs)

    def post_marketing_social_account_connect(self, **kwargs):
        """Connecter un compte social (agregateur Ayrshare)"""
        return self.request("POST", "/marketing/social-account/connect", **kwargs)

    def post_marketing_social_account_disconnect(self, **kwargs):
        """Deconnecter le compte social du tenant"""
        return self.request("POST", "/marketing/social-account/disconnect", **kwargs)

    def get_marketing_social_posts(self, **kwargs):
        """Lister les publications reseaux sociaux du tenant"""
        return self.request("GET", "/marketing/social-posts", **kwargs)

    def post_marketing_social_posts(self, **kwargs):
        """Creer une publication (brouillon, ou planifiee/publiee si scheduled_at fourni)"""
        return self.request("POST", "/marketing/social-posts", **kwargs)

    def delete_marketing_social_posts_by_socialpost(self, **kwargs):
        """Supprimer une publication (draft uniquement)"""
        return self.request("DELETE", "/marketing/social-posts/{socialPost}", **kwargs)

    def get_marketing_social_posts_by_socialpost(self, **kwargs):
        """Detail d'une publication"""
        return self.request("GET", "/marketing/social-posts/{socialPost}", **kwargs)

    def patch_marketing_social_posts_by_socialpost(self, **kwargs):
        """Modifier une publication (draft uniquement)"""
        return self.request("PATCH", "/marketing/social-posts/{socialPost}", **kwargs)

    def post_marketing_social_posts_by_socialpost_publish(self, **kwargs):
        """Publier immediatement ou (re)planifier une publication"""
        return self.request("POST", "/marketing/social-posts/{socialPost}/publish", **kwargs)

    def get_me_balance(self, **kwargs):
        """Mon solde de paie courant"""
        return self.request("GET", "/me/balance", **kwargs)

    def get_me_career(self, **kwargs):
        """Lire le parcours professionnel durable de l'employe courant"""
        return self.request("GET", "/me/career", **kwargs)

    def post_me_company_qr_scan(self, **kwargs):
        """Soumettre une demande d'integration via QR entreprise"""
        return self.request("POST", "/me/company-qr/scan", **kwargs)

    def get_me_contracts(self, **kwargs):
        """Mes contrats"""
        return self.request("GET", "/me/contracts", **kwargs)

    def get_me_daily_summary(self, **kwargs):
        """Resume journalier utilisateur courant"""
        return self.request("GET", "/me/daily-summary", **kwargs)

    def get_me_leave_balances(self, **kwargs):
        """Mes soldes de conges"""
        return self.request("GET", "/me/leave-balances", **kwargs)

    def get_me_loans(self, **kwargs):
        """Mes prets"""
        return self.request("GET", "/me/loans", **kwargs)

    def get_me_loans_by_loan_repayments(self, **kwargs):
        """Mes remboursements de pret"""
        return self.request("GET", "/me/loans/{loan}/repayments", **kwargs)

    def get_me_monthly_summary(self, **kwargs):
        """Resume mensuel utilisateur courant"""
        return self.request("GET", "/me/monthly-summary", **kwargs)

    def get_me_pay_slips(self, **kwargs):
        """Mes bulletins de paie"""
        return self.request("GET", "/me/pay-slips", **kwargs)

    def showmypayslip(self, **kwargs):
        """Voir un de mes bulletins de paie"""
        return self.request("GET", "/me/pay-slips/{paySlip}", **kwargs)

    def downloadmypayslippdf(self, **kwargs):
        """Telecharger un de mes bulletins de paie en PDF"""
        return self.request("GET", "/me/pay-slips/{paySlip}/pdf", **kwargs)

    def get_me_payment_documents(self, **kwargs):
        """Mes documents de paiement"""
        return self.request("GET", "/me/payment-documents", **kwargs)

    def get_me_payment_documents_by_paymentdocument_download(self, **kwargs):
        """Telecharger un document de paiement"""
        return self.request("GET", "/me/payment-documents/{paymentDocument}/download", **kwargs)

    def get_me_qr_profile(self, **kwargs):
        """Generer le QR profil employe"""
        return self.request("GET", "/me/qr-profile", **kwargs)

    def get_me_quick_estimate(self, **kwargs):
        """Estimation utilisateur courant"""
        return self.request("GET", "/me/quick-estimate", **kwargs)

    def get_me_trainings(self, **kwargs):
        """Mes formations"""
        return self.request("GET", "/me/trainings", **kwargs)

    def post_me_trainings_by_session_enroll(self, **kwargs):
        """Auto-inscription a une formation"""
        return self.request("POST", "/me/trainings/{session}/enroll", **kwargs)

    def get_notification_preferences(self, **kwargs):
        """Lire les preferences de notification de l'utilisateur courant"""
        return self.request("GET", "/notification-preferences", **kwargs)

    def patch_notification_preferences(self, **kwargs):
        """Mettre a jour les preferences de notification de l'utilisateur courant"""
        return self.request("PATCH", "/notification-preferences", **kwargs)

    def get_notifications(self, **kwargs):
        """Lister les notifications de l'utilisateur courant"""
        return self.request("GET", "/notifications", **kwargs)

    def delete_notifications_by_notification(self, **kwargs):
        """Supprimer une notification"""
        return self.request("DELETE", "/notifications/{notification}", **kwargs)

    def put_notifications_by_notification_read(self, **kwargs):
        """Marquer une notification comme lue"""
        return self.request("PUT", "/notifications/{notification}/read", **kwargs)

    def put_notifications_read_all(self, **kwargs):
        """Marquer toutes les notifications comme lues"""
        return self.request("PUT", "/notifications/read-all", **kwargs)

    def patch_onboarding_setup_by_stepkey_complete(self, **kwargs):
        """Marquer une étape comme complète"""
        return self.request("PATCH", "/onboarding-setup/{stepKey}/complete", **kwargs)

    def patch_onboarding_setup_by_stepkey_skip(self, **kwargs):
        """Ignorer une étape d'onboarding"""
        return self.request("PATCH", "/onboarding-setup/{stepKey}/skip", **kwargs)

    def get_onboarding_setup_checklist(self, **kwargs):
        """Récupérer la checklist d'onboarding"""
        return self.request("GET", "/onboarding-setup/checklist", **kwargs)

    def get_onboarding_setup_progress(self, **kwargs):
        """Progression globale de l'onboarding"""
        return self.request("GET", "/onboarding-setup/progress", **kwargs)

    def get_org_chart(self, **kwargs):
        """Organigramme complet"""
        return self.request("GET", "/org-chart", **kwargs)

    def get_org_chart_by_employeeid_manager_chain(self, **kwargs):
        """Chaine hierarchique"""
        return self.request("GET", "/org-chart/{employeeId}/manager-chain", **kwargs)

    def get_org_chart_by_employeeid_subordinates(self, **kwargs):
        """Subordonnes d'un employe"""
        return self.request("GET", "/org-chart/{employeeId}/subordinates", **kwargs)

    def post_partner_apply(self, **kwargs):
        """Candidature partenaire"""
        return self.request("POST", "/partner/apply", **kwargs)

    def get_partner_companies(self, **kwargs):
        """Entreprises parrainées par le partenaire"""
        return self.request("GET", "/partner/companies", **kwargs)

    def post_partner_payout(self, **kwargs):
        """Demande de versement commission"""
        return self.request("POST", "/partner/payout", **kwargs)

    def get_partner_stats(self, **kwargs):
        """Statistiques partenaire connecté"""
        return self.request("GET", "/partner/stats", **kwargs)

    def get_pay_slips(self, **kwargs):
        """Lister les bulletins du tenant (manager)"""
        return self.request("GET", "/pay-slips", **kwargs)

    def get_pay_slips_by_payslip(self, **kwargs):
        """Voir un bulletin de paie"""
        return self.request("GET", "/pay-slips/{paySlip}", **kwargs)

    def get_pay_slips_by_payslip_pdf(self, **kwargs):
        """Telecharger bulletin PDF"""
        return self.request("GET", "/pay-slips/{paySlip}/pdf", **kwargs)

    def get_payment_batches(self, **kwargs):
        """Lister les lots de paiement"""
        return self.request("GET", "/payment-batches", **kwargs)

    def post_payment_batches(self, **kwargs):
        """Creer un lot de paiement depuis un cycle paie"""
        return self.request("POST", "/payment-batches", **kwargs)

    def get_payment_batches_by_paymentbatch(self, **kwargs):
        """Detail d'un lot de paiement"""
        return self.request("GET", "/payment-batches/{paymentBatch}", **kwargs)

    def post_payment_batches_by_paymentbatch_mark_paid(self, **kwargs):
        """Declarer un lot de paiement comme envoye"""
        return self.request("POST", "/payment-batches/{paymentBatch}/mark-paid", **kwargs)

    def post_payment_confirmations_by_paymentitem_confirm(self, **kwargs):
        """Confirmer la reception d'un paiement"""
        return self.request("POST", "/payment-confirmations/{paymentItem}/confirm", **kwargs)

    def get_payments_by_payrollrun_documents(self, **kwargs):
        """Alias mobile pour documents de paiement d'un cycle"""
        return self.request("GET", "/payments/{payrollRun}/documents", **kwargs)

    def get_payroll_runs(self, **kwargs):
        """Lister les sessions de paie"""
        return self.request("GET", "/payroll-runs", **kwargs)

    def post_payroll_runs(self, **kwargs):
        """Creer une session de paie"""
        return self.request("POST", "/payroll-runs", **kwargs)

    def get_payroll_runs_by_payrollrun(self, **kwargs):
        """Voir une session de paie"""
        return self.request("GET", "/payroll-runs/{payrollRun}", **kwargs)

    def post_payroll_runs_by_payrollrun_calculate(self, **kwargs):
        """Calculer la paie"""
        return self.request("POST", "/payroll-runs/{payrollRun}/calculate", **kwargs)

    def post_payroll_runs_by_payrollrun_cancel(self, **kwargs):
        """Annuler une session de paie"""
        return self.request("POST", "/payroll-runs/{payrollRun}/cancel", **kwargs)

    def get_payroll_runs_by_payrollrun_journal(self, **kwargs):
        """Journal de paie mensuel CSV (F-10)"""
        return self.request("GET", "/payroll-runs/{payrollRun}/journal", **kwargs)

    def listpayrollrunpayslips(self, **kwargs):
        """Lister les bulletins de paie d'une session"""
        return self.request("GET", "/payroll-runs/{payrollRun}/pay-slips", **kwargs)

    def get_payroll_runs_by_payrollrun_payment_documents(self, **kwargs):
        """Documents de paiement d'un cycle paie"""
        return self.request("GET", "/payroll-runs/{payrollRun}/payment-documents", **kwargs)

    def get_payroll_runs_by_payrollrun_summary(self, **kwargs):
        """Resume de la session de paie"""
        return self.request("GET", "/payroll-runs/{payrollRun}/summary", **kwargs)

    def post_payroll_runs_by_payrollrun_validate(self, **kwargs):
        """Valider la session de paie"""
        return self.request("POST", "/payroll-runs/{payrollRun}/validate", **kwargs)

    def get_payroll_cycles_preview(self, **kwargs):
        """Previsualiser un cycle de paie candidat"""
        return self.request("GET", "/payroll/cycles/preview", **kwargs)

    def get_payroll_mobile_summary(self, **kwargs):
        """Resume mobile des soldes paie equipe"""
        return self.request("GET", "/payroll/mobile-summary", **kwargs)

    def post_platform_auth_login(self, **kwargs):
        """Connexion super-admin"""
        return self.request("POST", "/platform/auth/login", **kwargs)

    def post_platform_auth_logout(self, **kwargs):
        """Deconnexion super-admin"""
        return self.request("POST", "/platform/auth/logout", **kwargs)

    def get_platform_auth_me(self, **kwargs):
        """Super-admin courant"""
        return self.request("GET", "/platform/auth/me", **kwargs)

    def get_platform_companies(self, **kwargs):
        """Lister les societes"""
        return self.request("GET", "/platform/companies", **kwargs)

    def post_platform_companies(self, **kwargs):
        """Creer une societe shared"""
        return self.request("POST", "/platform/companies", **kwargs)

    def get_platform_companies_by_company_features(self, **kwargs):
        """Lire les feature flags d'une societe"""
        return self.request("GET", "/platform/companies/{company}/features", **kwargs)

    def patch_platform_companies_by_company_features(self, **kwargs):
        """Mettre a jour les feature flags d'une societe"""
        return self.request("PATCH", "/platform/companies/{company}/features", **kwargs)

    def get_platform_companies_by_company_health(self, **kwargs):
        """Health detaille d'une societe"""
        return self.request("GET", "/platform/companies/{company}/health", **kwargs)

    def get_platform_companies_by_company_subscription(self, **kwargs):
        """Lire l'abonnement plateforme d'une societe"""
        return self.request("GET", "/platform/companies/{company}/subscription", **kwargs)

    def patch_platform_companies_by_company_subscription(self, **kwargs):
        """Mettre a jour l'abonnement plateforme d'une societe"""
        return self.request("PATCH", "/platform/companies/{company}/subscription", **kwargs)

    def get_platform_companies_health(self, **kwargs):
        """Vue portefeuille health des societes"""
        return self.request("GET", "/platform/companies/health", **kwargs)

    def get_platform_company_requests(self, **kwargs):
        """Lister les demandes de creation de societe"""
        return self.request("GET", "/platform/company-requests", **kwargs)

    def get_platform_company_requests_by_id(self, **kwargs):
        """Lire une demande de creation de societe"""
        return self.request("GET", "/platform/company-requests/{id}", **kwargs)

    def patch_platform_company_requests_by_id(self, **kwargs):
        """Approuver ou rejeter une demande de creation de societe"""
        return self.request("PATCH", "/platform/company-requests/{id}", **kwargs)

    def get_platform_country_defaults(self, **kwargs):
        """Lister les pays supportes et leurs defaults"""
        return self.request("GET", "/platform/country-defaults", **kwargs)

    def get_platform_growth_partners(self, **kwargs):
        """Lister les partenaires (admin)"""
        return self.request("GET", "/platform/growth/partners", **kwargs)

    def patch_platform_growth_partners_by_partner_rate(self, **kwargs):
        """Mettre à jour le taux de commission d'un partenaire"""
        return self.request("PATCH", "/platform/growth/partners/{partner}/rate", **kwargs)

    def get_platform_growth_payouts(self, **kwargs):
        """Lister les demandes de versement"""
        return self.request("GET", "/platform/growth/payouts", **kwargs)

    def get_platform_metrics_overview(self, **kwargs):
        """Agregats business du cockpit super-admin"""
        return self.request("GET", "/platform/metrics/overview", **kwargs)

    def get_platform_plans(self, **kwargs):
        """Lister le catalogue des plans SaaS"""
        return self.request("GET", "/platform/plans", **kwargs)

    def get_positions(self, **kwargs):
        """Lister les postes"""
        return self.request("GET", "/positions", **kwargs)

    def post_positions(self, **kwargs):
        """Creer un poste"""
        return self.request("POST", "/positions", **kwargs)

    def delete_positions_by_position(self, **kwargs):
        """Supprimer un poste"""
        return self.request("DELETE", "/positions/{position}", **kwargs)

    def get_positions_by_position(self, **kwargs):
        """Voir un poste"""
        return self.request("GET", "/positions/{position}", **kwargs)

    def put_positions_by_position(self, **kwargs):
        """Modifier un poste"""
        return self.request("PUT", "/positions/{position}", **kwargs)

    def get_predictions_absenteeism(self, **kwargs):
        """Predire les risques d'absenteisme"""
        return self.request("GET", "/predictions/absenteeism", **kwargs)

    def get_predictions_notifications(self, **kwargs):
        """Notifications RH proactives generees par l'IA"""
        return self.request("GET", "/predictions/notifications", **kwargs)

    def get_predictions_turnover(self, **kwargs):
        """Predire le risque de turnover par employe"""
        return self.request("GET", "/predictions/turnover", **kwargs)

    def patch_privacy_biometric_consent(self, **kwargs):
        """Enregistrer ou retirer le consentement biometrique"""
        return self.request("PATCH", "/privacy/biometric-consent", **kwargs)

    def post_privacy_deletion_request(self, **kwargs):
        """Creer une demande de suppression non destructive"""
        return self.request("POST", "/privacy/deletion-request", **kwargs)

    def get_privacy_export(self, **kwargs):
        """Exporter les donnees personnelles de l'employe authentifie"""
        return self.request("GET", "/privacy/export", **kwargs)

    def get_projects(self, **kwargs):
        """Lister les projets"""
        return self.request("GET", "/projects", **kwargs)

    def post_projects(self, **kwargs):
        """Creer un projet"""
        return self.request("POST", "/projects", **kwargs)

    def delete_projects_by_project(self, **kwargs):
        """Supprimer un projet"""
        return self.request("DELETE", "/projects/{project}", **kwargs)

    def get_projects_by_project(self, **kwargs):
        """Voir un projet"""
        return self.request("GET", "/projects/{project}", **kwargs)

    def patch_projects_by_project(self, **kwargs):
        """Mettre a jour partiellement un projet"""
        return self.request("PATCH", "/projects/{project}", **kwargs)

    def put_projects_by_project(self, **kwargs):
        """Mettre a jour un projet"""
        return self.request("PUT", "/projects/{project}", **kwargs)

    def post_push_notifications_send(self, **kwargs):
        """Envoyer une notification push de test a un employe"""
        return self.request("POST", "/push-notifications/send", **kwargs)

    def put_recruitment_applicants_by_applicant(self, **kwargs):
        """Modifier un candidat"""
        return self.request("PUT", "/recruitment/applicants/{applicant}", **kwargs)

    def post_recruitment_applicants_by_applicant_interviews(self, **kwargs):
        """Planifier un entretien"""
        return self.request("POST", "/recruitment/applicants/{applicant}/interviews", **kwargs)

    def put_recruitment_interviews_by_interview(self, **kwargs):
        """Modifier un entretien"""
        return self.request("PUT", "/recruitment/interviews/{interview}", **kwargs)

    def get_recruitment_jobs(self, **kwargs):
        """Lister les offres d'emploi"""
        return self.request("GET", "/recruitment/jobs", **kwargs)

    def post_recruitment_jobs(self, **kwargs):
        """Creer une offre d'emploi"""
        return self.request("POST", "/recruitment/jobs", **kwargs)

    def get_recruitment_jobs_by_jobposting(self, **kwargs):
        """Voir une offre"""
        return self.request("GET", "/recruitment/jobs/{jobPosting}", **kwargs)

    def put_recruitment_jobs_by_jobposting(self, **kwargs):
        """Modifier une offre"""
        return self.request("PUT", "/recruitment/jobs/{jobPosting}", **kwargs)

    def get_recruitment_jobs_by_jobposting_applicants(self, **kwargs):
        """Lister les candidats"""
        return self.request("GET", "/recruitment/jobs/{jobPosting}/applicants", **kwargs)

    def post_recruitment_jobs_by_jobposting_applicants(self, **kwargs):
        """Ajouter un candidat"""
        return self.request("POST", "/recruitment/jobs/{jobPosting}/applicants", **kwargs)

    def post_recruitment_jobs_by_jobposting_close(self, **kwargs):
        """Cloturer une offre"""
        return self.request("POST", "/recruitment/jobs/{jobPosting}/close", **kwargs)

    def post_recruitment_jobs_by_jobposting_publish(self, **kwargs):
        """Publier une offre"""
        return self.request("POST", "/recruitment/jobs/{jobPosting}/publish", **kwargs)

    def get_salary_advances(self, **kwargs):
        """Lister les avances sur salaire"""
        return self.request("GET", "/salary-advances", **kwargs)

    def post_salary_advances(self, **kwargs):
        """Demander une avance sur salaire"""
        return self.request("POST", "/salary-advances", **kwargs)

    def delete_salary_advances_by_salaryadvance(self, **kwargs):
        """Annuler une avance (employe proprietaire)"""
        return self.request("DELETE", "/salary-advances/{salaryAdvance}", **kwargs)

    def get_salary_advances_by_salaryadvance(self, **kwargs):
        """Voir une avance"""
        return self.request("GET", "/salary-advances/{salaryAdvance}", **kwargs)

    def put_salary_advances_by_salaryadvance_approve(self, **kwargs):
        """Approuver une avance (manager)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/approve", **kwargs)

    def put_salary_advances_by_salaryadvance_confirm_received(self, **kwargs):
        """Confirmer la reception de l'avance (employe)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/confirm-received", **kwargs)

    def disputesalaryadvance(self, **kwargs):
        """Ouvrir une reclamation sur une avance dont le paiement a ete declare mais non recu (employe)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/dispute", **kwargs)

    def put_salary_advances_by_salaryadvance_manager_approve(self, **kwargs):
        """Valider une avance avant paiement (manager/RH)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/manager-approve", **kwargs)

    def put_salary_advances_by_salaryadvance_mark_paid(self, **kwargs):
        """Declarer l'avance comme envoyee (manager/RH)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/mark-paid", **kwargs)

    def downloadsalaryadvanceproof(self, **kwargs):
        """Telecharger le justificatif joint a une demande d'avance (employe proprietaire ou manager)"""
        return self.request("GET", "/salary-advances/{salaryAdvance}/proof", **kwargs)

    def put_salary_advances_by_salaryadvance_reject(self, **kwargs):
        """Rejeter une avance (manager)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/reject", **kwargs)

    def resolvesalaryadvancedispute(self, **kwargs):
        """Resoudre une reclamation sur une avance (manager/RH)"""
        return self.request("PUT", "/salary-advances/{salaryAdvance}/resolve-dispute", **kwargs)

    def listsalarycomponents(self, **kwargs):
        """Lister les composants de salaire (manager)"""
        return self.request("GET", "/salary-components", **kwargs)

    def createsalarycomponent(self, **kwargs):
        """Creer un composant de salaire (manager)"""
        return self.request("POST", "/salary-components", **kwargs)

    def deletesalarycomponent(self, **kwargs):
        """Supprimer un composant de salaire (manager)"""
        return self.request("DELETE", "/salary-components/{salaryComponent}", **kwargs)

    def showsalarycomponent(self, **kwargs):
        """Voir un composant de salaire (manager)"""
        return self.request("GET", "/salary-components/{salaryComponent}", **kwargs)

    def updatesalarycomponent(self, **kwargs):
        """Modifier un composant de salaire (manager)"""
        return self.request("PUT", "/salary-components/{salaryComponent}", **kwargs)

    def listsalarystructures(self, **kwargs):
        """Lister les structures salariales (manager)"""
        return self.request("GET", "/salary-structures", **kwargs)

    def createsalarystructure(self, **kwargs):
        """Creer une structure salariale (manager)"""
        return self.request("POST", "/salary-structures", **kwargs)

    def deletesalarystructure(self, **kwargs):
        """Supprimer une structure salariale (manager)"""
        return self.request("DELETE", "/salary-structures/{salaryStructure}", **kwargs)

    def showsalarystructure(self, **kwargs):
        """Voir une structure salariale avec ses composants (manager)"""
        return self.request("GET", "/salary-structures/{salaryStructure}", **kwargs)

    def updatesalarystructure(self, **kwargs):
        """Modifier une structure salariale (manager)"""
        return self.request("PUT", "/salary-structures/{salaryStructure}", **kwargs)

    def get_schedules(self, **kwargs):
        """Lister les horaires de l'entreprise"""
        return self.request("GET", "/schedules", **kwargs)

    def post_schedules(self, **kwargs):
        """Creer un horaire de travail"""
        return self.request("POST", "/schedules", **kwargs)

    def delete_schedules_by_schedule(self, **kwargs):
        """Supprimer un horaire non defaut"""
        return self.request("DELETE", "/schedules/{schedule}", **kwargs)

    def put_schedules_by_schedule(self, **kwargs):
        """Modifier un horaire"""
        return self.request("PUT", "/schedules/{schedule}", **kwargs)

    def post_schedules_by_schedule_assign_employees(self, **kwargs):
        """Affecter un horaire/regle entreprise a des employes"""
        return self.request("POST", "/schedules/{schedule}/assign-employees", **kwargs)

    def get_sites(self, **kwargs):
        """Lister les sites"""
        return self.request("GET", "/sites", **kwargs)

    def post_sites(self, **kwargs):
        """Creer un site"""
        return self.request("POST", "/sites", **kwargs)

    def delete_sites_by_site(self, **kwargs):
        """Supprimer un site"""
        return self.request("DELETE", "/sites/{site}", **kwargs)

    def get_sites_by_site(self, **kwargs):
        """Voir un site"""
        return self.request("GET", "/sites/{site}", **kwargs)

    def put_sites_by_site(self, **kwargs):
        """Modifier un site"""
        return self.request("PUT", "/sites/{site}", **kwargs)

    def get_smart_attendance_config(self, **kwargs):
        """Lire la configuration de mode active pour l'employe connecte"""
        return self.request("GET", "/smart-attendance/config", **kwargs)

    def put_smart_attendance_config(self, **kwargs):
        """Mettre à jour la configuration GPS (admin)"""
        return self.request("PUT", "/smart-attendance/config", **kwargs)

    def get_smart_attendance_dashboard(self, **kwargs):
        """Statistiques du jour — Smart Attendance (manager/RH)"""
        return self.request("GET", "/smart-attendance/dashboard", **kwargs)

    def post_smart_attendance_geo_events(self, **kwargs):
        """Envoyer un événement géographique (entrée/sortie de zone)"""
        return self.request("POST", "/smart-attendance/geo-events", **kwargs)

    def get_smart_attendance_preferences(self, **kwargs):
        """Lire les préférences de pointage de l'employé"""
        return self.request("GET", "/smart-attendance/preferences", **kwargs)

    def put_smart_attendance_preferences(self, **kwargs):
        """Mettre à jour les préférences de pointage"""
        return self.request("PUT", "/smart-attendance/preferences", **kwargs)

    def get_smart_attendance_sessions(self, **kwargs):
        """Lister les sessions GPS"""
        return self.request("GET", "/smart-attendance/sessions", **kwargs)

    def get_smart_attendance_sessions_by_id(self, **kwargs):
        """Détail d'une session GPS"""
        return self.request("GET", "/smart-attendance/sessions/{id}", **kwargs)

    def post_smart_attendance_sessions_by_id_validate(self, **kwargs):
        """Valider ou rejeter une session GPS (manager/RH)"""
        return self.request("POST", "/smart-attendance/sessions/{id}/validate", **kwargs)

    def listsocialcontributions(self, **kwargs):
        """Lister les regles de cotisations sociales (manager)"""
        return self.request("GET", "/social-contributions", **kwargs)

    def createsocialcontribution(self, **kwargs):
        """Creer une regle de cotisation sociale (manager)"""
        return self.request("POST", "/social-contributions", **kwargs)

    def deletesocialcontribution(self, **kwargs):
        """Supprimer une regle de cotisation sociale (manager)"""
        return self.request("DELETE", "/social-contributions/{socialContribution}", **kwargs)

    def updatesocialcontribution(self, **kwargs):
        """Modifier une regle de cotisation sociale (manager)"""
        return self.request("PUT", "/social-contributions/{socialContribution}", **kwargs)

    def generatecnasdzdeclaration(self, **kwargs):
        """Generer la declaration trimestrielle CNAS (Algerie) pour tous les employes actifs"""
        return self.request("POST", "/social-declarations/cnas-dz", **kwargs)

    def generatecnssmadeclaration(self, **kwargs):
        """Generer la declaration trimestrielle CNSS (Maroc) pour tous les employes actifs"""
        return self.request("POST", "/social-declarations/cnss-ma", **kwargs)

    def generatedsnfrdeclaration(self, **kwargs):
        """Generer la DSN (Declaration Sociale Nominative, France) pour un mois donne"""
        return self.request("POST", "/social-declarations/dsn-fr", **kwargs)

    def post_sso_configure(self, **kwargs):
        """Configurer le SSO de l'entreprise"""
        return self.request("POST", "/sso/configure", **kwargs)

    def delete_sso_disable(self, **kwargs):
        """Desactiver le SSO de l'entreprise"""
        return self.request("DELETE", "/sso/disable", **kwargs)

    def get_sso_oidc_by_companyid_callback(self, **kwargs):
        """Callback OpenID Connect (IdP -> SP)"""
        return self.request("GET", "/sso/oidc/{companyId}/callback", **kwargs)

    def get_sso_providers(self, **kwargs):
        """Lister les fournisseurs SSO supportes"""
        return self.request("GET", "/sso/providers", **kwargs)

    def post_sso_saml_by_companyid_callback(self, **kwargs):
        """Callback SAML 2.0 (IdP -> SP)"""
        return self.request("POST", "/sso/saml/{companyId}/callback", **kwargs)

    def get_sso_status(self, **kwargs):
        """Statut SSO de l'entreprise"""
        return self.request("GET", "/sso/status", **kwargs)

    def get_tasks(self, **kwargs):
        """Lister les taches"""
        return self.request("GET", "/tasks", **kwargs)

    def post_tasks(self, **kwargs):
        """Creer une tache"""
        return self.request("POST", "/tasks", **kwargs)

    def delete_tasks_by_task(self, **kwargs):
        """Supprimer une tache"""
        return self.request("DELETE", "/tasks/{task}", **kwargs)

    def get_tasks_by_task(self, **kwargs):
        """Voir une tache"""
        return self.request("GET", "/tasks/{task}", **kwargs)

    def patch_tasks_by_task(self, **kwargs):
        """Mettre a jour partiellement une tache"""
        return self.request("PATCH", "/tasks/{task}", **kwargs)

    def put_tasks_by_task(self, **kwargs):
        """Mettre a jour une tache"""
        return self.request("PUT", "/tasks/{task}", **kwargs)

    def post_tasks_by_task_comments(self, **kwargs):
        """Ajouter un commentaire sur une tache"""
        return self.request("POST", "/tasks/{task}/comments", **kwargs)

    def get_tasks_today(self, **kwargs):
        """Lister les taches du jour"""
        return self.request("GET", "/tasks/today", **kwargs)

    def listtaxslabs(self, **kwargs):
        """Lister le bareme fiscal (tranches d'impot) (manager)"""
        return self.request("GET", "/tax-slabs", **kwargs)

    def createtaxslab(self, **kwargs):
        """Creer une tranche d'impot (manager)"""
        return self.request("POST", "/tax-slabs", **kwargs)

    def deletetaxslab(self, **kwargs):
        """Supprimer une tranche d'impot (manager)"""
        return self.request("DELETE", "/tax-slabs/{taxSlab}", **kwargs)

    def updatetaxslab(self, **kwargs):
        """Modifier une tranche d'impot (manager)"""
        return self.request("PUT", "/tax-slabs/{taxSlab}", **kwargs)

    def post_tracking_sync_devices(self, **kwargs):
        """Synchroniser les devices Traccar"""
        return self.request("POST", "/tracking/sync-devices", **kwargs)

    def post_tracking_sync_positions(self, **kwargs):
        """Synchroniser les positions Traccar"""
        return self.request("POST", "/tracking/sync-positions", **kwargs)

    def post_tracking_sync_trips(self, **kwargs):
        """Synchroniser les trajets Traccar"""
        return self.request("POST", "/tracking/sync-trips", **kwargs)

    def get_training_courses(self, **kwargs):
        """Lister les formations"""
        return self.request("GET", "/training/courses", **kwargs)

    def post_training_courses(self, **kwargs):
        """Creer une formation"""
        return self.request("POST", "/training/courses", **kwargs)

    def get_training_courses_by_trainingcourse(self, **kwargs):
        """Voir une formation"""
        return self.request("GET", "/training/courses/{trainingCourse}", **kwargs)

    def put_training_courses_by_trainingcourse(self, **kwargs):
        """Modifier une formation"""
        return self.request("PUT", "/training/courses/{trainingCourse}", **kwargs)

    def get_training_courses_by_trainingcourse_sessions(self, **kwargs):
        """Lister les sessions d'une formation"""
        return self.request("GET", "/training/courses/{trainingCourse}/sessions", **kwargs)

    def post_training_courses_by_trainingcourse_sessions(self, **kwargs):
        """Creer une session de formation"""
        return self.request("POST", "/training/courses/{trainingCourse}/sessions", **kwargs)

    def put_training_enrollments_by_trainingenrollment(self, **kwargs):
        """Modifier une inscription"""
        return self.request("PUT", "/training/enrollments/{trainingEnrollment}", **kwargs)

    def put_training_sessions_by_trainingsession(self, **kwargs):
        """Modifier une session"""
        return self.request("PUT", "/training/sessions/{trainingSession}", **kwargs)

    def post_training_sessions_by_trainingsession_enroll(self, **kwargs):
        """Inscrire un employe"""
        return self.request("POST", "/training/sessions/{trainingSession}/enroll", **kwargs)

    def get_vehicle_alerts(self, **kwargs):
        """Liste de toutes les alertes vehicules"""
        return self.request("GET", "/vehicle-alerts", **kwargs)

    def post_vehicle_alerts_by_id_acknowledge(self, **kwargs):
        """Acquitter une alerte vehicule"""
        return self.request("POST", "/vehicle-alerts/{id}/acknowledge", **kwargs)

    def get_vehicle_maintenance(self, **kwargs):
        """Liste des maintenances vehicules"""
        return self.request("GET", "/vehicle-maintenance", **kwargs)

    def post_vehicle_maintenance(self, **kwargs):
        """Planifier une maintenance"""
        return self.request("POST", "/vehicle-maintenance", **kwargs)

    def delete_vehicle_maintenance_by_id(self, **kwargs):
        """Supprimer une maintenance"""
        return self.request("DELETE", "/vehicle-maintenance/{id}", **kwargs)

    def put_vehicle_maintenance_by_id(self, **kwargs):
        """Modifier une maintenance"""
        return self.request("PUT", "/vehicle-maintenance/{id}", **kwargs)

    def get_vehicle_trips(self, **kwargs):
        """Liste de tous les trajets"""
        return self.request("GET", "/vehicle-trips", **kwargs)

    def get_vehicle_trips_by_id(self, **kwargs):
        """Detail d'un trajet"""
        return self.request("GET", "/vehicle-trips/{id}", **kwargs)

    def get_vehicles(self, **kwargs):
        """Liste des vehicules de l'entreprise"""
        return self.request("GET", "/vehicles", **kwargs)

    def post_vehicles(self, **kwargs):
        """Creer un vehicule"""
        return self.request("POST", "/vehicles", **kwargs)

    def delete_vehicles_by_id(self, **kwargs):
        """Supprimer un vehicule"""
        return self.request("DELETE", "/vehicles/{id}", **kwargs)

    def get_vehicles_by_id(self, **kwargs):
        """Detail d'un vehicule"""
        return self.request("GET", "/vehicles/{id}", **kwargs)

    def put_vehicles_by_id(self, **kwargs):
        """Modifier un vehicule"""
        return self.request("PUT", "/vehicles/{id}", **kwargs)

    def get_vehicles_by_id_alerts(self, **kwargs):
        """Alertes d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/alerts", **kwargs)

    def post_vehicles_by_id_assign(self, **kwargs):
        """Assigner un vehicule a un employe"""
        return self.request("POST", "/vehicles/{id}/assign", **kwargs)

    def get_vehicles_by_id_assignments(self, **kwargs):
        """Historique des affectations conducteur"""
        return self.request("GET", "/vehicles/{id}/assignments", **kwargs)

    def get_vehicles_by_id_maintenance(self, **kwargs):
        """Historique maintenance d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/maintenance", **kwargs)

    def get_vehicles_by_id_position(self, **kwargs):
        """Position actuelle du vehicule (via Traccar)"""
        return self.request("GET", "/vehicles/{id}/position", **kwargs)

    def get_vehicles_by_id_trips(self, **kwargs):
        """Trajets d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/trips", **kwargs)

    def post_vehicles_by_id_unassign(self, **kwargs):
        """Desassigner un vehicule"""
        return self.request("POST", "/vehicles/{id}/unassign", **kwargs)

    def get_view_cam(self, **kwargs):
        """Viewer public par token"""
        return self.request("GET", "/view/cam", **kwargs)

    def get_webhooks(self, **kwargs):
        """Lister les webhooks de l'entreprise"""
        return self.request("GET", "/webhooks", **kwargs)

    def post_webhooks(self, **kwargs):
        """Creer un webhook"""
        return self.request("POST", "/webhooks", **kwargs)

    def delete_webhooks_by_webhook(self, **kwargs):
        """Supprimer un webhook"""
        return self.request("DELETE", "/webhooks/{webhook}", **kwargs)

    def get_webhooks_by_webhook(self, **kwargs):
        """Voir un webhook et ses dernieres livraisons"""
        return self.request("GET", "/webhooks/{webhook}", **kwargs)

    def put_webhooks_by_webhook(self, **kwargs):
        """Modifier un webhook"""
        return self.request("PUT", "/webhooks/{webhook}", **kwargs)

    def get_webhooks_by_webhook_dead_letters(self, **kwargs):
        """Lister les livraisons webhook dead-letter (retries epuises)"""
        return self.request("GET", "/webhooks/{webhook}/dead-letters", **kwargs)

    def post_webhooks_by_webhook_dead_letters_by_delivery_replay(self, **kwargs):
        """Rejouer une livraison webhook dead-letter"""
        return self.request("POST", "/webhooks/{webhook}/dead-letters/{delivery}/replay", **kwargs)

    def get_webhooks_events(self, **kwargs):
        """Lister les types d'evenements webhook disponibles"""
        return self.request("GET", "/webhooks/events", **kwargs)

    def listzktecodevices(self, **kwargs):
        """Lister les pointeuses ZKTeco de l'entreprise (manager)"""
        return self.request("GET", "/zkteco/devices", **kwargs)

    def registerzktecodevice(self, **kwargs):
        """Enregistrer une nouvelle pointeuse ZKTeco (manager)"""
        return self.request("POST", "/zkteco/devices", **kwargs)

    def deletezktecodevice(self, **kwargs):
        """Supprimer une pointeuse ZKTeco (manager)"""
        return self.request("DELETE", "/zkteco/devices/{id}", **kwargs)

    def showzktecodevice(self, **kwargs):
        """Voir une pointeuse ZKTeco avec son historique de synchronisation (manager)"""
        return self.request("GET", "/zkteco/devices/{id}", **kwargs)

    def updatezktecodevice(self, **kwargs):
        """Modifier une pointeuse ZKTeco (manager)"""
        return self.request("PUT", "/zkteco/devices/{id}", **kwargs)

    def listzktecosynclogs(self, **kwargs):
        """Lister l'historique de synchronisation d'une pointeuse (manager)"""
        return self.request("GET", "/zkteco/devices/{id}/sync-logs", **kwargs)

    def pushzktecousers(self, **kwargs):
        """Pousser la liste des employes vers la pointeuse (manager)"""
        return self.request("POST", "/zkteco/devices/{serialNumber}/push-users", **kwargs)

    def zktecoheartbeat(self, **kwargs):
        """Signal de vie envoye par la pointeuse elle-meme (pas d'authentification employe)"""
        return self.request("POST", "/zkteco/heartbeat/{serialNumber}", **kwargs)

    def zktecosyncattendance(self, **kwargs):
        """Pousser des pointages bruts depuis l'appareil vers le serveur (appele par l'appareil)"""
        return self.request("POST", "/zkteco/sync-attendance/{serialNumber}", **kwargs)
