# Generated by dev-hub/tools/generate-openapi-sdk.mjs from api/openapi.yaml.
# Do not edit manually.

import json
from urllib import error, parse, request as urllib_request


open_api_version = "4.1.81-2026-04-28"


class LeopardoApiError(Exception):
    def __init__(self, message, *, status, body):
        super().__init__(message)
        self.status = status
        self.body = body


class LeopardoClient:
    def __init__(self, *, base_url, token=None, timeout=30):
        if not base_url:
            raise ValueError("base_url is required")

        self.base_url = base_url.rstrip("/")
        self.token = token
        self.timeout = timeout

    def _build_path(self, path_template, path_params=None):
        path_params = path_params or {}
        rendered = path_template

        for key, value in path_params.items():
            rendered = rendered.replace("{" + key + "}", parse.quote(str(value), safe=""))

        if "{" in rendered or "}" in rendered:
            raise ValueError("Missing path parameter in " + path_template)

        return rendered

    def _build_url(self, path_template, *, path_params=None, query=None):
        url = self.base_url + self._build_path(path_template, path_params)
        clean_query = {}

        for key, value in (query or {}).items():
            if value is None:
                continue
            clean_query[key] = value

        if clean_query:
            url += "?" + parse.urlencode(clean_query, doseq=True)

        return url

    def request(self, method, path_template, *, path_params=None, query=None, body=None, headers=None):
        request_headers = {
            "Accept": "application/json",
            **(headers or {}),
        }

        if self.token:
            request_headers["Authorization"] = "Bearer " + self.token

        data = None
        if body is not None:
            request_headers.setdefault("Content-Type", "application/json")
            data = json.dumps(body).encode("utf-8")

        req = urllib_request.Request(
            self._build_url(path_template, path_params=path_params, query=query),
            data=data,
            headers=request_headers,
            method=method,
        )

        try:
            with urllib_request.urlopen(req, timeout=self.timeout) as response:
                raw = response.read()
                content_type = response.headers.get("content-type", "")
                if "application/json" in content_type:
                    return json.loads(raw.decode("utf-8")) if raw else None
                return raw.decode("utf-8")
        except error.HTTPError as exc:
            raw = exc.read()
            body_text = raw.decode("utf-8") if raw else ""
            try:
                parsed_body = json.loads(body_text) if body_text else None
            except json.JSONDecodeError:
                parsed_body = body_text

            raise LeopardoApiError(
                "Leopardo API request failed with status " + str(exc.code),
                status=exc.code,
                body=parsed_body,
            ) from exc

    def get_ai_analytics_costs(self, **kwargs):
        """Couts IA par periode"""
        return self.request("GET", "/ai/analytics/costs", **kwargs)

    def get_ai_analytics_errors(self, **kwargs):
        """Erreurs IA recentes"""
        return self.request("GET", "/ai/analytics/errors", **kwargs)

    def get_ai_analytics_tools(self, **kwargs):
        """Usage des outils IA"""
        return self.request("GET", "/ai/analytics/tools", **kwargs)

    def get_ai_analytics_usage(self, **kwargs):
        """Metriques d'usage IA"""
        return self.request("GET", "/ai/analytics/usage", **kwargs)

    def post_ai_chat(self, **kwargs):
        """Envoyer un message au chatbot IA"""
        return self.request("POST", "/ai/chat", **kwargs)

    def delete_ai_chat_by_conversationid(self, **kwargs):
        """Supprimer une conversation IA"""
        return self.request("DELETE", "/ai/chat/{conversationId}", **kwargs)

    def get_ai_chat_history(self, **kwargs):
        """Historique des conversations IA"""
        return self.request("GET", "/ai/chat/history", **kwargs)

    def get_ai_tools(self, **kwargs):
        """Liste des outils IA disponibles"""
        return self.request("GET", "/ai/tools", **kwargs)

    def get_attendance(self, **kwargs):
        """Historique de pointage"""
        return self.request("GET", "/attendance", **kwargs)

    def put_attendance_by_attendancelog(self, **kwargs):
        """Modifier directement un pointage"""
        return self.request("PUT", "/attendance/{attendanceLog}", **kwargs)

    def post_attendance_check_in(self, **kwargs):
        """Check-in"""
        return self.request("POST", "/attendance/check-in", **kwargs)

    def post_attendance_check_out(self, **kwargs):
        """Check-out"""
        return self.request("POST", "/attendance/check-out", **kwargs)

    def post_attendance_corrections(self, **kwargs):
        """Demander une correction de pointage"""
        return self.request("POST", "/attendance/corrections", **kwargs)

    def get_attendance_today(self, **kwargs):
        """Etat du jour"""
        return self.request("GET", "/attendance/today", **kwargs)

    def get_auth_biometric_enrollment(self, **kwargs):
        """Derniere demande biometrie de l'utilisateur courant"""
        return self.request("GET", "/auth/biometric-enrollment", **kwargs)

    def post_auth_biometric_enrollment(self, **kwargs):
        """Soumettre une demande biometrie"""
        return self.request("POST", "/auth/biometric-enrollment", **kwargs)

    def post_auth_change_password(self, **kwargs):
        """Changer le mot de passe"""
        return self.request("POST", "/auth/change-password", **kwargs)

    def post_auth_login(self, **kwargs):
        """Connexion employee"""
        return self.request("POST", "/auth/login", **kwargs)

    def post_auth_logout(self, **kwargs):
        """Deconnexion employee"""
        return self.request("POST", "/auth/logout", **kwargs)

    def get_auth_me(self, **kwargs):
        """Profil authentifie"""
        return self.request("GET", "/auth/me", **kwargs)

    def patch_auth_profile(self, **kwargs):
        """Mettre a jour le profil courant"""
        return self.request("PATCH", "/auth/profile", **kwargs)

    def get_biometric_enrollment_requests(self, **kwargs):
        """Lister les demandes biometrie de la company"""
        return self.request("GET", "/biometric-enrollment-requests", **kwargs)

    def post_biometric_enrollment_requests_by_id_approve(self, **kwargs):
        """Approuver une demande biometrie"""
        return self.request("POST", "/biometric-enrollment-requests/{id}/approve", **kwargs)

    def post_biometric_enrollment_requests_by_id_reject(self, **kwargs):
        """Rejeter une demande biometrie"""
        return self.request("POST", "/biometric-enrollment-requests/{id}/reject", **kwargs)

    def get_cameras(self, **kwargs):
        """Lister les cameras"""
        return self.request("GET", "/cameras", **kwargs)

    def post_cameras(self, **kwargs):
        """Creer une camera"""
        return self.request("POST", "/cameras", **kwargs)

    def delete_cameras_by_camera(self, **kwargs):
        """Desactiver une camera"""
        return self.request("DELETE", "/cameras/{camera}", **kwargs)

    def get_cameras_by_camera(self, **kwargs):
        """Voir une camera"""
        return self.request("GET", "/cameras/{camera}", **kwargs)

    def patch_cameras_by_camera(self, **kwargs):
        """Patch camera"""
        return self.request("PATCH", "/cameras/{camera}", **kwargs)

    def put_cameras_by_camera(self, **kwargs):
        """Mettre a jour une camera"""
        return self.request("PUT", "/cameras/{camera}", **kwargs)

    def get_cameras_by_camera_access_logs(self, **kwargs):
        """Lister les logs d'acces camera"""
        return self.request("GET", "/cameras/{camera}/access-logs", **kwargs)

    def get_cameras_by_camera_access_tokens(self, **kwargs):
        """Lister les tokens de partage"""
        return self.request("GET", "/cameras/{camera}/access-tokens", **kwargs)

    def post_cameras_by_camera_access_tokens(self, **kwargs):
        """Creer un token de partage"""
        return self.request("POST", "/cameras/{camera}/access-tokens", **kwargs)

    def delete_cameras_by_camera_access_tokens_by_token(self, **kwargs):
        """Revoquer un token de partage"""
        return self.request("DELETE", "/cameras/{camera}/access-tokens/{token}", **kwargs)

    def get_cameras_by_camera_permissions(self, **kwargs):
        """Lister les permissions internes"""
        return self.request("GET", "/cameras/{camera}/permissions", **kwargs)

    def post_cameras_by_camera_permissions(self, **kwargs):
        """Creer ou remplacer une permission interne"""
        return self.request("POST", "/cameras/{camera}/permissions", **kwargs)

    def delete_cameras_by_camera_permissions_by_permission(self, **kwargs):
        """Supprimer une permission interne"""
        return self.request("DELETE", "/cameras/{camera}/permissions/{permission}", **kwargs)

    def get_cameras_by_camera_stream_token(self, **kwargs):
        """Regenerer un stream token client"""
        return self.request("GET", "/cameras/{camera}/stream-token", **kwargs)

    def post_cameras_test_rtsp(self, **kwargs):
        """Tester une URL RTSP"""
        return self.request("POST", "/cameras/test-rtsp", **kwargs)

    def post_client_events(self, **kwargs):
        """Persister un evenement UX client tenant-scope"""
        return self.request("POST", "/client-events", **kwargs)

    def get_communication_analytics(self, **kwargs):
        """Analytics communication tenant"""
        return self.request("GET", "/communication/analytics", **kwargs)

    def get_employees(self, **kwargs):
        """Lister les employes"""
        return self.request("GET", "/employees", **kwargs)

    def post_employees(self, **kwargs):
        """Creer un employe"""
        return self.request("POST", "/employees", **kwargs)

    def get_employees_by_employee(self, **kwargs):
        """Voir un employe"""
        return self.request("GET", "/employees/{employee}", **kwargs)

    def patch_employees_by_employee(self, **kwargs):
        """Patch employe"""
        return self.request("PATCH", "/employees/{employee}", **kwargs)

    def put_employees_by_employee(self, **kwargs):
        """Mettre a jour un employe"""
        return self.request("PUT", "/employees/{employee}", **kwargs)

    def post_employees_by_employee_archive(self, **kwargs):
        """Archiver un employe"""
        return self.request("POST", "/employees/{employee}/archive", **kwargs)

    def get_employees_by_employee_daily_summary(self, **kwargs):
        """Resume journalier d'un employe"""
        return self.request("GET", "/employees/{employee}/daily-summary", **kwargs)

    def get_employees_by_employee_quick_estimate(self, **kwargs):
        """Estimation sur periode"""
        return self.request("GET", "/employees/{employee}/quick-estimate", **kwargs)

    def get_employees_by_employee_receipt(self, **kwargs):
        """Telecharger le PDF d'estimation"""
        return self.request("GET", "/employees/{employee}/receipt", **kwargs)

    def get_evaluations(self, **kwargs):
        """Lister les evaluations"""
        return self.request("GET", "/evaluations", **kwargs)

    def post_evaluations(self, **kwargs):
        """Creer une evaluation"""
        return self.request("POST", "/evaluations", **kwargs)

    def delete_evaluations_by_evaluation(self, **kwargs):
        """Supprimer une evaluation"""
        return self.request("DELETE", "/evaluations/{evaluation}", **kwargs)

    def get_evaluations_by_evaluation(self, **kwargs):
        """Voir une evaluation"""
        return self.request("GET", "/evaluations/{evaluation}", **kwargs)

    def patch_evaluations_by_evaluation(self, **kwargs):
        """Mettre a jour partiellement une evaluation"""
        return self.request("PATCH", "/evaluations/{evaluation}", **kwargs)

    def put_evaluations_by_evaluation(self, **kwargs):
        """Mettre a jour une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}", **kwargs)

    def put_evaluations_by_evaluation_acknowledge(self, **kwargs):
        """Accuser reception d'une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}/acknowledge", **kwargs)

    def put_evaluations_by_evaluation_submit(self, **kwargs):
        """Soumettre une evaluation"""
        return self.request("PUT", "/evaluations/{evaluation}/submit", **kwargs)

    def get_fleet_live_map(self, **kwargs):
        """Carte temps reel des vehicules"""
        return self.request("GET", "/fleet/live-map", **kwargs)

    def get_fleet_overview(self, **kwargs):
        """Vue d'ensemble de la flotte"""
        return self.request("GET", "/fleet/overview", **kwargs)

    def get_fleet_reports_fuel(self, **kwargs):
        """Rapport consommation carburant"""
        return self.request("GET", "/fleet/reports/fuel", **kwargs)

    def get_fleet_reports_maintenance_due(self, **kwargs):
        """Vehicules necessitant une maintenance"""
        return self.request("GET", "/fleet/reports/maintenance-due", **kwargs)

    def get_fleet_reports_mileage(self, **kwargs):
        """Rapport kilometrage"""
        return self.request("GET", "/fleet/reports/mileage", **kwargs)

    def get_health(self, **kwargs):
        """Healthcheck live + ready"""
        return self.request("GET", "/health", **kwargs)

    def get_internal_camera_token_verify(self, **kwargs):
        """Verification interne MediaMTX"""
        return self.request("GET", "/internal/camera-token/verify", **kwargs)

    def get_invitations(self, **kwargs):
        """Lister les invitations de l'entreprise"""
        return self.request("GET", "/invitations", **kwargs)

    def post_invitations_by_invitation_resend(self, **kwargs):
        """Renvoyer une invitation"""
        return self.request("POST", "/invitations/{invitation}/resend", **kwargs)

    def post_kiosks(self, **kwargs):
        """Enregistrer un kiosk"""
        return self.request("POST", "/kiosks", **kwargs)

    def post_kiosks_by_devicecode_punch(self, **kwargs):
        """Pointage via kiosk"""
        return self.request("POST", "/kiosks/{deviceCode}/punch", **kwargs)

    def get_kiosks_by_devicecode_roster(self, **kwargs):
        """Roster biometrie d'un kiosk"""
        return self.request("GET", "/kiosks/{deviceCode}/roster", **kwargs)

    def post_kiosks_by_devicecode_sync(self, **kwargs):
        """Synchroniser des evenements offline"""
        return self.request("POST", "/kiosks/{deviceCode}/sync", **kwargs)

    def get_launch_readiness(self, **kwargs):
        """Lire le score de readiness lancement du tenant"""
        return self.request("GET", "/launch-readiness", **kwargs)

    def get_me_daily_summary(self, **kwargs):
        """Resume journalier utilisateur courant"""
        return self.request("GET", "/me/daily-summary", **kwargs)

    def get_me_monthly_summary(self, **kwargs):
        """Resume mensuel utilisateur courant"""
        return self.request("GET", "/me/monthly-summary", **kwargs)

    def get_me_quick_estimate(self, **kwargs):
        """Estimation utilisateur courant"""
        return self.request("GET", "/me/quick-estimate", **kwargs)

    def get_notification_preferences(self, **kwargs):
        """Lire les preferences de notification de l'utilisateur courant"""
        return self.request("GET", "/notification-preferences", **kwargs)

    def patch_notification_preferences(self, **kwargs):
        """Mettre a jour les preferences de notification de l'utilisateur courant"""
        return self.request("PATCH", "/notification-preferences", **kwargs)

    def get_notifications(self, **kwargs):
        """Lister les notifications de l'utilisateur courant"""
        return self.request("GET", "/notifications", **kwargs)

    def delete_notifications_by_notification(self, **kwargs):
        """Supprimer une notification"""
        return self.request("DELETE", "/notifications/{notification}", **kwargs)

    def put_notifications_by_notification_read(self, **kwargs):
        """Marquer une notification comme lue"""
        return self.request("PUT", "/notifications/{notification}/read", **kwargs)

    def put_notifications_read_all(self, **kwargs):
        """Marquer toutes les notifications comme lues"""
        return self.request("PUT", "/notifications/read-all", **kwargs)

    def get_pay_slips(self, **kwargs):
        """Lister les bulletins du tenant (manager)"""
        return self.request("GET", "/pay-slips", **kwargs)

    def post_platform_auth_login(self, **kwargs):
        """Connexion super-admin"""
        return self.request("POST", "/platform/auth/login", **kwargs)

    def post_platform_auth_logout(self, **kwargs):
        """Deconnexion super-admin"""
        return self.request("POST", "/platform/auth/logout", **kwargs)

    def get_platform_auth_me(self, **kwargs):
        """Super-admin courant"""
        return self.request("GET", "/platform/auth/me", **kwargs)

    def get_platform_companies(self, **kwargs):
        """Lister les societes"""
        return self.request("GET", "/platform/companies", **kwargs)

    def post_platform_companies(self, **kwargs):
        """Creer une societe shared"""
        return self.request("POST", "/platform/companies", **kwargs)

    def get_platform_companies_by_company_features(self, **kwargs):
        """Lire les feature flags d'une societe"""
        return self.request("GET", "/platform/companies/{company}/features", **kwargs)

    def patch_platform_companies_by_company_features(self, **kwargs):
        """Mettre a jour les feature flags d'une societe"""
        return self.request("PATCH", "/platform/companies/{company}/features", **kwargs)

    def get_platform_companies_by_company_health(self, **kwargs):
        """Health detaille d'une societe"""
        return self.request("GET", "/platform/companies/{company}/health", **kwargs)

    def get_platform_companies_by_company_subscription(self, **kwargs):
        """Lire l'abonnement plateforme d'une societe"""
        return self.request("GET", "/platform/companies/{company}/subscription", **kwargs)

    def patch_platform_companies_by_company_subscription(self, **kwargs):
        """Mettre a jour l'abonnement plateforme d'une societe"""
        return self.request("PATCH", "/platform/companies/{company}/subscription", **kwargs)

    def get_platform_companies_health(self, **kwargs):
        """Vue portefeuille health des societes"""
        return self.request("GET", "/platform/companies/health", **kwargs)

    def get_platform_company_requests(self, **kwargs):
        """Lister les demandes de creation de societe"""
        return self.request("GET", "/platform/company-requests", **kwargs)

    def get_platform_company_requests_by_id(self, **kwargs):
        """Lire une demande de creation de societe"""
        return self.request("GET", "/platform/company-requests/{id}", **kwargs)

    def patch_platform_company_requests_by_id(self, **kwargs):
        """Approuver ou rejeter une demande de creation de societe"""
        return self.request("PATCH", "/platform/company-requests/{id}", **kwargs)

    def get_platform_metrics_overview(self, **kwargs):
        """Agregats business du cockpit super-admin"""
        return self.request("GET", "/platform/metrics/overview", **kwargs)

    def get_platform_plans(self, **kwargs):
        """Lister le catalogue des plans SaaS"""
        return self.request("GET", "/platform/plans", **kwargs)

    def patch_privacy_biometric_consent(self, **kwargs):
        """Enregistrer ou retirer le consentement biometrique"""
        return self.request("PATCH", "/privacy/biometric-consent", **kwargs)

    def post_privacy_deletion_request(self, **kwargs):
        """Creer une demande de suppression non destructive"""
        return self.request("POST", "/privacy/deletion-request", **kwargs)

    def get_privacy_export(self, **kwargs):
        """Exporter les donnees personnelles de l'employe authentifie"""
        return self.request("GET", "/privacy/export", **kwargs)

    def get_projects(self, **kwargs):
        """Lister les projets"""
        return self.request("GET", "/projects", **kwargs)

    def post_projects(self, **kwargs):
        """Creer un projet"""
        return self.request("POST", "/projects", **kwargs)

    def delete_projects_by_project(self, **kwargs):
        """Supprimer un projet"""
        return self.request("DELETE", "/projects/{project}", **kwargs)

    def get_projects_by_project(self, **kwargs):
        """Voir un projet"""
        return self.request("GET", "/projects/{project}", **kwargs)

    def patch_projects_by_project(self, **kwargs):
        """Mettre a jour partiellement un projet"""
        return self.request("PATCH", "/projects/{project}", **kwargs)

    def put_projects_by_project(self, **kwargs):
        """Mettre a jour un projet"""
        return self.request("PUT", "/projects/{project}", **kwargs)

    def get_tasks(self, **kwargs):
        """Lister les taches"""
        return self.request("GET", "/tasks", **kwargs)

    def post_tasks(self, **kwargs):
        """Creer une tache"""
        return self.request("POST", "/tasks", **kwargs)

    def delete_tasks_by_task(self, **kwargs):
        """Supprimer une tache"""
        return self.request("DELETE", "/tasks/{task}", **kwargs)

    def get_tasks_by_task(self, **kwargs):
        """Voir une tache"""
        return self.request("GET", "/tasks/{task}", **kwargs)

    def patch_tasks_by_task(self, **kwargs):
        """Mettre a jour partiellement une tache"""
        return self.request("PATCH", "/tasks/{task}", **kwargs)

    def put_tasks_by_task(self, **kwargs):
        """Mettre a jour une tache"""
        return self.request("PUT", "/tasks/{task}", **kwargs)

    def post_tasks_by_task_comments(self, **kwargs):
        """Ajouter un commentaire sur une tache"""
        return self.request("POST", "/tasks/{task}/comments", **kwargs)

    def post_tracking_sync_devices(self, **kwargs):
        """Synchroniser les devices Traccar"""
        return self.request("POST", "/tracking/sync-devices", **kwargs)

    def post_tracking_sync_positions(self, **kwargs):
        """Synchroniser les positions Traccar"""
        return self.request("POST", "/tracking/sync-positions", **kwargs)

    def post_tracking_sync_trips(self, **kwargs):
        """Synchroniser les trajets Traccar"""
        return self.request("POST", "/tracking/sync-trips", **kwargs)

    def get_vehicle_alerts(self, **kwargs):
        """Liste de toutes les alertes vehicules"""
        return self.request("GET", "/vehicle-alerts", **kwargs)

    def post_vehicle_alerts_by_id_acknowledge(self, **kwargs):
        """Acquitter une alerte vehicule"""
        return self.request("POST", "/vehicle-alerts/{id}/acknowledge", **kwargs)

    def get_vehicle_maintenance(self, **kwargs):
        """Liste des maintenances vehicules"""
        return self.request("GET", "/vehicle-maintenance", **kwargs)

    def post_vehicle_maintenance(self, **kwargs):
        """Planifier une maintenance"""
        return self.request("POST", "/vehicle-maintenance", **kwargs)

    def delete_vehicle_maintenance_by_id(self, **kwargs):
        """Supprimer une maintenance"""
        return self.request("DELETE", "/vehicle-maintenance/{id}", **kwargs)

    def put_vehicle_maintenance_by_id(self, **kwargs):
        """Modifier une maintenance"""
        return self.request("PUT", "/vehicle-maintenance/{id}", **kwargs)

    def get_vehicle_trips(self, **kwargs):
        """Liste de tous les trajets"""
        return self.request("GET", "/vehicle-trips", **kwargs)

    def get_vehicle_trips_by_id(self, **kwargs):
        """Detail d'un trajet"""
        return self.request("GET", "/vehicle-trips/{id}", **kwargs)

    def get_vehicles(self, **kwargs):
        """Liste des vehicules de l'entreprise"""
        return self.request("GET", "/vehicles", **kwargs)

    def post_vehicles(self, **kwargs):
        """Creer un vehicule"""
        return self.request("POST", "/vehicles", **kwargs)

    def delete_vehicles_by_id(self, **kwargs):
        """Supprimer un vehicule"""
        return self.request("DELETE", "/vehicles/{id}", **kwargs)

    def get_vehicles_by_id(self, **kwargs):
        """Detail d'un vehicule"""
        return self.request("GET", "/vehicles/{id}", **kwargs)

    def put_vehicles_by_id(self, **kwargs):
        """Modifier un vehicule"""
        return self.request("PUT", "/vehicles/{id}", **kwargs)

    def get_vehicles_by_id_alerts(self, **kwargs):
        """Alertes d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/alerts", **kwargs)

    def post_vehicles_by_id_assign(self, **kwargs):
        """Assigner un vehicule a un employe"""
        return self.request("POST", "/vehicles/{id}/assign", **kwargs)

    def get_vehicles_by_id_assignments(self, **kwargs):
        """Historique des affectations conducteur"""
        return self.request("GET", "/vehicles/{id}/assignments", **kwargs)

    def get_vehicles_by_id_maintenance(self, **kwargs):
        """Historique maintenance d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/maintenance", **kwargs)

    def get_vehicles_by_id_position(self, **kwargs):
        """Position actuelle du vehicule (via Traccar)"""
        return self.request("GET", "/vehicles/{id}/position", **kwargs)

    def get_vehicles_by_id_trips(self, **kwargs):
        """Trajets d'un vehicule"""
        return self.request("GET", "/vehicles/{id}/trips", **kwargs)

    def post_vehicles_by_id_unassign(self, **kwargs):
        """Desassigner un vehicule"""
        return self.request("POST", "/vehicles/{id}/unassign", **kwargs)

    def get_view_cam(self, **kwargs):
        """Viewer public par token"""
        return self.request("GET", "/view/cam", **kwargs)
