version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      php-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      flutter-dependencies:
        patterns:
          - "*"
