<?php

// #7493/#7494 — personalized checklist titles generated by the setup
// interview + /setup-interview API messages (i18n guard PA2-I18N-007, #5432).
return [
    'step_company_info' => 'Fill in your company information',
    'step_first_employee' => 'Add your first employee',
    'step_configure_schedules' => 'Set up your schedules',
    'step_first_attendance' => 'Record the first clock-in',
    'step_configure_payroll' => 'Set up payroll',
    'step_install_kiosk' => 'Install a kiosk',
    'step_activate_geofence' => 'Enable geofencing',
    'step_customize_showcase' => 'Customize your showcase website',
    'step_publish_showcase' => 'Publish your showcase website',
    'interview_invalid_answer' => 'Invalid answer: :question',
];
