<?php

return [
    // #7630 (PA2-I18N-007) — titles of the steps generated by the setup
    // interview (#7494): catalog instead of hardcoded French.
    'step_first_employee_title' => 'Add your first employee',
    'step_activate_geofence_title' => 'Enable geofencing',

    // Setup interview (#7493) — answer outside the allowlist (422).
    'interview_invalid_answer' => 'Invalid answer: :question',
];
