// Generated by dev-hub/tools/generate-openapi-sdk.mjs from api/openapi.yaml.
// Do not edit manually.

export class LeopardoApiError extends Error {
  constructor(message, { status, response, body }) {
    super(message);
    this.name = "LeopardoApiError";
    this.status = status;
    this.response = response;
    this.body = body;
  }
}

export function createLeopardoClient({ baseUrl, token, fetchImpl = globalThis.fetch } = {}) {
  if (!baseUrl) {
    throw new TypeError("baseUrl is required");
  }

  if (typeof fetchImpl !== "function") {
    throw new TypeError("fetchImpl is required when global fetch is unavailable");
  }

  const normalizedBaseUrl = baseUrl.replace(/\/+$/, "");

  function buildPath(pathTemplate, pathParams = {}) {
    return pathTemplate.replace(/\{([^}]+)\}/g, (_, name) => {
      if (pathParams[name] === undefined || pathParams[name] === null) {
        throw new TypeError(`Missing path parameter: ${name}`);
      }

      return encodeURIComponent(String(pathParams[name]));
    });
  }

  function buildUrl(pathTemplate, { pathParams, query } = {}) {
    const url = new URL(`${normalizedBaseUrl}${buildPath(pathTemplate, pathParams)}`);

    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }

      if (Array.isArray(value)) {
        for (const item of value) {
          url.searchParams.append(key, String(item));
        }
      } else {
        url.searchParams.set(key, String(value));
      }
    }

    return url;
  }

  async function request(method, pathTemplate, { pathParams, query, body, headers = {} } = {}) {
    const requestHeaders = {
      Accept: "application/json",
      ...headers,
    };

    if (token) {
      requestHeaders.Authorization = `Bearer ${token}`;
    }

    const init = {
      method,
      headers: requestHeaders,
    };

    if (body !== undefined) {
      requestHeaders["Content-Type"] = requestHeaders["Content-Type"] ?? "application/json";
      init.body = requestHeaders["Content-Type"].includes("application/json") ? JSON.stringify(body) : body;
    }

    const response = await fetchImpl(buildUrl(pathTemplate, { pathParams, query }), init);
    const contentType = response.headers.get("content-type") ?? "";
    const payload = contentType.includes("application/json") ? await response.json() : await response.text();

    if (!response.ok) {
      throw new LeopardoApiError(`Leopardo API request failed with status ${response.status}`, {
        status: response.status,
        response,
        body: payload,
      });
    }

    return payload;
  }

  return {
    request,

    /** Lister les absences */
    getAbsences(options = {}) {
      return request("GET", "/absences", options);
    },

    /** Demander une absence */
    postAbsences(options = {}) {
      return request("POST", "/absences", options);
    },

    /** Annuler une absence (employe proprietaire) */
    deleteAbsencesByAbsence(options = {}) {
      return request("DELETE", "/absences/{absence}", options);
    },

    /** Voir une absence */
    getAbsencesByAbsence(options = {}) {
      return request("GET", "/absences/{absence}", options);
    },

    /** Approuver une absence (manager) */
    putAbsencesByAbsenceApprove(options = {}) {
      return request("PUT", "/absences/{absence}/approve", options);
    },

    /** Rejeter une absence (manager) */
    putAbsencesByAbsenceReject(options = {}) {
      return request("PUT", "/absences/{absence}/reject", options);
    },

    /** Conversations IA cross-tenant (super-admin) */
    getAdminAiConversations(options = {}) {
      return request("GET", "/admin/ai/conversations", options);
    },

    /** Messages d'une conversation IA (super-admin) */
    getAdminAiConversationsByConversationMessages(options = {}) {
      return request("GET", "/admin/ai/conversations/{conversation}/messages", options);
    },

    /** Activites recentes plateforme (cockpit super-admin) */
    getAdminDashboardActivities(options = {}) {
      return request("GET", "/admin/dashboard/activities", options);
    },

    /** Alertes systeme du cockpit super-admin */
    getAdminDashboardAlerts(options = {}) {
      return request("GET", "/admin/dashboard/alerts", options);
    },

    /** Masquer une alerte du cockpit (persiste le dismiss) */
    postAdminDashboardAlertsByAlertKeyDismiss(options = {}) {
      return request("POST", "/admin/dashboard/alerts/{alertKey}/dismiss", options);
    },

    /** Statistiques globales du cockpit super-admin */
    getAdminDashboardStats(options = {}) {
      return request("GET", "/admin/dashboard/stats", options);
    },

    /** Lister les nœuds Edge de tous les tenants (super-admin) */
    getAdminEdgeNodes(options = {}) {
      return request("GET", "/admin/edge-nodes", options);
    },

    /** Révoquer un nœud Edge et sa licence (super-admin) */
    postAdminEdgeNodesByNodeIdRevoke(options = {}) {
      return request("POST", "/admin/edge-nodes/{nodeId}/revoke", options);
    },

    /** Forcer la synchronisation d'un nœud Edge (super-admin) */
    postAdminEdgeNodesByNodeIdSync(options = {}) {
      return request("POST", "/admin/edge-nodes/{nodeId}/sync", options);
    },

    /** Alertes flotte cross-tenant (super-admin) */
    getAdminFleetAlerts(options = {}) {
      return request("GET", "/admin/fleet/alerts", options);
    },

    /** Rapports RH cross-tenant (super-admin) */
    getAdminHrReports(options = {}) {
      return request("GET", "/admin/hr-reports", options);
    },

    /** Config OAuth marketing (super-admin) */
    getAdminPlatformMarketingOauthConfig(options = {}) {
      return request("GET", "/admin/platform/marketing/oauth-config", options);
    },

    /** Enregistrer la config OAuth d'un provider marketing */
    putAdminPlatformMarketingOauthConfig(options = {}) {
      return request("PUT", "/admin/platform/marketing/oauth-config", options);
    },

    /** Lister les jours fériés d'un pays/année (super-admin : national + entreprise) */
    listPublicHolidaysAdmin(options = {}) {
      return request("GET", "/admin/public-holidays", options);
    },

    /** Créer un jour férié national (super-admin) */
    storePublicHolidayAdmin(options = {}) {
      return request("POST", "/admin/public-holidays", options);
    },

    /** Supprimer un jour férié (super-admin) */
    destroyPublicHolidayAdmin(options = {}) {
      return request("DELETE", "/admin/public-holidays/{publicHoliday}", options);
    },

    /** Modifier un jour férié (super-admin) */
    updatePublicHolidayAdmin(options = {}) {
      return request("PUT", "/admin/public-holidays/{publicHoliday}", options);
    },

    /** Couts IA par periode */
    getAiAnalyticsCosts(options = {}) {
      return request("GET", "/ai/analytics/costs", options);
    },

    /** Erreurs IA recentes */
    getAiAnalyticsErrors(options = {}) {
      return request("GET", "/ai/analytics/errors", options);
    },

    /** Usage des outils IA */
    getAiAnalyticsTools(options = {}) {
      return request("GET", "/ai/analytics/tools", options);
    },

    /** Metriques d'usage IA */
    getAiAnalyticsUsage(options = {}) {
      return request("GET", "/ai/analytics/usage", options);
    },

    /** Envoyer un message au chatbot IA */
    postAiChat(options = {}) {
      return request("POST", "/ai/chat", options);
    },

    /** Supprimer une conversation IA */
    deleteAiChatByConversationId(options = {}) {
      return request("DELETE", "/ai/chat/{conversationId}", options);
    },

    /** Historique des conversations IA */
    getAiChatHistory(options = {}) {
      return request("GET", "/ai/chat/history", options);
    },

    /** Liste des outils IA disponibles */
    getAiTools(options = {}) {
      return request("GET", "/ai/tools", options);
    },

    /** Lister les workflows d'approbation */
    getApprovalWorkflows(options = {}) {
      return request("GET", "/approval-workflows", options);
    },

    /** Creer un workflow */
    postApprovalWorkflows(options = {}) {
      return request("POST", "/approval-workflows", options);
    },

    /** Supprimer un workflow */
    deleteApprovalWorkflowsByApprovalWorkflow(options = {}) {
      return request("DELETE", "/approval-workflows/{approvalWorkflow}", options);
    },

    /** Modifier un workflow */
    putApprovalWorkflowsByApprovalWorkflow(options = {}) {
      return request("PUT", "/approval-workflows/{approvalWorkflow}", options);
    },

    /** Approuver une demande */
    postApprovalsByApprovalRequestApprove(options = {}) {
      return request("POST", "/approvals/{approvalRequest}/approve", options);
    },

    /** Rejeter une demande */
    postApprovalsByApprovalRequestReject(options = {}) {
      return request("POST", "/approvals/{approvalRequest}/reject", options);
    },

    /** Historique des approbations */
    getApprovalsHistory(options = {}) {
      return request("GET", "/approvals/history", options);
    },

    /** Approbations en attente */
    getApprovalsPending(options = {}) {
      return request("GET", "/approvals/pending", options);
    },

    /** Historique de pointage */
    getAttendance(options = {}) {
      return request("GET", "/attendance", options);
    },

    /** Modifier directement un pointage */
    putAttendanceByAttendanceLog(options = {}) {
      return request("PUT", "/attendance/{attendanceLog}", options);
    },

    /** Telecharger la photo de pointage d'un log */
    getAttendanceByAttendanceLogPunchPhoto(options = {}) {
      return request("GET", "/attendance/{attendanceLog}/punch-photo", options);
    },

    /** Anomalies de pointage */
    getAttendanceAnomalies(options = {}) {
      return request("GET", "/attendance/anomalies", options);
    },

    /** Check-in */
    postAttendanceCheckIn(options = {}) {
      return request("POST", "/attendance/check-in", options);
    },

    /** Check-out */
    postAttendanceCheckOut(options = {}) {
      return request("POST", "/attendance/check-out", options);
    },

    /** Lister les demandes de correction de pointage */
    getAttendanceCorrections(options = {}) {
      return request("GET", "/attendance/corrections", options);
    },

    /** Demander une correction de pointage */
    postAttendanceCorrections(options = {}) {
      return request("POST", "/attendance/corrections", options);
    },

    /** Appliquer une demande de correction de pointage */
    putAttendanceCorrectionsByCorrectionApprove(options = {}) {
      return request("PUT", "/attendance/corrections/{correction}/approve", options);
    },

    /** Refuser une demande de correction de pointage */
    putAttendanceCorrectionsByCorrectionReject(options = {}) {
      return request("PUT", "/attendance/corrections/{correction}/reject", options);
    },

    /** Rapport mensuel de pointage */
    getAttendanceMonthlyReport(options = {}) {
      return request("GET", "/attendance/monthly-report", options);
    },

    /** Etat du jour */
    getAttendanceToday(options = {}) {
      return request("GET", "/attendance/today", options);
    },

    /** Journal d'audit */
    getAuditLogs(options = {}) {
      return request("GET", "/audit-logs", options);
    },

    /** Voir un evenement d'audit */
    getAuditLogsByAuditLog(options = {}) {
      return request("GET", "/audit-logs/{auditLog}", options);
    },

    /** Exporter le journal d'audit en CSV */
    getAuditLogsExportCsv(options = {}) {
      return request("GET", "/audit-logs/export-csv", options);
    },

    /** Derniere demande biometrie de l'utilisateur courant */
    getAuthBiometricEnrollment(options = {}) {
      return request("GET", "/auth/biometric-enrollment", options);
    },

    /** Soumettre une demande biometrie */
    postAuthBiometricEnrollment(options = {}) {
      return request("POST", "/auth/biometric-enrollment", options);
    },

    /** Changer le mot de passe */
    postAuthChangePassword(options = {}) {
      return request("POST", "/auth/change-password", options);
    },

    /** Connexion Google OAuth */
    postAuthGoogleToken(options = {}) {
      return request("POST", "/auth/google/token", options);
    },

    /** Changer la langue */
    patchAuthLanguage(options = {}) {
      return request("PATCH", "/auth/language", options);
    },

    /** Connexion employee */
    postAuthLogin(options = {}) {
      return request("POST", "/auth/login", options);
    },

    /** Deconnexion employee */
    postAuthLogout(options = {}) {
      return request("POST", "/auth/logout", options);
    },

    /** Profil authentifie */
    getAuthMe(options = {}) {
      return request("GET", "/auth/me", options);
    },

    /** Mettre a jour le profil courant */
    patchAuthProfile(options = {}) {
      return request("PATCH", "/auth/profile", options);
    },

    /** Rafraichir le token */
    postAuthRefreshToken(options = {}) {
      return request("POST", "/auth/refresh-token", options);
    },

    /** Inscription employe */
    postAuthRegister(options = {}) {
      return request("POST", "/auth/register", options);
    },

    /** Lister les exports bancaires */
    getBankExports(options = {}) {
      return request("GET", "/bank-exports", options);
    },

    /** Generer un export bancaire */
    postBankExports(options = {}) {
      return request("POST", "/bank-exports", options);
    },

    /** Telecharger un export bancaire */
    getBankExportsByBankExportDownload(options = {}) {
      return request("GET", "/bank-exports/{bankExport}/download", options);
    },

    /** Creer une session Stripe Checkout pour souscrire/upgrader (manager) */
    createBillingCheckoutSession(options = {}) {
      return request("POST", "/billing/checkout", options);
    },

    /** Lister les factures */
    getBillingInvoices(options = {}) {
      return request("GET", "/billing/invoices", options);
    },

    /** Voir une facture */
    getBillingInvoicesById(options = {}) {
      return request("GET", "/billing/invoices/{id}", options);
    },

    /** Telecharger facture PDF */
    getBillingInvoicesByIdPdf(options = {}) {
      return request("GET", "/billing/invoices/{id}/pdf", options);
    },

    /** Creer une session Stripe Customer Portal pour gerer l'abonnement (manager) */
    createBillingPortalSession(options = {}) {
      return request("GET", "/billing/portal", options);
    },

    /** Voir l'abonnement courant */
    getBillingSubscription(options = {}) {
      return request("GET", "/billing/subscription", options);
    },

    /** Annuler l'abonnement (manager) */
    cancelSubscription(options = {}) {
      return request("POST", "/billing/subscription/cancel", options);
    },

    /** Renouveler l'abonnement (manager) */
    renewSubscription(options = {}) {
      return request("POST", "/billing/subscription/renew", options);
    },

    /** Upgrader l'abonnement (manager) */
    upgradeSubscription(options = {}) {
      return request("POST", "/billing/subscription/upgrade", options);
    },

    /** Lister les demandes biometrie de la company */
    getBiometricEnrollmentRequests(options = {}) {
      return request("GET", "/biometric-enrollment-requests", options);
    },

    /** Approuver une demande biometrie */
    postBiometricEnrollmentRequestsByIdApprove(options = {}) {
      return request("POST", "/biometric-enrollment-requests/{id}/approve", options);
    },

    /** Rejeter une demande biometrie */
    postBiometricEnrollmentRequestsByIdReject(options = {}) {
      return request("POST", "/biometric-enrollment-requests/{id}/reject", options);
    },

    /** Lister les documents */
    getCabinetDocuments(options = {}) {
      return request("GET", "/cabinet/documents", options);
    },

    /** Uploader un document */
    postCabinetDocuments(options = {}) {
      return request("POST", "/cabinet/documents", options);
    },

    /** Supprimer un document */
    deleteCabinetDocumentsByCabinetDocument(options = {}) {
      return request("DELETE", "/cabinet/documents/{cabinetDocument}", options);
    },

    /** Voir un document */
    getCabinetDocumentsByCabinetDocument(options = {}) {
      return request("GET", "/cabinet/documents/{cabinetDocument}", options);
    },

    /** Modifier un document */
    putCabinetDocumentsByCabinetDocument(options = {}) {
      return request("PUT", "/cabinet/documents/{cabinetDocument}", options);
    },

    /** Telecharger un document */
    getCabinetDocumentsByCabinetDocumentDownload(options = {}) {
      return request("GET", "/cabinet/documents/{cabinetDocument}/download", options);
    },

    /** Deplacer un document */
    postCabinetDocumentsByCabinetDocumentMove(options = {}) {
      return request("POST", "/cabinet/documents/{cabinetDocument}/move", options);
    },

    /** Lister les dossiers */
    getCabinetFolders(options = {}) {
      return request("GET", "/cabinet/folders", options);
    },

    /** Creer un dossier */
    postCabinetFolders(options = {}) {
      return request("POST", "/cabinet/folders", options);
    },

    /** Supprimer un dossier */
    deleteCabinetFoldersByCabinetFolder(options = {}) {
      return request("DELETE", "/cabinet/folders/{cabinetFolder}", options);
    },

    /** Voir un dossier */
    getCabinetFoldersByCabinetFolder(options = {}) {
      return request("GET", "/cabinet/folders/{cabinetFolder}", options);
    },

    /** Modifier un dossier */
    putCabinetFoldersByCabinetFolder(options = {}) {
      return request("PUT", "/cabinet/folders/{cabinetFolder}", options);
    },

    /** Lister les cameras */
    getCameras(options = {}) {
      return request("GET", "/cameras", options);
    },

    /** Creer une camera */
    postCameras(options = {}) {
      return request("POST", "/cameras", options);
    },

    /** Desactiver une camera */
    deleteCamerasByCamera(options = {}) {
      return request("DELETE", "/cameras/{camera}", options);
    },

    /** Voir une camera */
    getCamerasByCamera(options = {}) {
      return request("GET", "/cameras/{camera}", options);
    },

    /** Patch camera */
    patchCamerasByCamera(options = {}) {
      return request("PATCH", "/cameras/{camera}", options);
    },

    /** Mettre a jour une camera */
    putCamerasByCamera(options = {}) {
      return request("PUT", "/cameras/{camera}", options);
    },

    /** Lister les logs d'acces camera */
    getCamerasByCameraAccessLogs(options = {}) {
      return request("GET", "/cameras/{camera}/access-logs", options);
    },

    /** Lister les tokens de partage */
    getCamerasByCameraAccessTokens(options = {}) {
      return request("GET", "/cameras/{camera}/access-tokens", options);
    },

    /** Creer un token de partage */
    postCamerasByCameraAccessTokens(options = {}) {
      return request("POST", "/cameras/{camera}/access-tokens", options);
    },

    /** Revoquer un token de partage */
    deleteCamerasByCameraAccessTokensByToken(options = {}) {
      return request("DELETE", "/cameras/{camera}/access-tokens/{token}", options);
    },

    /** Lister les permissions internes */
    getCamerasByCameraPermissions(options = {}) {
      return request("GET", "/cameras/{camera}/permissions", options);
    },

    /** Creer ou remplacer une permission interne */
    postCamerasByCameraPermissions(options = {}) {
      return request("POST", "/cameras/{camera}/permissions", options);
    },

    /** Supprimer une permission interne */
    deleteCamerasByCameraPermissionsByPermission(options = {}) {
      return request("DELETE", "/cameras/{camera}/permissions/{permission}", options);
    },

    /** Regenerer un stream token client */
    getCamerasByCameraStreamToken(options = {}) {
      return request("GET", "/cameras/{camera}/stream-token", options);
    },

    /** Tester une URL RTSP */
    postCamerasTestRtsp(options = {}) {
      return request("POST", "/cameras/test-rtsp", options);
    },

    /** Persister un evenement UX client tenant-scope */
    postClientEvents(options = {}) {
      return request("POST", "/client-events", options);
    },

    /** Analytics communication tenant */
    getCommunicationAnalytics(options = {}) {
      return request("GET", "/communication/analytics", options);
    },

    /** Lire l'identite visuelle de l'entreprise courante */
    getCompanyBranding(options = {}) {
      return request("GET", "/company/branding", options);
    },

    /** Mettre a jour l'identite visuelle entreprise */
    patchCompanyBranding(options = {}) {
      return request("PATCH", "/company/branding", options);
    },

    /** Generer le QR onboarding entreprise */
    getCompanyQrOnboarding(options = {}) {
      return request("GET", "/company/qr-onboarding", options);
    },

    /** Creer un employe depuis QR */
    postCompanyQrOnboardingCreateEmployee(options = {}) {
      return request("POST", "/company/qr-onboarding/create-employee", options);
    },

    /** Lire un QR employe pour pre-remplir l'ajout manager */
    postCompanyQrOnboardingScanEmployee(options = {}) {
      return request("POST", "/company/qr-onboarding/scan-employee", options);
    },

    /** Lister les contrats */
    getContracts(options = {}) {
      return request("GET", "/contracts", options);
    },

    /** Creer un contrat */
    postContracts(options = {}) {
      return request("POST", "/contracts", options);
    },

    /** Voir un contrat */
    getContractsByContract(options = {}) {
      return request("GET", "/contracts/{contract}", options);
    },

    /** Modifier un contrat */
    putContractsByContract(options = {}) {
      return request("PUT", "/contracts/{contract}", options);
    },

    /** Activer un contrat draft */
    postContractsByContractActivate(options = {}) {
      return request("POST", "/contracts/{contract}/activate", options);
    },

    /** Lister les avenants */
    getContractsByContractAmendments(options = {}) {
      return request("GET", "/contracts/{contract}/amendments", options);
    },

    /** Creer un avenant */
    postContractsByContractAmendments(options = {}) {
      return request("POST", "/contracts/{contract}/amendments", options);
    },

    /** Donnees PDF du contrat */
    getContractsByContractGeneratePdf(options = {}) {
      return request("GET", "/contracts/{contract}/generate-pdf", options);
    },

    /** Renouveler un contrat */
    postContractsByContractRenew(options = {}) {
      return request("POST", "/contracts/{contract}/renew", options);
    },

    /** Suspendre un contrat actif */
    postContractsByContractSuspend(options = {}) {
      return request("POST", "/contracts/{contract}/suspend", options);
    },

    /** Resilier un contrat */
    postContractsByContractTerminate(options = {}) {
      return request("POST", "/contracts/{contract}/terminate", options);
    },

    /** Contrats expirant bientot */
    getContractsExpiring(options = {}) {
      return request("GET", "/contracts/expiring", options);
    },

    /** Simuler les cotisations sociales employe/employeur et l'impot sur le revenu pour un salaire brut donne, sans persister (manager) */
    simulateCotisations(options = {}) {
      return request("POST", "/cotisation-simulation", options);
    },

    /** KPIs detailles */
    getDashboardKpi(options = {}) {
      return request("GET", "/dashboard/kpi", options);
    },

    /** Lire les signaux manager du jour */
    getDashboardManagerDigest(options = {}) {
      return request("GET", "/dashboard/manager-digest", options);
    },

    /** Activite recente */
    getDashboardRecentActivity(options = {}) {
      return request("GET", "/dashboard/recent-activity", options);
    },

    /** Resume dashboard */
    getDashboardSummary(options = {}) {
      return request("GET", "/dashboard/summary", options);
    },

    /** Supprimer le token FCM du device courant au logout */
    deleteDeviceTokens(options = {}) {
      return request("DELETE", "/device-tokens", options);
    },

    /** Lister les tokens push actifs de l'utilisateur courant */
    getDeviceTokens(options = {}) {
      return request("GET", "/device-tokens", options);
    },

    /** Enregistrer ou rafraichir le token FCM du device courant */
    postDeviceTokens(options = {}) {
      return request("POST", "/device-tokens", options);
    },

    /** Lister les employes */
    getEmployees(options = {}) {
      return request("GET", "/employees", options);
    },

    /** Creer un employe */
    postEmployees(options = {}) {
      return request("POST", "/employees", options);
    },

    /** Voir un employe */
    getEmployeesByEmployee(options = {}) {
      return request("GET", "/employees/{employee}", options);
    },

    /** Patch employe */
    patchEmployeesByEmployee(options = {}) {
      return request("PATCH", "/employees/{employee}", options);
    },

    /** Mettre a jour un employe */
    putEmployeesByEmployee(options = {}) {
      return request("PUT", "/employees/{employee}", options);
    },

    /** Archiver un employe */
    postEmployeesByEmployeeArchive(options = {}) {
      return request("POST", "/employees/{employee}/archive", options);
    },

    /** Certificat de travail PDF (fin de contrat, F-08) */
    getEmployeesByEmployeeCertificateOfEmployment(options = {}) {
      return request("GET", "/employees/{employee}/certificate-of-employment", options);
    },

    /** Resume journalier d'un employe */
    getEmployeesByEmployeeDailySummary(options = {}) {
      return request("GET", "/employees/{employee}/daily-summary", options);
    },

    /** Solde de tout compte (fin de contrat, F-08) */
    getEmployeesByEmployeeEndOfContract(options = {}) {
      return request("GET", "/employees/{employee}/end-of-contract", options);
    },

    /** Estimation sur periode */
    getEmployeesByEmployeeQuickEstimate(options = {}) {
      return request("GET", "/employees/{employee}/quick-estimate", options);
    },

    /** Telecharger le PDF d'estimation */
    getEmployeesByEmployeeReceipt(options = {}) {
      return request("GET", "/employees/{employee}/receipt", options);
    },

    /** Importer des employes par CSV */
    postEmployeesImport(options = {}) {
      return request("POST", "/employees/import", options);
    },

    /** Template CSV import */
    getEmployeesImportTemplate(options = {}) {
      return request("GET", "/employees/import-template", options);
    },

    /** Lister les evaluations */
    getEvaluations(options = {}) {
      return request("GET", "/evaluations", options);
    },

    /** Creer une evaluation */
    postEvaluations(options = {}) {
      return request("POST", "/evaluations", options);
    },

    /** Supprimer une evaluation */
    deleteEvaluationsByEvaluation(options = {}) {
      return request("DELETE", "/evaluations/{evaluation}", options);
    },

    /** Voir une evaluation */
    getEvaluationsByEvaluation(options = {}) {
      return request("GET", "/evaluations/{evaluation}", options);
    },

    /** Mettre a jour partiellement une evaluation */
    patchEvaluationsByEvaluation(options = {}) {
      return request("PATCH", "/evaluations/{evaluation}", options);
    },

    /** Mettre a jour une evaluation */
    putEvaluationsByEvaluation(options = {}) {
      return request("PUT", "/evaluations/{evaluation}", options);
    },

    /** Accuser reception d'une evaluation */
    putEvaluationsByEvaluationAcknowledge(options = {}) {
      return request("PUT", "/evaluations/{evaluation}/acknowledge", options);
    },

    /** Soumettre une evaluation */
    putEvaluationsByEvaluationSubmit(options = {}) {
      return request("PUT", "/evaluations/{evaluation}/submit", options);
    },

    /** Lister les notes de frais */
    getExpenseClaims(options = {}) {
      return request("GET", "/expense-claims", options);
    },

    /** Creer une note de frais */
    postExpenseClaims(options = {}) {
      return request("POST", "/expense-claims", options);
    },

    /** Voir une note de frais */
    getExpenseClaimsByExpenseClaim(options = {}) {
      return request("GET", "/expense-claims/{expenseClaim}", options);
    },

    /** Approuver une note de frais */
    postExpenseClaimsByExpenseClaimApprove(options = {}) {
      return request("POST", "/expense-claims/{expenseClaim}/approve", options);
    },

    /** Rejeter une note de frais */
    postExpenseClaimsByExpenseClaimReject(options = {}) {
      return request("POST", "/expense-claims/{expenseClaim}/reject", options);
    },

    /** Soumettre une note de frais */
    postExpenseClaimsByExpenseClaimSubmit(options = {}) {
      return request("POST", "/expense-claims/{expenseClaim}/submit", options);
    },

    /** Exporter les bulletins de paie de l'entreprise (JSON ou CSV encode en JSON) - manager uniquement */
    exportPaySlips(options = {}) {
      return request("GET", "/export/pay-slips", options);
    },

    /** Exporter les absences */
    getExportsAbsences(options = {}) {
      return request("GET", "/exports/absences", options);
    },

    /** Exporter le pointage */
    getExportsAttendance(options = {}) {
      return request("GET", "/exports/attendance", options);
    },

    /** Exporter les contrats */
    getExportsContracts(options = {}) {
      return request("GET", "/exports/contracts", options);
    },

    /** Exporter les employes */
    getExportsEmployees(options = {}) {
      return request("GET", "/exports/employees", options);
    },

    /** Historique des exports */
    getExportsHistory(options = {}) {
      return request("GET", "/exports/history", options);
    },

    /** Exporter les bulletins */
    getExportsPaySlips(options = {}) {
      return request("GET", "/exports/pay-slips", options);
    },

    /** Exporter les formations */
    getExportsTraining(options = {}) {
      return request("GET", "/exports/training", options);
    },

    /** Exporter la flotte */
    getExportsVehicles(options = {}) {
      return request("GET", "/exports/vehicles", options);
    },

    /** Verifier si une fonctionnalite est activee pour le plan de l'entreprise courante */
    checkFeatureFlag(options = {}) {
      return request("GET", "/feature-flags/check/{featureKey}", options);
    },

    /** Voir la matrice complete feature x plan */
    getFeatureFlagMatrix(options = {}) {
      return request("GET", "/feature-flags/matrix", options);
    },

    /** Modifier la matrice feature x plan (reserve a l'administration plateforme) */
    updateFeatureFlagMatrix(options = {}) {
      return request("PUT", "/feature-flags/matrix", options);
    },

    /** Voir le detail d'une fonctionnalite du registre */
    getFeatureByKey(options = {}) {
      return request("GET", "/features/{key}", options);
    },

    /** Statistiques du registre de fonctionnalites (admin) */
    getFeatureRegistryStatistics(options = {}) {
      return request("GET", "/features/admin/statistics", options);
    },

    /** Synchroniser manuellement le registre de fonctionnalites (admin) */
    synchronizeFeatureRegistry(options = {}) {
      return request("POST", "/features/admin/synchronize", options);
    },

    /** Lister les fonctionnalites compatibles avec une version mobile donnee */
    getCompatibleFeatures(options = {}) {
      return request("GET", "/features/compatible/{version}", options);
    },

    /** Obtenir le manifeste des fonctionnalites disponibles pour l'utilisateur courant */
    getFeatureManifest(options = {}) {
      return request("GET", "/features/manifest", options);
    },

    /** Carte temps reel des vehicules */
    getFleetLiveMap(options = {}) {
      return request("GET", "/fleet/live-map", options);
    },

    /** Vue d'ensemble de la flotte */
    getFleetOverview(options = {}) {
      return request("GET", "/fleet/overview", options);
    },

    /** Rapport consommation carburant */
    getFleetReportsFuel(options = {}) {
      return request("GET", "/fleet/reports/fuel", options);
    },

    /** Vehicules necessitant une maintenance */
    getFleetReportsMaintenanceDue(options = {}) {
      return request("GET", "/fleet/reports/maintenance-due", options);
    },

    /** Rapport kilometrage */
    getFleetReportsMileage(options = {}) {
      return request("GET", "/fleet/reports/mileage", options);
    },

    /** Healthcheck live + ready */
    getHealth(options = {}) {
      return request("GET", "/health", options);
    },

    /** Traductions pour une locale */
    getI18nByLocale(options = {}) {
      return request("GET", "/i18n/{locale}", options);
    },

    /** Verification interne MediaMTX */
    getInternalCameraTokenVerify(options = {}) {
      return request("GET", "/internal/camera-token/verify", options);
    },

    /** Lister les invitations de l'entreprise */
    getInvitations(options = {}) {
      return request("GET", "/invitations", options);
    },

    /** Renvoyer une invitation */
    postInvitationsByInvitationResend(options = {}) {
      return request("POST", "/invitations/{invitation}/resend", options);
    },

    /** Enregistrer un kiosk */
    postKiosks(options = {}) {
      return request("POST", "/kiosks", options);
    },

    /** Pointage via kiosk */
    postKiosksByDeviceCodePunch(options = {}) {
      return request("POST", "/kiosks/{deviceCode}/punch", options);
    },

    /** Roster biometrie d'un kiosk */
    getKiosksByDeviceCodeRoster(options = {}) {
      return request("GET", "/kiosks/{deviceCode}/roster", options);
    },

    /** Synchroniser des evenements offline */
    postKiosksByDeviceCodeSync(options = {}) {
      return request("POST", "/kiosks/{deviceCode}/sync", options);
    },

    /** Lire le score de readiness lancement du tenant */
    getLaunchReadiness(options = {}) {
      return request("GET", "/launch-readiness", options);
    },

    /** Lister les accruals */
    getLeaveAccruals(options = {}) {
      return request("GET", "/leave-accruals", options);
    },

    /** Creer un accrual */
    postLeaveAccruals(options = {}) {
      return request("POST", "/leave-accruals", options);
    },

    /** Soldes de conges globaux (manager) */
    getLeaveBalances(options = {}) {
      return request("GET", "/leave-balances", options);
    },

    /** Lister les politiques de conges */
    getLeavePolicies(options = {}) {
      return request("GET", "/leave-policies", options);
    },

    /** Creer une politique de conges */
    postLeavePolicies(options = {}) {
      return request("POST", "/leave-policies", options);
    },

    /** Supprimer une politique */
    deleteLeavePoliciesByLeavePolicy(options = {}) {
      return request("DELETE", "/leave-policies/{leavePolicy}", options);
    },

    /** Voir une politique */
    getLeavePoliciesByLeavePolicy(options = {}) {
      return request("GET", "/leave-policies/{leavePolicy}", options);
    },

    /** Modifier une politique */
    putLeavePoliciesByLeavePolicy(options = {}) {
      return request("PUT", "/leave-policies/{leavePolicy}", options);
    },

    /** Lister les prets */
    getLoans(options = {}) {
      return request("GET", "/loans", options);
    },

    /** Demander un pret */
    postLoans(options = {}) {
      return request("POST", "/loans", options);
    },

    /** Voir un pret */
    getLoansByEmployeeLoan(options = {}) {
      return request("GET", "/loans/{employeeLoan}", options);
    },

    /** Approuver un pret */
    postLoansByEmployeeLoanApprove(options = {}) {
      return request("POST", "/loans/{employeeLoan}/approve", options);
    },

    /** Decaisser un pret */
    postLoansByEmployeeLoanDisburse(options = {}) {
      return request("POST", "/loans/{employeeLoan}/disburse", options);
    },

    /** Compte social connecte du tenant */
    getMarketingSocialAccount(options = {}) {
      return request("GET", "/marketing/social-account", options);
    },

    /** Connecter un compte social (agregateur Ayrshare) */
    postMarketingSocialAccountConnect(options = {}) {
      return request("POST", "/marketing/social-account/connect", options);
    },

    /** Deconnecter le compte social du tenant */
    postMarketingSocialAccountDisconnect(options = {}) {
      return request("POST", "/marketing/social-account/disconnect", options);
    },

    /** Lister les publications reseaux sociaux du tenant */
    getMarketingSocialPosts(options = {}) {
      return request("GET", "/marketing/social-posts", options);
    },

    /** Creer une publication (brouillon, ou planifiee/publiee si scheduled_at fourni) */
    postMarketingSocialPosts(options = {}) {
      return request("POST", "/marketing/social-posts", options);
    },

    /** Supprimer une publication (draft uniquement) */
    deleteMarketingSocialPostsBySocialPost(options = {}) {
      return request("DELETE", "/marketing/social-posts/{socialPost}", options);
    },

    /** Detail d'une publication */
    getMarketingSocialPostsBySocialPost(options = {}) {
      return request("GET", "/marketing/social-posts/{socialPost}", options);
    },

    /** Modifier une publication (draft uniquement) */
    patchMarketingSocialPostsBySocialPost(options = {}) {
      return request("PATCH", "/marketing/social-posts/{socialPost}", options);
    },

    /** Publier immediatement ou (re)planifier une publication */
    postMarketingSocialPostsBySocialPostPublish(options = {}) {
      return request("POST", "/marketing/social-posts/{socialPost}/publish", options);
    },

    /** Mon solde de paie courant */
    getMeBalance(options = {}) {
      return request("GET", "/me/balance", options);
    },

    /** Lire le parcours professionnel durable de l'employe courant */
    getMeCareer(options = {}) {
      return request("GET", "/me/career", options);
    },

    /** Soumettre une demande d'integration via QR entreprise */
    postMeCompanyQrScan(options = {}) {
      return request("POST", "/me/company-qr/scan", options);
    },

    /** Mes contrats */
    getMeContracts(options = {}) {
      return request("GET", "/me/contracts", options);
    },

    /** Resume journalier utilisateur courant */
    getMeDailySummary(options = {}) {
      return request("GET", "/me/daily-summary", options);
    },

    /** Mes soldes de conges */
    getMeLeaveBalances(options = {}) {
      return request("GET", "/me/leave-balances", options);
    },

    /** Mes prets */
    getMeLoans(options = {}) {
      return request("GET", "/me/loans", options);
    },

    /** Mes remboursements de pret */
    getMeLoansByLoanRepayments(options = {}) {
      return request("GET", "/me/loans/{loan}/repayments", options);
    },

    /** Resume mensuel utilisateur courant */
    getMeMonthlySummary(options = {}) {
      return request("GET", "/me/monthly-summary", options);
    },

    /** Mes bulletins de paie */
    getMePaySlips(options = {}) {
      return request("GET", "/me/pay-slips", options);
    },

    /** Voir un de mes bulletins de paie */
    showMyPaySlip(options = {}) {
      return request("GET", "/me/pay-slips/{paySlip}", options);
    },

    /** Telecharger un de mes bulletins de paie en PDF */
    downloadMyPaySlipPdf(options = {}) {
      return request("GET", "/me/pay-slips/{paySlip}/pdf", options);
    },

    /** Mes documents de paiement */
    getMePaymentDocuments(options = {}) {
      return request("GET", "/me/payment-documents", options);
    },

    /** Telecharger un document de paiement */
    getMePaymentDocumentsByPaymentDocumentDownload(options = {}) {
      return request("GET", "/me/payment-documents/{paymentDocument}/download", options);
    },

    /** Generer le QR profil employe */
    getMeQrProfile(options = {}) {
      return request("GET", "/me/qr-profile", options);
    },

    /** Estimation utilisateur courant */
    getMeQuickEstimate(options = {}) {
      return request("GET", "/me/quick-estimate", options);
    },

    /** Mes formations */
    getMeTrainings(options = {}) {
      return request("GET", "/me/trainings", options);
    },

    /** Auto-inscription a une formation */
    postMeTrainingsBySessionEnroll(options = {}) {
      return request("POST", "/me/trainings/{session}/enroll", options);
    },

    /** Lire les preferences de notification de l'utilisateur courant */
    getNotificationPreferences(options = {}) {
      return request("GET", "/notification-preferences", options);
    },

    /** Mettre a jour les preferences de notification de l'utilisateur courant */
    patchNotificationPreferences(options = {}) {
      return request("PATCH", "/notification-preferences", options);
    },

    /** Lister les notifications de l'utilisateur courant */
    getNotifications(options = {}) {
      return request("GET", "/notifications", options);
    },

    /** Supprimer une notification */
    deleteNotificationsByNotification(options = {}) {
      return request("DELETE", "/notifications/{notification}", options);
    },

    /** Marquer une notification comme lue */
    putNotificationsByNotificationRead(options = {}) {
      return request("PUT", "/notifications/{notification}/read", options);
    },

    /** Marquer toutes les notifications comme lues */
    putNotificationsReadAll(options = {}) {
      return request("PUT", "/notifications/read-all", options);
    },

    /** Marquer une étape comme complète */
    patchOnboardingSetupByStepKeyComplete(options = {}) {
      return request("PATCH", "/onboarding-setup/{stepKey}/complete", options);
    },

    /** Ignorer une étape d'onboarding */
    patchOnboardingSetupByStepKeySkip(options = {}) {
      return request("PATCH", "/onboarding-setup/{stepKey}/skip", options);
    },

    /** Récupérer la checklist d'onboarding */
    getOnboardingSetupChecklist(options = {}) {
      return request("GET", "/onboarding-setup/checklist", options);
    },

    /** Progression globale de l'onboarding */
    getOnboardingSetupProgress(options = {}) {
      return request("GET", "/onboarding-setup/progress", options);
    },

    /** Organigramme complet */
    getOrgChart(options = {}) {
      return request("GET", "/org-chart", options);
    },

    /** Chaine hierarchique */
    getOrgChartByEmployeeIdManagerChain(options = {}) {
      return request("GET", "/org-chart/{employeeId}/manager-chain", options);
    },

    /** Subordonnes d'un employe */
    getOrgChartByEmployeeIdSubordinates(options = {}) {
      return request("GET", "/org-chart/{employeeId}/subordinates", options);
    },

    /** Candidature partenaire */
    postPartnerApply(options = {}) {
      return request("POST", "/partner/apply", options);
    },

    /** Entreprises parrainées par le partenaire */
    getPartnerCompanies(options = {}) {
      return request("GET", "/partner/companies", options);
    },

    /** Demande de versement commission */
    postPartnerPayout(options = {}) {
      return request("POST", "/partner/payout", options);
    },

    /** Statistiques partenaire connecté */
    getPartnerStats(options = {}) {
      return request("GET", "/partner/stats", options);
    },

    /** Lister les bulletins du tenant (manager) */
    getPaySlips(options = {}) {
      return request("GET", "/pay-slips", options);
    },

    /** Voir un bulletin de paie */
    getPaySlipsByPaySlip(options = {}) {
      return request("GET", "/pay-slips/{paySlip}", options);
    },

    /** Telecharger bulletin PDF */
    getPaySlipsByPaySlipPdf(options = {}) {
      return request("GET", "/pay-slips/{paySlip}/pdf", options);
    },

    /** Lister les lots de paiement */
    getPaymentBatches(options = {}) {
      return request("GET", "/payment-batches", options);
    },

    /** Creer un lot de paiement depuis un cycle paie */
    postPaymentBatches(options = {}) {
      return request("POST", "/payment-batches", options);
    },

    /** Detail d'un lot de paiement */
    getPaymentBatchesByPaymentBatch(options = {}) {
      return request("GET", "/payment-batches/{paymentBatch}", options);
    },

    /** Declarer un lot de paiement comme envoye */
    postPaymentBatchesByPaymentBatchMarkPaid(options = {}) {
      return request("POST", "/payment-batches/{paymentBatch}/mark-paid", options);
    },

    /** Confirmer la reception d'un paiement */
    postPaymentConfirmationsByPaymentItemConfirm(options = {}) {
      return request("POST", "/payment-confirmations/{paymentItem}/confirm", options);
    },

    /** Alias mobile pour documents de paiement d'un cycle */
    getPaymentsByPayrollRunDocuments(options = {}) {
      return request("GET", "/payments/{payrollRun}/documents", options);
    },

    /** Lister les sessions de paie */
    getPayrollRuns(options = {}) {
      return request("GET", "/payroll-runs", options);
    },

    /** Creer une session de paie */
    postPayrollRuns(options = {}) {
      return request("POST", "/payroll-runs", options);
    },

    /** Voir une session de paie */
    getPayrollRunsByPayrollRun(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}", options);
    },

    /** Rapport d'anomalies pre-cloture (F-20) */
    getPayrollRunsByPayrollRunAnomalies(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}/anomalies", options);
    },

    /** Calculer la paie */
    postPayrollRunsByPayrollRunCalculate(options = {}) {
      return request("POST", "/payroll-runs/{payrollRun}/calculate", options);
    },

    /** Annuler une session de paie */
    postPayrollRunsByPayrollRunCancel(options = {}) {
      return request("POST", "/payroll-runs/{payrollRun}/cancel", options);
    },

    /** Journal de paie mensuel CSV (F-10) */
    getPayrollRunsByPayrollRunJournal(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}/journal", options);
    },

    /** Verrouiller la session de paie (cloture comptable, F-11) */
    postPayrollRunsByPayrollRunLock(options = {}) {
      return request("POST", "/payroll-runs/{payrollRun}/lock", options);
    },

    /** Lister les bulletins de paie d'une session */
    listPayrollRunPaySlips(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}/pay-slips", options);
    },

    /** Documents de paiement d'un cycle paie */
    getPayrollRunsByPayrollRunPaymentDocuments(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}/payment-documents", options);
    },

    /** Resume de la session de paie */
    getPayrollRunsByPayrollRunSummary(options = {}) {
      return request("GET", "/payroll-runs/{payrollRun}/summary", options);
    },

    /** Deverrouiller une session cloturee (raison obligatoire, F-11) */
    postPayrollRunsByPayrollRunUnlock(options = {}) {
      return request("POST", "/payroll-runs/{payrollRun}/unlock", options);
    },

    /** Valider la session de paie */
    postPayrollRunsByPayrollRunValidate(options = {}) {
      return request("POST", "/payroll-runs/{payrollRun}/validate", options);
    },

    /** Previsualiser un cycle de paie candidat */
    getPayrollCyclesPreview(options = {}) {
      return request("GET", "/payroll/cycles/preview", options);
    },

    /** Resume mobile des soldes paie equipe */
    getPayrollMobileSummary(options = {}) {
      return request("GET", "/payroll/mobile-summary", options);
    },

    /** Connexion super-admin */
    postPlatformAuthLogin(options = {}) {
      return request("POST", "/platform/auth/login", options);
    },

    /** Deconnexion super-admin */
    postPlatformAuthLogout(options = {}) {
      return request("POST", "/platform/auth/logout", options);
    },

    /** Super-admin courant */
    getPlatformAuthMe(options = {}) {
      return request("GET", "/platform/auth/me", options);
    },

    /** Lister les societes */
    getPlatformCompanies(options = {}) {
      return request("GET", "/platform/companies", options);
    },

    /** Creer une societe shared */
    postPlatformCompanies(options = {}) {
      return request("POST", "/platform/companies", options);
    },

    /** Lire les feature flags d'une societe */
    getPlatformCompaniesByCompanyFeatures(options = {}) {
      return request("GET", "/platform/companies/{company}/features", options);
    },

    /** Mettre a jour les feature flags d'une societe */
    patchPlatformCompaniesByCompanyFeatures(options = {}) {
      return request("PATCH", "/platform/companies/{company}/features", options);
    },

    /** Health detaille d'une societe */
    getPlatformCompaniesByCompanyHealth(options = {}) {
      return request("GET", "/platform/companies/{company}/health", options);
    },

    /** Lire l'abonnement plateforme d'une societe */
    getPlatformCompaniesByCompanySubscription(options = {}) {
      return request("GET", "/platform/companies/{company}/subscription", options);
    },

    /** Mettre a jour l'abonnement plateforme d'une societe */
    patchPlatformCompaniesByCompanySubscription(options = {}) {
      return request("PATCH", "/platform/companies/{company}/subscription", options);
    },

    /** Vue portefeuille health des societes */
    getPlatformCompaniesHealth(options = {}) {
      return request("GET", "/platform/companies/health", options);
    },

    /** Lister les demandes de creation de societe */
    getPlatformCompanyRequests(options = {}) {
      return request("GET", "/platform/company-requests", options);
    },

    /** Lire une demande de creation de societe */
    getPlatformCompanyRequestsById(options = {}) {
      return request("GET", "/platform/company-requests/{id}", options);
    },

    /** Approuver ou rejeter une demande de creation de societe */
    patchPlatformCompanyRequestsById(options = {}) {
      return request("PATCH", "/platform/company-requests/{id}", options);
    },

    /** Lister les pays supportes et leurs defaults */
    getPlatformCountryDefaults(options = {}) {
      return request("GET", "/platform/country-defaults", options);
    },

    /** Lister les partenaires (admin) */
    getPlatformGrowthPartners(options = {}) {
      return request("GET", "/platform/growth/partners", options);
    },

    /** Mettre à jour le taux de commission d'un partenaire */
    patchPlatformGrowthPartnersByPartnerRate(options = {}) {
      return request("PATCH", "/platform/growth/partners/{partner}/rate", options);
    },

    /** Lister les demandes de versement */
    getPlatformGrowthPayouts(options = {}) {
      return request("GET", "/platform/growth/payouts", options);
    },

    /** Agregats business du cockpit super-admin */
    getPlatformMetricsOverview(options = {}) {
      return request("GET", "/platform/metrics/overview", options);
    },

    /** Lister le catalogue des plans SaaS */
    getPlatformPlans(options = {}) {
      return request("GET", "/platform/plans", options);
    },

    /** Lister les postes */
    getPositions(options = {}) {
      return request("GET", "/positions", options);
    },

    /** Creer un poste */
    postPositions(options = {}) {
      return request("POST", "/positions", options);
    },

    /** Supprimer un poste */
    deletePositionsByPosition(options = {}) {
      return request("DELETE", "/positions/{position}", options);
    },

    /** Voir un poste */
    getPositionsByPosition(options = {}) {
      return request("GET", "/positions/{position}", options);
    },

    /** Modifier un poste */
    putPositionsByPosition(options = {}) {
      return request("PUT", "/positions/{position}", options);
    },

    /** Predire les risques d'absenteisme */
    getPredictionsAbsenteeism(options = {}) {
      return request("GET", "/predictions/absenteeism", options);
    },

    /** Notifications RH proactives generees par l'IA */
    getPredictionsNotifications(options = {}) {
      return request("GET", "/predictions/notifications", options);
    },

    /** Predire le risque de turnover par employe */
    getPredictionsTurnover(options = {}) {
      return request("GET", "/predictions/turnover", options);
    },

    /** Enregistrer ou retirer le consentement biometrique */
    patchPrivacyBiometricConsent(options = {}) {
      return request("PATCH", "/privacy/biometric-consent", options);
    },

    /** Creer une demande de suppression non destructive */
    postPrivacyDeletionRequest(options = {}) {
      return request("POST", "/privacy/deletion-request", options);
    },

    /** Exporter les donnees personnelles de l'employe authentifie */
    getPrivacyExport(options = {}) {
      return request("GET", "/privacy/export", options);
    },

    /** Lister les projets */
    getProjects(options = {}) {
      return request("GET", "/projects", options);
    },

    /** Creer un projet */
    postProjects(options = {}) {
      return request("POST", "/projects", options);
    },

    /** Supprimer un projet */
    deleteProjectsByProject(options = {}) {
      return request("DELETE", "/projects/{project}", options);
    },

    /** Voir un projet */
    getProjectsByProject(options = {}) {
      return request("GET", "/projects/{project}", options);
    },

    /** Mettre a jour partiellement un projet */
    patchProjectsByProject(options = {}) {
      return request("PATCH", "/projects/{project}", options);
    },

    /** Mettre a jour un projet */
    putProjectsByProject(options = {}) {
      return request("PUT", "/projects/{project}", options);
    },

    /** Lister les jours fériés du pays (manager principal : nationaux + entreprise) */
    listPublicHolidays(options = {}) {
      return request("GET", "/public-holidays", options);
    },

    /** Créer un jour férié d'entreprise (manager principal) */
    storePublicHoliday(options = {}) {
      return request("POST", "/public-holidays", options);
    },

    /** Supprimer un jour férié d'entreprise (manager principal) */
    destroyPublicHoliday(options = {}) {
      return request("DELETE", "/public-holidays/{publicHoliday}", options);
    },

    /** Modifier un jour férié d'entreprise (manager principal) */
    updatePublicHoliday(options = {}) {
      return request("PUT", "/public-holidays/{publicHoliday}", options);
    },

    /** Envoyer une notification push de test a un employe */
    postPushNotificationsSend(options = {}) {
      return request("POST", "/push-notifications/send", options);
    },

    /** Modifier un candidat */
    putRecruitmentApplicantsByApplicant(options = {}) {
      return request("PUT", "/recruitment/applicants/{applicant}", options);
    },

    /** Planifier un entretien */
    postRecruitmentApplicantsByApplicantInterviews(options = {}) {
      return request("POST", "/recruitment/applicants/{applicant}/interviews", options);
    },

    /** Modifier un entretien */
    putRecruitmentInterviewsByInterview(options = {}) {
      return request("PUT", "/recruitment/interviews/{interview}", options);
    },

    /** Lister les offres d'emploi */
    getRecruitmentJobs(options = {}) {
      return request("GET", "/recruitment/jobs", options);
    },

    /** Creer une offre d'emploi */
    postRecruitmentJobs(options = {}) {
      return request("POST", "/recruitment/jobs", options);
    },

    /** Voir une offre */
    getRecruitmentJobsByJobPosting(options = {}) {
      return request("GET", "/recruitment/jobs/{jobPosting}", options);
    },

    /** Modifier une offre */
    putRecruitmentJobsByJobPosting(options = {}) {
      return request("PUT", "/recruitment/jobs/{jobPosting}", options);
    },

    /** Lister les candidats */
    getRecruitmentJobsByJobPostingApplicants(options = {}) {
      return request("GET", "/recruitment/jobs/{jobPosting}/applicants", options);
    },

    /** Ajouter un candidat */
    postRecruitmentJobsByJobPostingApplicants(options = {}) {
      return request("POST", "/recruitment/jobs/{jobPosting}/applicants", options);
    },

    /** Cloturer une offre */
    postRecruitmentJobsByJobPostingClose(options = {}) {
      return request("POST", "/recruitment/jobs/{jobPosting}/close", options);
    },

    /** Publier une offre */
    postRecruitmentJobsByJobPostingPublish(options = {}) {
      return request("POST", "/recruitment/jobs/{jobPosting}/publish", options);
    },

    /** Lister les avances sur salaire */
    getSalaryAdvances(options = {}) {
      return request("GET", "/salary-advances", options);
    },

    /** Demander une avance sur salaire */
    postSalaryAdvances(options = {}) {
      return request("POST", "/salary-advances", options);
    },

    /** Annuler une avance (employe proprietaire) */
    deleteSalaryAdvancesBySalaryAdvance(options = {}) {
      return request("DELETE", "/salary-advances/{salaryAdvance}", options);
    },

    /** Voir une avance */
    getSalaryAdvancesBySalaryAdvance(options = {}) {
      return request("GET", "/salary-advances/{salaryAdvance}", options);
    },

    /** Approuver une avance (manager) */
    putSalaryAdvancesBySalaryAdvanceApprove(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/approve", options);
    },

    /** Confirmer la reception de l'avance (employe) */
    putSalaryAdvancesBySalaryAdvanceConfirmReceived(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/confirm-received", options);
    },

    /** Ouvrir une reclamation sur une avance dont le paiement a ete declare mais non recu (employe) */
    disputeSalaryAdvance(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/dispute", options);
    },

    /** Valider une avance avant paiement (manager/RH) */
    putSalaryAdvancesBySalaryAdvanceManagerApprove(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/manager-approve", options);
    },

    /** Declarer l'avance comme envoyee (manager/RH) */
    putSalaryAdvancesBySalaryAdvanceMarkPaid(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/mark-paid", options);
    },

    /** Telecharger le justificatif joint a une demande d'avance (employe proprietaire ou manager) */
    downloadSalaryAdvanceProof(options = {}) {
      return request("GET", "/salary-advances/{salaryAdvance}/proof", options);
    },

    /** Rejeter une avance (manager) */
    putSalaryAdvancesBySalaryAdvanceReject(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/reject", options);
    },

    /** Resoudre une reclamation sur une avance (manager/RH) */
    resolveSalaryAdvanceDispute(options = {}) {
      return request("PUT", "/salary-advances/{salaryAdvance}/resolve-dispute", options);
    },

    /** Lister les composants de salaire (manager) */
    listSalaryComponents(options = {}) {
      return request("GET", "/salary-components", options);
    },

    /** Creer un composant de salaire (manager) */
    createSalaryComponent(options = {}) {
      return request("POST", "/salary-components", options);
    },

    /** Supprimer un composant de salaire (manager) */
    deleteSalaryComponent(options = {}) {
      return request("DELETE", "/salary-components/{salaryComponent}", options);
    },

    /** Voir un composant de salaire (manager) */
    showSalaryComponent(options = {}) {
      return request("GET", "/salary-components/{salaryComponent}", options);
    },

    /** Modifier un composant de salaire (manager) */
    updateSalaryComponent(options = {}) {
      return request("PUT", "/salary-components/{salaryComponent}", options);
    },

    /** Lister les structures salariales (manager) */
    listSalaryStructures(options = {}) {
      return request("GET", "/salary-structures", options);
    },

    /** Creer une structure salariale (manager) */
    createSalaryStructure(options = {}) {
      return request("POST", "/salary-structures", options);
    },

    /** Supprimer une structure salariale (manager) */
    deleteSalaryStructure(options = {}) {
      return request("DELETE", "/salary-structures/{salaryStructure}", options);
    },

    /** Voir une structure salariale avec ses composants (manager) */
    showSalaryStructure(options = {}) {
      return request("GET", "/salary-structures/{salaryStructure}", options);
    },

    /** Modifier une structure salariale (manager) */
    updateSalaryStructure(options = {}) {
      return request("PUT", "/salary-structures/{salaryStructure}", options);
    },

    /** Lister les horaires de l'entreprise */
    getSchedules(options = {}) {
      return request("GET", "/schedules", options);
    },

    /** Creer un horaire de travail */
    postSchedules(options = {}) {
      return request("POST", "/schedules", options);
    },

    /** Supprimer un horaire non defaut */
    deleteSchedulesBySchedule(options = {}) {
      return request("DELETE", "/schedules/{schedule}", options);
    },

    /** Modifier un horaire */
    putSchedulesBySchedule(options = {}) {
      return request("PUT", "/schedules/{schedule}", options);
    },

    /** Affecter un horaire/regle entreprise a des employes */
    postSchedulesByScheduleAssignEmployees(options = {}) {
      return request("POST", "/schedules/{schedule}/assign-employees", options);
    },

    /** Lister les sites */
    getSites(options = {}) {
      return request("GET", "/sites", options);
    },

    /** Creer un site */
    postSites(options = {}) {
      return request("POST", "/sites", options);
    },

    /** Supprimer un site */
    deleteSitesBySite(options = {}) {
      return request("DELETE", "/sites/{site}", options);
    },

    /** Voir un site */
    getSitesBySite(options = {}) {
      return request("GET", "/sites/{site}", options);
    },

    /** Modifier un site */
    putSitesBySite(options = {}) {
      return request("PUT", "/sites/{site}", options);
    },

    /** Lire la configuration de mode active pour l'employe connecte */
    getSmartAttendanceConfig(options = {}) {
      return request("GET", "/smart-attendance/config", options);
    },

    /** Mettre à jour la configuration GPS (admin) */
    putSmartAttendanceConfig(options = {}) {
      return request("PUT", "/smart-attendance/config", options);
    },

    /** Statistiques du jour — Smart Attendance (manager/RH) */
    getSmartAttendanceDashboard(options = {}) {
      return request("GET", "/smart-attendance/dashboard", options);
    },

    /** Envoyer un événement géographique (entrée/sortie de zone) */
    postSmartAttendanceGeoEvents(options = {}) {
      return request("POST", "/smart-attendance/geo-events", options);
    },

    /** Lire les préférences de pointage de l'employé */
    getSmartAttendancePreferences(options = {}) {
      return request("GET", "/smart-attendance/preferences", options);
    },

    /** Mettre à jour les préférences de pointage */
    putSmartAttendancePreferences(options = {}) {
      return request("PUT", "/smart-attendance/preferences", options);
    },

    /** Lister les sessions GPS */
    getSmartAttendanceSessions(options = {}) {
      return request("GET", "/smart-attendance/sessions", options);
    },

    /** Détail d'une session GPS */
    getSmartAttendanceSessionsById(options = {}) {
      return request("GET", "/smart-attendance/sessions/{id}", options);
    },

    /** Valider ou rejeter une session GPS (manager/RH) */
    postSmartAttendanceSessionsByIdValidate(options = {}) {
      return request("POST", "/smart-attendance/sessions/{id}/validate", options);
    },

    /** Lister les regles de cotisations sociales (manager) */
    listSocialContributions(options = {}) {
      return request("GET", "/social-contributions", options);
    },

    /** Creer une regle de cotisation sociale (manager) */
    createSocialContribution(options = {}) {
      return request("POST", "/social-contributions", options);
    },

    /** Supprimer une regle de cotisation sociale (manager) */
    deleteSocialContribution(options = {}) {
      return request("DELETE", "/social-contributions/{socialContribution}", options);
    },

    /** Modifier une regle de cotisation sociale (manager) */
    updateSocialContribution(options = {}) {
      return request("PUT", "/social-contributions/{socialContribution}", options);
    },

    /** Generer la declaration trimestrielle CNAS (Algerie) pour tous les employes actifs */
    generateCnasDzDeclaration(options = {}) {
      return request("POST", "/social-declarations/cnas-dz", options);
    },

    /** Generer la declaration trimestrielle CNSS (Maroc) pour tous les employes actifs */
    generateCnssMaDeclaration(options = {}) {
      return request("POST", "/social-declarations/cnss-ma", options);
    },

    /** Generer la DSN (Declaration Sociale Nominative, France) pour un mois donne */
    generateDsnFrDeclaration(options = {}) {
      return request("POST", "/social-declarations/dsn-fr", options);
    },

    /** Configurer le SSO de l'entreprise */
    postSsoConfigure(options = {}) {
      return request("POST", "/sso/configure", options);
    },

    /** Desactiver le SSO de l'entreprise */
    deleteSsoDisable(options = {}) {
      return request("DELETE", "/sso/disable", options);
    },

    /** Callback OpenID Connect (IdP -> SP) */
    getSsoOidcByCompanyIdCallback(options = {}) {
      return request("GET", "/sso/oidc/{companyId}/callback", options);
    },

    /** Lister les fournisseurs SSO supportes */
    getSsoProviders(options = {}) {
      return request("GET", "/sso/providers", options);
    },

    /** Callback SAML 2.0 (IdP -> SP) */
    postSsoSamlByCompanyIdCallback(options = {}) {
      return request("POST", "/sso/saml/{companyId}/callback", options);
    },

    /** Statut SSO de l'entreprise */
    getSsoStatus(options = {}) {
      return request("GET", "/sso/status", options);
    },

    /** Lister les taches */
    getTasks(options = {}) {
      return request("GET", "/tasks", options);
    },

    /** Creer une tache */
    postTasks(options = {}) {
      return request("POST", "/tasks", options);
    },

    /** Supprimer une tache */
    deleteTasksByTask(options = {}) {
      return request("DELETE", "/tasks/{task}", options);
    },

    /** Voir une tache */
    getTasksByTask(options = {}) {
      return request("GET", "/tasks/{task}", options);
    },

    /** Mettre a jour partiellement une tache */
    patchTasksByTask(options = {}) {
      return request("PATCH", "/tasks/{task}", options);
    },

    /** Mettre a jour une tache */
    putTasksByTask(options = {}) {
      return request("PUT", "/tasks/{task}", options);
    },

    /** Ajouter un commentaire sur une tache */
    postTasksByTaskComments(options = {}) {
      return request("POST", "/tasks/{task}/comments", options);
    },

    /** Lister les taches du jour */
    getTasksToday(options = {}) {
      return request("GET", "/tasks/today", options);
    },

    /** Lister le bareme fiscal (tranches d'impot) (manager) */
    listTaxSlabs(options = {}) {
      return request("GET", "/tax-slabs", options);
    },

    /** Creer une tranche d'impot (manager) */
    createTaxSlab(options = {}) {
      return request("POST", "/tax-slabs", options);
    },

    /** Supprimer une tranche d'impot (manager) */
    deleteTaxSlab(options = {}) {
      return request("DELETE", "/tax-slabs/{taxSlab}", options);
    },

    /** Modifier une tranche d'impot (manager) */
    updateTaxSlab(options = {}) {
      return request("PUT", "/tax-slabs/{taxSlab}", options);
    },

    /** Synchroniser les devices Traccar */
    postTrackingSyncDevices(options = {}) {
      return request("POST", "/tracking/sync-devices", options);
    },

    /** Synchroniser les positions Traccar */
    postTrackingSyncPositions(options = {}) {
      return request("POST", "/tracking/sync-positions", options);
    },

    /** Synchroniser les trajets Traccar */
    postTrackingSyncTrips(options = {}) {
      return request("POST", "/tracking/sync-trips", options);
    },

    /** Lister les formations */
    getTrainingCourses(options = {}) {
      return request("GET", "/training/courses", options);
    },

    /** Creer une formation */
    postTrainingCourses(options = {}) {
      return request("POST", "/training/courses", options);
    },

    /** Voir une formation */
    getTrainingCoursesByTrainingCourse(options = {}) {
      return request("GET", "/training/courses/{trainingCourse}", options);
    },

    /** Modifier une formation */
    putTrainingCoursesByTrainingCourse(options = {}) {
      return request("PUT", "/training/courses/{trainingCourse}", options);
    },

    /** Lister les sessions d'une formation */
    getTrainingCoursesByTrainingCourseSessions(options = {}) {
      return request("GET", "/training/courses/{trainingCourse}/sessions", options);
    },

    /** Creer une session de formation */
    postTrainingCoursesByTrainingCourseSessions(options = {}) {
      return request("POST", "/training/courses/{trainingCourse}/sessions", options);
    },

    /** Modifier une inscription */
    putTrainingEnrollmentsByTrainingEnrollment(options = {}) {
      return request("PUT", "/training/enrollments/{trainingEnrollment}", options);
    },

    /** Modifier une session */
    putTrainingSessionsByTrainingSession(options = {}) {
      return request("PUT", "/training/sessions/{trainingSession}", options);
    },

    /** Inscrire un employe */
    postTrainingSessionsByTrainingSessionEnroll(options = {}) {
      return request("POST", "/training/sessions/{trainingSession}/enroll", options);
    },

    /** Liste de toutes les alertes vehicules */
    getVehicleAlerts(options = {}) {
      return request("GET", "/vehicle-alerts", options);
    },

    /** Acquitter une alerte vehicule */
    postVehicleAlertsByIdAcknowledge(options = {}) {
      return request("POST", "/vehicle-alerts/{id}/acknowledge", options);
    },

    /** Liste des maintenances vehicules */
    getVehicleMaintenance(options = {}) {
      return request("GET", "/vehicle-maintenance", options);
    },

    /** Planifier une maintenance */
    postVehicleMaintenance(options = {}) {
      return request("POST", "/vehicle-maintenance", options);
    },

    /** Supprimer une maintenance */
    deleteVehicleMaintenanceById(options = {}) {
      return request("DELETE", "/vehicle-maintenance/{id}", options);
    },

    /** Modifier une maintenance */
    putVehicleMaintenanceById(options = {}) {
      return request("PUT", "/vehicle-maintenance/{id}", options);
    },

    /** Liste de tous les trajets */
    getVehicleTrips(options = {}) {
      return request("GET", "/vehicle-trips", options);
    },

    /** Detail d'un trajet */
    getVehicleTripsById(options = {}) {
      return request("GET", "/vehicle-trips/{id}", options);
    },

    /** Liste des vehicules de l'entreprise */
    getVehicles(options = {}) {
      return request("GET", "/vehicles", options);
    },

    /** Creer un vehicule */
    postVehicles(options = {}) {
      return request("POST", "/vehicles", options);
    },

    /** Supprimer un vehicule */
    deleteVehiclesById(options = {}) {
      return request("DELETE", "/vehicles/{id}", options);
    },

    /** Detail d'un vehicule */
    getVehiclesById(options = {}) {
      return request("GET", "/vehicles/{id}", options);
    },

    /** Modifier un vehicule */
    putVehiclesById(options = {}) {
      return request("PUT", "/vehicles/{id}", options);
    },

    /** Alertes d'un vehicule */
    getVehiclesByIdAlerts(options = {}) {
      return request("GET", "/vehicles/{id}/alerts", options);
    },

    /** Assigner un vehicule a un employe */
    postVehiclesByIdAssign(options = {}) {
      return request("POST", "/vehicles/{id}/assign", options);
    },

    /** Historique des affectations conducteur */
    getVehiclesByIdAssignments(options = {}) {
      return request("GET", "/vehicles/{id}/assignments", options);
    },

    /** Historique maintenance d'un vehicule */
    getVehiclesByIdMaintenance(options = {}) {
      return request("GET", "/vehicles/{id}/maintenance", options);
    },

    /** Position actuelle du vehicule (via Traccar) */
    getVehiclesByIdPosition(options = {}) {
      return request("GET", "/vehicles/{id}/position", options);
    },

    /** Trajets d'un vehicule */
    getVehiclesByIdTrips(options = {}) {
      return request("GET", "/vehicles/{id}/trips", options);
    },

    /** Desassigner un vehicule */
    postVehiclesByIdUnassign(options = {}) {
      return request("POST", "/vehicles/{id}/unassign", options);
    },

    /** Viewer public par token */
    getViewCam(options = {}) {
      return request("GET", "/view/cam", options);
    },

    /** Lister les webhooks de l'entreprise */
    getWebhooks(options = {}) {
      return request("GET", "/webhooks", options);
    },

    /** Creer un webhook */
    postWebhooks(options = {}) {
      return request("POST", "/webhooks", options);
    },

    /** Supprimer un webhook */
    deleteWebhooksByWebhook(options = {}) {
      return request("DELETE", "/webhooks/{webhook}", options);
    },

    /** Voir un webhook et ses dernieres livraisons */
    getWebhooksByWebhook(options = {}) {
      return request("GET", "/webhooks/{webhook}", options);
    },

    /** Modifier un webhook */
    putWebhooksByWebhook(options = {}) {
      return request("PUT", "/webhooks/{webhook}", options);
    },

    /** Lister les livraisons webhook dead-letter (retries epuises) */
    getWebhooksByWebhookDeadLetters(options = {}) {
      return request("GET", "/webhooks/{webhook}/dead-letters", options);
    },

    /** Rejouer une livraison webhook dead-letter */
    postWebhooksByWebhookDeadLettersByDeliveryReplay(options = {}) {
      return request("POST", "/webhooks/{webhook}/dead-letters/{delivery}/replay", options);
    },

    /** Lister les types d'evenements webhook disponibles */
    getWebhooksEvents(options = {}) {
      return request("GET", "/webhooks/events", options);
    },

    /** Lister les pointeuses ZKTeco de l'entreprise (manager) */
    listZktecoDevices(options = {}) {
      return request("GET", "/zkteco/devices", options);
    },

    /** Enregistrer une nouvelle pointeuse ZKTeco (manager) */
    registerZktecoDevice(options = {}) {
      return request("POST", "/zkteco/devices", options);
    },

    /** Supprimer une pointeuse ZKTeco (manager) */
    deleteZktecoDevice(options = {}) {
      return request("DELETE", "/zkteco/devices/{id}", options);
    },

    /** Voir une pointeuse ZKTeco avec son historique de synchronisation (manager) */
    showZktecoDevice(options = {}) {
      return request("GET", "/zkteco/devices/{id}", options);
    },

    /** Modifier une pointeuse ZKTeco (manager) */
    updateZktecoDevice(options = {}) {
      return request("PUT", "/zkteco/devices/{id}", options);
    },

    /** Lister l'historique de synchronisation d'une pointeuse (manager) */
    listZktecoSyncLogs(options = {}) {
      return request("GET", "/zkteco/devices/{id}/sync-logs", options);
    },

    /** Pousser la liste des employes vers la pointeuse (manager) */
    pushZktecoUsers(options = {}) {
      return request("POST", "/zkteco/devices/{serialNumber}/push-users", options);
    },

    /** Signal de vie envoye par la pointeuse elle-meme (pas d'authentification employe) */
    zktecoHeartbeat(options = {}) {
      return request("POST", "/zkteco/heartbeat/{serialNumber}", options);
    },

    /** Pousser des pointages bruts depuis l'appareil vers le serveur (appele par l'appareil) */
    zktecoSyncAttendance(options = {}) {
      return request("POST", "/zkteco/sync-attendance/{serialNumber}", options);
    }
  };
}

export default createLeopardoClient;

export const openApiVersion = "4.23.5";
