// Generated by dev-hub/tools/generate-openapi-sdk.mjs from api/openapi.yaml.
// Do not edit manually.

export class LeopardoApiError extends Error {
  constructor(message, { status, response, body }) {
    super(message);
    this.name = "LeopardoApiError";
    this.status = status;
    this.response = response;
    this.body = body;
  }
}

export function createLeopardoClient({ baseUrl, token, fetchImpl = globalThis.fetch } = {}) {
  if (!baseUrl) {
    throw new TypeError("baseUrl is required");
  }

  if (typeof fetchImpl !== "function") {
    throw new TypeError("fetchImpl is required when global fetch is unavailable");
  }

  const normalizedBaseUrl = baseUrl.replace(/\/+$/, "");

  function buildPath(pathTemplate, pathParams = {}) {
    return pathTemplate.replace(/\{([^}]+)\}/g, (_, name) => {
      if (pathParams[name] === undefined || pathParams[name] === null) {
        throw new TypeError(`Missing path parameter: ${name}`);
      }

      return encodeURIComponent(String(pathParams[name]));
    });
  }

  function buildUrl(pathTemplate, { pathParams, query } = {}) {
    const url = new URL(`${normalizedBaseUrl}${buildPath(pathTemplate, pathParams)}`);

    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }

      if (Array.isArray(value)) {
        for (const item of value) {
          url.searchParams.append(key, String(item));
        }
      } else {
        url.searchParams.set(key, String(value));
      }
    }

    return url;
  }

  async function request(method, pathTemplate, { pathParams, query, body, headers = {} } = {}) {
    const requestHeaders = {
      Accept: "application/json",
      ...headers,
    };

    if (token) {
      requestHeaders.Authorization = `Bearer ${token}`;
    }

    const init = {
      method,
      headers: requestHeaders,
    };

    if (body !== undefined) {
      requestHeaders["Content-Type"] = requestHeaders["Content-Type"] ?? "application/json";
      init.body = requestHeaders["Content-Type"].includes("application/json") ? JSON.stringify(body) : body;
    }

    const response = await fetchImpl(buildUrl(pathTemplate, { pathParams, query }), init);
    const contentType = response.headers.get("content-type") ?? "";
    const payload = contentType.includes("application/json") ? await response.json() : await response.text();

    if (!response.ok) {
      throw new LeopardoApiError(`Leopardo API request failed with status ${response.status}`, {
        status: response.status,
        response,
        body: payload,
      });
    }

    return payload;
  }

  return {
    request,

    /** Couts IA par periode */
    getAiAnalyticsCosts(options = {}) {
      return request("GET", "/ai/analytics/costs", options);
    },

    /** Erreurs IA recentes */
    getAiAnalyticsErrors(options = {}) {
      return request("GET", "/ai/analytics/errors", options);
    },

    /** Usage des outils IA */
    getAiAnalyticsTools(options = {}) {
      return request("GET", "/ai/analytics/tools", options);
    },

    /** Metriques d'usage IA */
    getAiAnalyticsUsage(options = {}) {
      return request("GET", "/ai/analytics/usage", options);
    },

    /** Envoyer un message au chatbot IA */
    postAiChat(options = {}) {
      return request("POST", "/ai/chat", options);
    },

    /** Supprimer une conversation IA */
    deleteAiChatByConversationId(options = {}) {
      return request("DELETE", "/ai/chat/{conversationId}", options);
    },

    /** Historique des conversations IA */
    getAiChatHistory(options = {}) {
      return request("GET", "/ai/chat/history", options);
    },

    /** Liste des outils IA disponibles */
    getAiTools(options = {}) {
      return request("GET", "/ai/tools", options);
    },

    /** Historique de pointage */
    getAttendance(options = {}) {
      return request("GET", "/attendance", options);
    },

    /** Modifier directement un pointage */
    putAttendanceByAttendanceLog(options = {}) {
      return request("PUT", "/attendance/{attendanceLog}", options);
    },

    /** Check-in */
    postAttendanceCheckIn(options = {}) {
      return request("POST", "/attendance/check-in", options);
    },

    /** Check-out */
    postAttendanceCheckOut(options = {}) {
      return request("POST", "/attendance/check-out", options);
    },

    /** Demander une correction de pointage */
    postAttendanceCorrections(options = {}) {
      return request("POST", "/attendance/corrections", options);
    },

    /** Etat du jour */
    getAttendanceToday(options = {}) {
      return request("GET", "/attendance/today", options);
    },

    /** Derniere demande biometrie de l'utilisateur courant */
    getAuthBiometricEnrollment(options = {}) {
      return request("GET", "/auth/biometric-enrollment", options);
    },

    /** Soumettre une demande biometrie */
    postAuthBiometricEnrollment(options = {}) {
      return request("POST", "/auth/biometric-enrollment", options);
    },

    /** Changer le mot de passe */
    postAuthChangePassword(options = {}) {
      return request("POST", "/auth/change-password", options);
    },

    /** Connexion employee */
    postAuthLogin(options = {}) {
      return request("POST", "/auth/login", options);
    },

    /** Deconnexion employee */
    postAuthLogout(options = {}) {
      return request("POST", "/auth/logout", options);
    },

    /** Profil authentifie */
    getAuthMe(options = {}) {
      return request("GET", "/auth/me", options);
    },

    /** Mettre a jour le profil courant */
    patchAuthProfile(options = {}) {
      return request("PATCH", "/auth/profile", options);
    },

    /** Lister les demandes biometrie de la company */
    getBiometricEnrollmentRequests(options = {}) {
      return request("GET", "/biometric-enrollment-requests", options);
    },

    /** Approuver une demande biometrie */
    postBiometricEnrollmentRequestsByIdApprove(options = {}) {
      return request("POST", "/biometric-enrollment-requests/{id}/approve", options);
    },

    /** Rejeter une demande biometrie */
    postBiometricEnrollmentRequestsByIdReject(options = {}) {
      return request("POST", "/biometric-enrollment-requests/{id}/reject", options);
    },

    /** Lister les cameras */
    getCameras(options = {}) {
      return request("GET", "/cameras", options);
    },

    /** Creer une camera */
    postCameras(options = {}) {
      return request("POST", "/cameras", options);
    },

    /** Desactiver une camera */
    deleteCamerasByCamera(options = {}) {
      return request("DELETE", "/cameras/{camera}", options);
    },

    /** Voir une camera */
    getCamerasByCamera(options = {}) {
      return request("GET", "/cameras/{camera}", options);
    },

    /** Patch camera */
    patchCamerasByCamera(options = {}) {
      return request("PATCH", "/cameras/{camera}", options);
    },

    /** Mettre a jour une camera */
    putCamerasByCamera(options = {}) {
      return request("PUT", "/cameras/{camera}", options);
    },

    /** Lister les logs d'acces camera */
    getCamerasByCameraAccessLogs(options = {}) {
      return request("GET", "/cameras/{camera}/access-logs", options);
    },

    /** Lister les tokens de partage */
    getCamerasByCameraAccessTokens(options = {}) {
      return request("GET", "/cameras/{camera}/access-tokens", options);
    },

    /** Creer un token de partage */
    postCamerasByCameraAccessTokens(options = {}) {
      return request("POST", "/cameras/{camera}/access-tokens", options);
    },

    /** Revoquer un token de partage */
    deleteCamerasByCameraAccessTokensByToken(options = {}) {
      return request("DELETE", "/cameras/{camera}/access-tokens/{token}", options);
    },

    /** Lister les permissions internes */
    getCamerasByCameraPermissions(options = {}) {
      return request("GET", "/cameras/{camera}/permissions", options);
    },

    /** Creer ou remplacer une permission interne */
    postCamerasByCameraPermissions(options = {}) {
      return request("POST", "/cameras/{camera}/permissions", options);
    },

    /** Supprimer une permission interne */
    deleteCamerasByCameraPermissionsByPermission(options = {}) {
      return request("DELETE", "/cameras/{camera}/permissions/{permission}", options);
    },

    /** Regenerer un stream token client */
    getCamerasByCameraStreamToken(options = {}) {
      return request("GET", "/cameras/{camera}/stream-token", options);
    },

    /** Tester une URL RTSP */
    postCamerasTestRtsp(options = {}) {
      return request("POST", "/cameras/test-rtsp", options);
    },

    /** Persister un evenement UX client tenant-scope */
    postClientEvents(options = {}) {
      return request("POST", "/client-events", options);
    },

    /** Analytics communication tenant */
    getCommunicationAnalytics(options = {}) {
      return request("GET", "/communication/analytics", options);
    },

    /** Lister les employes */
    getEmployees(options = {}) {
      return request("GET", "/employees", options);
    },

    /** Creer un employe */
    postEmployees(options = {}) {
      return request("POST", "/employees", options);
    },

    /** Voir un employe */
    getEmployeesByEmployee(options = {}) {
      return request("GET", "/employees/{employee}", options);
    },

    /** Patch employe */
    patchEmployeesByEmployee(options = {}) {
      return request("PATCH", "/employees/{employee}", options);
    },

    /** Mettre a jour un employe */
    putEmployeesByEmployee(options = {}) {
      return request("PUT", "/employees/{employee}", options);
    },

    /** Archiver un employe */
    postEmployeesByEmployeeArchive(options = {}) {
      return request("POST", "/employees/{employee}/archive", options);
    },

    /** Resume journalier d'un employe */
    getEmployeesByEmployeeDailySummary(options = {}) {
      return request("GET", "/employees/{employee}/daily-summary", options);
    },

    /** Estimation sur periode */
    getEmployeesByEmployeeQuickEstimate(options = {}) {
      return request("GET", "/employees/{employee}/quick-estimate", options);
    },

    /** Telecharger le PDF d'estimation */
    getEmployeesByEmployeeReceipt(options = {}) {
      return request("GET", "/employees/{employee}/receipt", options);
    },

    /** Lister les evaluations */
    getEvaluations(options = {}) {
      return request("GET", "/evaluations", options);
    },

    /** Creer une evaluation */
    postEvaluations(options = {}) {
      return request("POST", "/evaluations", options);
    },

    /** Supprimer une evaluation */
    deleteEvaluationsByEvaluation(options = {}) {
      return request("DELETE", "/evaluations/{evaluation}", options);
    },

    /** Voir une evaluation */
    getEvaluationsByEvaluation(options = {}) {
      return request("GET", "/evaluations/{evaluation}", options);
    },

    /** Mettre a jour partiellement une evaluation */
    patchEvaluationsByEvaluation(options = {}) {
      return request("PATCH", "/evaluations/{evaluation}", options);
    },

    /** Mettre a jour une evaluation */
    putEvaluationsByEvaluation(options = {}) {
      return request("PUT", "/evaluations/{evaluation}", options);
    },

    /** Accuser reception d'une evaluation */
    putEvaluationsByEvaluationAcknowledge(options = {}) {
      return request("PUT", "/evaluations/{evaluation}/acknowledge", options);
    },

    /** Soumettre une evaluation */
    putEvaluationsByEvaluationSubmit(options = {}) {
      return request("PUT", "/evaluations/{evaluation}/submit", options);
    },

    /** Carte temps reel des vehicules */
    getFleetLiveMap(options = {}) {
      return request("GET", "/fleet/live-map", options);
    },

    /** Vue d'ensemble de la flotte */
    getFleetOverview(options = {}) {
      return request("GET", "/fleet/overview", options);
    },

    /** Rapport consommation carburant */
    getFleetReportsFuel(options = {}) {
      return request("GET", "/fleet/reports/fuel", options);
    },

    /** Vehicules necessitant une maintenance */
    getFleetReportsMaintenanceDue(options = {}) {
      return request("GET", "/fleet/reports/maintenance-due", options);
    },

    /** Rapport kilometrage */
    getFleetReportsMileage(options = {}) {
      return request("GET", "/fleet/reports/mileage", options);
    },

    /** Healthcheck live + ready */
    getHealth(options = {}) {
      return request("GET", "/health", options);
    },

    /** Verification interne MediaMTX */
    getInternalCameraTokenVerify(options = {}) {
      return request("GET", "/internal/camera-token/verify", options);
    },

    /** Lister les invitations de l'entreprise */
    getInvitations(options = {}) {
      return request("GET", "/invitations", options);
    },

    /** Renvoyer une invitation */
    postInvitationsByInvitationResend(options = {}) {
      return request("POST", "/invitations/{invitation}/resend", options);
    },

    /** Enregistrer un kiosk */
    postKiosks(options = {}) {
      return request("POST", "/kiosks", options);
    },

    /** Pointage via kiosk */
    postKiosksByDeviceCodePunch(options = {}) {
      return request("POST", "/kiosks/{deviceCode}/punch", options);
    },

    /** Roster biometrie d'un kiosk */
    getKiosksByDeviceCodeRoster(options = {}) {
      return request("GET", "/kiosks/{deviceCode}/roster", options);
    },

    /** Synchroniser des evenements offline */
    postKiosksByDeviceCodeSync(options = {}) {
      return request("POST", "/kiosks/{deviceCode}/sync", options);
    },

    /** Lire le score de readiness lancement du tenant */
    getLaunchReadiness(options = {}) {
      return request("GET", "/launch-readiness", options);
    },

    /** Resume journalier utilisateur courant */
    getMeDailySummary(options = {}) {
      return request("GET", "/me/daily-summary", options);
    },

    /** Resume mensuel utilisateur courant */
    getMeMonthlySummary(options = {}) {
      return request("GET", "/me/monthly-summary", options);
    },

    /** Estimation utilisateur courant */
    getMeQuickEstimate(options = {}) {
      return request("GET", "/me/quick-estimate", options);
    },

    /** Lire les preferences de notification de l'utilisateur courant */
    getNotificationPreferences(options = {}) {
      return request("GET", "/notification-preferences", options);
    },

    /** Mettre a jour les preferences de notification de l'utilisateur courant */
    patchNotificationPreferences(options = {}) {
      return request("PATCH", "/notification-preferences", options);
    },

    /** Lister les notifications de l'utilisateur courant */
    getNotifications(options = {}) {
      return request("GET", "/notifications", options);
    },

    /** Supprimer une notification */
    deleteNotificationsByNotification(options = {}) {
      return request("DELETE", "/notifications/{notification}", options);
    },

    /** Marquer une notification comme lue */
    putNotificationsByNotificationRead(options = {}) {
      return request("PUT", "/notifications/{notification}/read", options);
    },

    /** Marquer toutes les notifications comme lues */
    putNotificationsReadAll(options = {}) {
      return request("PUT", "/notifications/read-all", options);
    },

    /** Lister les bulletins du tenant (manager) */
    getPaySlips(options = {}) {
      return request("GET", "/pay-slips", options);
    },

    /** Connexion super-admin */
    postPlatformAuthLogin(options = {}) {
      return request("POST", "/platform/auth/login", options);
    },

    /** Deconnexion super-admin */
    postPlatformAuthLogout(options = {}) {
      return request("POST", "/platform/auth/logout", options);
    },

    /** Super-admin courant */
    getPlatformAuthMe(options = {}) {
      return request("GET", "/platform/auth/me", options);
    },

    /** Lister les societes */
    getPlatformCompanies(options = {}) {
      return request("GET", "/platform/companies", options);
    },

    /** Creer une societe shared */
    postPlatformCompanies(options = {}) {
      return request("POST", "/platform/companies", options);
    },

    /** Lire les feature flags d'une societe */
    getPlatformCompaniesByCompanyFeatures(options = {}) {
      return request("GET", "/platform/companies/{company}/features", options);
    },

    /** Mettre a jour les feature flags d'une societe */
    patchPlatformCompaniesByCompanyFeatures(options = {}) {
      return request("PATCH", "/platform/companies/{company}/features", options);
    },

    /** Health detaille d'une societe */
    getPlatformCompaniesByCompanyHealth(options = {}) {
      return request("GET", "/platform/companies/{company}/health", options);
    },

    /** Lire l'abonnement plateforme d'une societe */
    getPlatformCompaniesByCompanySubscription(options = {}) {
      return request("GET", "/platform/companies/{company}/subscription", options);
    },

    /** Mettre a jour l'abonnement plateforme d'une societe */
    patchPlatformCompaniesByCompanySubscription(options = {}) {
      return request("PATCH", "/platform/companies/{company}/subscription", options);
    },

    /** Vue portefeuille health des societes */
    getPlatformCompaniesHealth(options = {}) {
      return request("GET", "/platform/companies/health", options);
    },

    /** Lister les demandes de creation de societe */
    getPlatformCompanyRequests(options = {}) {
      return request("GET", "/platform/company-requests", options);
    },

    /** Lire une demande de creation de societe */
    getPlatformCompanyRequestsById(options = {}) {
      return request("GET", "/platform/company-requests/{id}", options);
    },

    /** Approuver ou rejeter une demande de creation de societe */
    patchPlatformCompanyRequestsById(options = {}) {
      return request("PATCH", "/platform/company-requests/{id}", options);
    },

    /** Agregats business du cockpit super-admin */
    getPlatformMetricsOverview(options = {}) {
      return request("GET", "/platform/metrics/overview", options);
    },

    /** Lister le catalogue des plans SaaS */
    getPlatformPlans(options = {}) {
      return request("GET", "/platform/plans", options);
    },

    /** Enregistrer ou retirer le consentement biometrique */
    patchPrivacyBiometricConsent(options = {}) {
      return request("PATCH", "/privacy/biometric-consent", options);
    },

    /** Creer une demande de suppression non destructive */
    postPrivacyDeletionRequest(options = {}) {
      return request("POST", "/privacy/deletion-request", options);
    },

    /** Exporter les donnees personnelles de l'employe authentifie */
    getPrivacyExport(options = {}) {
      return request("GET", "/privacy/export", options);
    },

    /** Lister les projets */
    getProjects(options = {}) {
      return request("GET", "/projects", options);
    },

    /** Creer un projet */
    postProjects(options = {}) {
      return request("POST", "/projects", options);
    },

    /** Supprimer un projet */
    deleteProjectsByProject(options = {}) {
      return request("DELETE", "/projects/{project}", options);
    },

    /** Voir un projet */
    getProjectsByProject(options = {}) {
      return request("GET", "/projects/{project}", options);
    },

    /** Mettre a jour partiellement un projet */
    patchProjectsByProject(options = {}) {
      return request("PATCH", "/projects/{project}", options);
    },

    /** Mettre a jour un projet */
    putProjectsByProject(options = {}) {
      return request("PUT", "/projects/{project}", options);
    },

    /** Lister les taches */
    getTasks(options = {}) {
      return request("GET", "/tasks", options);
    },

    /** Creer une tache */
    postTasks(options = {}) {
      return request("POST", "/tasks", options);
    },

    /** Supprimer une tache */
    deleteTasksByTask(options = {}) {
      return request("DELETE", "/tasks/{task}", options);
    },

    /** Voir une tache */
    getTasksByTask(options = {}) {
      return request("GET", "/tasks/{task}", options);
    },

    /** Mettre a jour partiellement une tache */
    patchTasksByTask(options = {}) {
      return request("PATCH", "/tasks/{task}", options);
    },

    /** Mettre a jour une tache */
    putTasksByTask(options = {}) {
      return request("PUT", "/tasks/{task}", options);
    },

    /** Ajouter un commentaire sur une tache */
    postTasksByTaskComments(options = {}) {
      return request("POST", "/tasks/{task}/comments", options);
    },

    /** Synchroniser les devices Traccar */
    postTrackingSyncDevices(options = {}) {
      return request("POST", "/tracking/sync-devices", options);
    },

    /** Synchroniser les positions Traccar */
    postTrackingSyncPositions(options = {}) {
      return request("POST", "/tracking/sync-positions", options);
    },

    /** Synchroniser les trajets Traccar */
    postTrackingSyncTrips(options = {}) {
      return request("POST", "/tracking/sync-trips", options);
    },

    /** Liste de toutes les alertes vehicules */
    getVehicleAlerts(options = {}) {
      return request("GET", "/vehicle-alerts", options);
    },

    /** Acquitter une alerte vehicule */
    postVehicleAlertsByIdAcknowledge(options = {}) {
      return request("POST", "/vehicle-alerts/{id}/acknowledge", options);
    },

    /** Liste des maintenances vehicules */
    getVehicleMaintenance(options = {}) {
      return request("GET", "/vehicle-maintenance", options);
    },

    /** Planifier une maintenance */
    postVehicleMaintenance(options = {}) {
      return request("POST", "/vehicle-maintenance", options);
    },

    /** Supprimer une maintenance */
    deleteVehicleMaintenanceById(options = {}) {
      return request("DELETE", "/vehicle-maintenance/{id}", options);
    },

    /** Modifier une maintenance */
    putVehicleMaintenanceById(options = {}) {
      return request("PUT", "/vehicle-maintenance/{id}", options);
    },

    /** Liste de tous les trajets */
    getVehicleTrips(options = {}) {
      return request("GET", "/vehicle-trips", options);
    },

    /** Detail d'un trajet */
    getVehicleTripsById(options = {}) {
      return request("GET", "/vehicle-trips/{id}", options);
    },

    /** Liste des vehicules de l'entreprise */
    getVehicles(options = {}) {
      return request("GET", "/vehicles", options);
    },

    /** Creer un vehicule */
    postVehicles(options = {}) {
      return request("POST", "/vehicles", options);
    },

    /** Supprimer un vehicule */
    deleteVehiclesById(options = {}) {
      return request("DELETE", "/vehicles/{id}", options);
    },

    /** Detail d'un vehicule */
    getVehiclesById(options = {}) {
      return request("GET", "/vehicles/{id}", options);
    },

    /** Modifier un vehicule */
    putVehiclesById(options = {}) {
      return request("PUT", "/vehicles/{id}", options);
    },

    /** Alertes d'un vehicule */
    getVehiclesByIdAlerts(options = {}) {
      return request("GET", "/vehicles/{id}/alerts", options);
    },

    /** Assigner un vehicule a un employe */
    postVehiclesByIdAssign(options = {}) {
      return request("POST", "/vehicles/{id}/assign", options);
    },

    /** Historique des affectations conducteur */
    getVehiclesByIdAssignments(options = {}) {
      return request("GET", "/vehicles/{id}/assignments", options);
    },

    /** Historique maintenance d'un vehicule */
    getVehiclesByIdMaintenance(options = {}) {
      return request("GET", "/vehicles/{id}/maintenance", options);
    },

    /** Position actuelle du vehicule (via Traccar) */
    getVehiclesByIdPosition(options = {}) {
      return request("GET", "/vehicles/{id}/position", options);
    },

    /** Trajets d'un vehicule */
    getVehiclesByIdTrips(options = {}) {
      return request("GET", "/vehicles/{id}/trips", options);
    },

    /** Desassigner un vehicule */
    postVehiclesByIdUnassign(options = {}) {
      return request("POST", "/vehicles/{id}/unassign", options);
    },

    /** Viewer public par token */
    getViewCam(options = {}) {
      return request("GET", "/view/cam", options);
    }
  };
}

export default createLeopardoClient;

export const openApiVersion = "4.1.81-2026-04-28";
