// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by drift_dev. Run `dart run build_runner build` to regenerate.
// ignore_for_file: type=lint, unused_import

part of 'edge_database.dart';

// **************************************************************************
// TableInfoMixin
// **************************************************************************

class $AttendanceLogsTable extends AttendanceLogs
    with TableInfo<$AttendanceLogsTable, AttendanceLog> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $AttendanceLogsTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> localId = GeneratedColumn<String>(
      'local_id', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);

  @override
  late final GeneratedColumn<int> remoteId = GeneratedColumn<int>(
      'remote_id', aliasedName, true,
      type: DriftSqlType.int, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<int> employeeId = GeneratedColumn<int>(
      'employee_id', aliasedName, false,
      type: DriftSqlType.int, requiredDuringInsert: true);

  @override
  late final GeneratedColumnWithTypeConverter<AttendanceType, String> type =
      GeneratedColumn<String>('type', aliasedName, false,
              type: DriftSqlType.string, requiredDuringInsert: true)
          .withConverter<AttendanceType>(
              $AttendanceLogsTable.$convertertype);

  @override
  late final GeneratedColumn<DateTime> checkedAt = GeneratedColumn<DateTime>(
      'checked_at', aliasedName, false,
      type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  late final GeneratedColumn<String> source = GeneratedColumn<String>(
      'source', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      defaultValue: const Constant('edge'));

  @override
  late final GeneratedColumn<String> locationJson = GeneratedColumn<String>(
      'location_json', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> syncStatus = GeneratedColumn<String>(
      'sync_status', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      defaultValue: const Constant('pending'));

  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>(
      'created_at', aliasedName, false,
      type: DriftSqlType.dateTime,
      requiredDuringInsert: false,
      defaultValue: currentDateAndTime);

  @override
  List<GeneratedColumn> get $columns => [
        localId,
        remoteId,
        employeeId,
        type,
        checkedAt,
        source,
        locationJson,
        syncStatus,
        createdAt,
      ];

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'attendance_logs';

  @override
  Set<GeneratedColumn> get $primaryKey => {localId};

  @override
  AttendanceLog map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return AttendanceLog(
      localId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}local_id'])!,
      remoteId: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}remote_id']),
      employeeId: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}employee_id'])!,
      type: $AttendanceLogsTable.$convertertype.fromSql(attachedDatabase
          .typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}type'])!),
      checkedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}checked_at'])!,
      source: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}source'])!,
      locationJson: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}location_json']),
      syncStatus: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}sync_status'])!,
      createdAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
    );
  }

  @override
  $AttendanceLogsTable createAlias(String alias) {
    return $AttendanceLogsTable(attachedDatabase, alias);
  }

  static TypeConverter<AttendanceType, String> $convertertype =
      const EnumNameConverter<AttendanceType>(AttendanceType.values);
}

class AttendanceLog extends DataClass
    implements Insertable<AttendanceLog> {
  final String localId;
  final int? remoteId;
  final int employeeId;
  final AttendanceType type;
  final DateTime checkedAt;
  final String source;
  final String? locationJson;
  final String syncStatus;
  final DateTime createdAt;

  const AttendanceLog({
    required this.localId,
    this.remoteId,
    required this.employeeId,
    required this.type,
    required this.checkedAt,
    required this.source,
    this.locationJson,
    required this.syncStatus,
    required this.createdAt,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['local_id'] = Variable<String>(localId);
    if (!nullToAbsent || remoteId != null) {
      map['remote_id'] = Variable<int>(remoteId);
    }
    map['employee_id'] = Variable<int>(employeeId);
    map['type'] = Variable<String>(
        $AttendanceLogsTable.$convertertype.toSql(type));
    map['checked_at'] = Variable<DateTime>(checkedAt);
    map['source'] = Variable<String>(source);
    if (!nullToAbsent || locationJson != null) {
      map['location_json'] = Variable<String>(locationJson);
    }
    map['sync_status'] = Variable<String>(syncStatus);
    map['created_at'] = Variable<DateTime>(createdAt);
    return map;
  }

  AttendanceLogsCompanion toCompanion(bool nullToAbsent) {
    return AttendanceLogsCompanion(
      localId: Value(localId),
      remoteId: remoteId == null && nullToAbsent
          ? const Value.absent()
          : Value(remoteId),
      employeeId: Value(employeeId),
      type: Value(type),
      checkedAt: Value(checkedAt),
      source: Value(source),
      locationJson: locationJson == null && nullToAbsent
          ? const Value.absent()
          : Value(locationJson),
      syncStatus: Value(syncStatus),
      createdAt: Value(createdAt),
    );
  }

  factory AttendanceLog.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return AttendanceLog(
      localId: serializer.fromJson<String>(json['local_id']),
      remoteId: serializer.fromJson<int?>(json['remote_id']),
      employeeId: serializer.fromJson<int>(json['employee_id']),
      type: $AttendanceLogsTable.$convertertype
          .fromSql(serializer.fromJson<String>(json['type'])),
      checkedAt: serializer.fromJson<DateTime>(json['checked_at']),
      source: serializer.fromJson<String>(json['source']),
      locationJson: serializer.fromJson<String?>(json['location_json']),
      syncStatus: serializer.fromJson<String>(json['sync_status']),
      createdAt: serializer.fromJson<DateTime>(json['created_at']),
    );
  }

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'local_id': serializer.toJson<String>(localId),
      'remote_id': serializer.toJson<int?>(remoteId),
      'employee_id': serializer.toJson<int>(employeeId),
      'type': serializer.toJson<String>(
          $AttendanceLogsTable.$convertertype.toSql(type)),
      'checked_at': serializer.toJson<DateTime>(checkedAt),
      'source': serializer.toJson<String>(source),
      'location_json': serializer.toJson<String?>(locationJson),
      'sync_status': serializer.toJson<String>(syncStatus),
      'created_at': serializer.toJson<DateTime>(createdAt),
    };
  }

  AttendanceLog copyWith({
    String? localId,
    Value<int?> remoteId = const Value.absent(),
    int? employeeId,
    AttendanceType? type,
    DateTime? checkedAt,
    String? source,
    Value<String?> locationJson = const Value.absent(),
    String? syncStatus,
    DateTime? createdAt,
  }) =>
      AttendanceLog(
        localId: localId ?? this.localId,
        remoteId: remoteId.present ? remoteId.value : this.remoteId,
        employeeId: employeeId ?? this.employeeId,
        type: type ?? this.type,
        checkedAt: checkedAt ?? this.checkedAt,
        source: source ?? this.source,
        locationJson:
            locationJson.present ? locationJson.value : this.locationJson,
        syncStatus: syncStatus ?? this.syncStatus,
        createdAt: createdAt ?? this.createdAt,
      );

  @override
  String toString() {
    return (StringBuffer('AttendanceLog(')
          ..write('localId: $localId, ')
          ..write('remoteId: $remoteId, ')
          ..write('employeeId: $employeeId, ')
          ..write('type: $type, ')
          ..write('checkedAt: $checkedAt, ')
          ..write('source: $source, ')
          ..write('locationJson: $locationJson, ')
          ..write('syncStatus: $syncStatus, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(localId, remoteId, employeeId, type,
      checkedAt, source, locationJson, syncStatus, createdAt);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AttendanceLog &&
          other.localId == localId &&
          other.remoteId == remoteId &&
          other.employeeId == employeeId &&
          other.type == type &&
          other.checkedAt == checkedAt &&
          other.source == source &&
          other.locationJson == locationJson &&
          other.syncStatus == syncStatus &&
          other.createdAt == createdAt);
}

class AttendanceLogsCompanion extends UpdateCompanion<AttendanceLog> {
  final Value<String> localId;
  final Value<int?> remoteId;
  final Value<int> employeeId;
  final Value<AttendanceType> type;
  final Value<DateTime> checkedAt;
  final Value<String> source;
  final Value<String?> locationJson;
  final Value<String> syncStatus;
  final Value<DateTime> createdAt;

  const AttendanceLogsCompanion({
    this.localId = const Value.absent(),
    this.remoteId = const Value.absent(),
    this.employeeId = const Value.absent(),
    this.type = const Value.absent(),
    this.checkedAt = const Value.absent(),
    this.source = const Value.absent(),
    this.locationJson = const Value.absent(),
    this.syncStatus = const Value.absent(),
    this.createdAt = const Value.absent(),
  });

  AttendanceLogsCompanion.insert({
    required String localId,
    this.remoteId = const Value.absent(),
    required int employeeId,
    required AttendanceType type,
    required DateTime checkedAt,
    this.source = const Value.absent(),
    this.locationJson = const Value.absent(),
    this.syncStatus = const Value.absent(),
    this.createdAt = const Value.absent(),
  })  : localId = Value(localId),
        employeeId = Value(employeeId),
        type = Value(type),
        checkedAt = Value(checkedAt);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (localId.present) map['local_id'] = Variable<String>(localId.value);
    if (remoteId.present) map['remote_id'] = Variable<int>(remoteId.value);
    if (employeeId.present) {
      map['employee_id'] = Variable<int>(employeeId.value);
    }
    if (type.present) {
      map['type'] = Variable<String>(
          $AttendanceLogsTable.$convertertype.toSql(type.value));
    }
    if (checkedAt.present) {
      map['checked_at'] = Variable<DateTime>(checkedAt.value);
    }
    if (source.present) map['source'] = Variable<String>(source.value);
    if (locationJson.present) {
      map['location_json'] = Variable<String>(locationJson.value);
    }
    if (syncStatus.present) {
      map['sync_status'] = Variable<String>(syncStatus.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<DateTime>(createdAt.value);
    }
    return map;
  }

  @override
  String toString() => 'AttendanceLogsCompanion(localId: $localId, '
      'remoteId: $remoteId, employeeId: $employeeId, type: $type, '
      'checkedAt: $checkedAt, source: $source, locationJson: $locationJson, '
      'syncStatus: $syncStatus, createdAt: $createdAt)';
}

// **************************************************************************
// EmployeeCache
// **************************************************************************

class $EmployeeCacheTable extends EmployeeCache
    with TableInfo<$EmployeeCacheTable, EmployeeCacheData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $EmployeeCacheTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      type: DriftSqlType.int, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> firstName = GeneratedColumn<String>(
      'first_name', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> lastName = GeneratedColumn<String>(
      'last_name', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> email = GeneratedColumn<String>(
      'email', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> badgeQr = GeneratedColumn<String>(
      'badge_qr', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> department = GeneratedColumn<String>(
      'department', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> jobTitle = GeneratedColumn<String>(
      'job_title', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<bool> isActive = GeneratedColumn<bool>(
      'is_active', aliasedName, false,
      type: DriftSqlType.bool,
      requiredDuringInsert: false,
      defaultValue: const Constant(true));
  @override
  late final GeneratedColumn<int> syncedAt = GeneratedColumn<int>(
      'synced_at', aliasedName, true,
      type: DriftSqlType.int, requiredDuringInsert: false);

  @override
  List<GeneratedColumn> get $columns =>
      [id, firstName, lastName, email, badgeQr, department, jobTitle, isActive, syncedAt];

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'employee_cache';

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  EmployeeCacheData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return EmployeeCacheData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}id'])!,
      firstName: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}first_name'])!,
      lastName: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}last_name'])!,
      email: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}email'])!,
      badgeQr: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}badge_qr']),
      department: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}department']),
      jobTitle: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}job_title']),
      isActive: attachedDatabase.typeMapping
          .read(DriftSqlType.bool, data['${effectivePrefix}is_active'])!,
      syncedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}synced_at']),
    );
  }

  @override
  $EmployeeCacheTable createAlias(String alias) {
    return $EmployeeCacheTable(attachedDatabase, alias);
  }
}

class EmployeeCacheData extends DataClass
    implements Insertable<EmployeeCacheData> {
  final int id;
  final String firstName;
  final String lastName;
  final String email;
  final String? badgeQr;
  final String? department;
  final String? jobTitle;
  final bool isActive;
  final int? syncedAt;

  const EmployeeCacheData({
    required this.id,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.badgeQr,
    this.department,
    this.jobTitle,
    required this.isActive,
    this.syncedAt,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['first_name'] = Variable<String>(firstName);
    map['last_name'] = Variable<String>(lastName);
    map['email'] = Variable<String>(email);
    if (!nullToAbsent || badgeQr != null) {
      map['badge_qr'] = Variable<String>(badgeQr);
    }
    if (!nullToAbsent || department != null) {
      map['department'] = Variable<String>(department);
    }
    if (!nullToAbsent || jobTitle != null) {
      map['job_title'] = Variable<String>(jobTitle);
    }
    map['is_active'] = Variable<bool>(isActive);
    if (!nullToAbsent || syncedAt != null) {
      map['synced_at'] = Variable<int>(syncedAt);
    }
    return map;
  }

  EmployeeCacheCompanion toCompanion(bool nullToAbsent) {
    return EmployeeCacheCompanion(
      id: Value(id),
      firstName: Value(firstName),
      lastName: Value(lastName),
      email: Value(email),
      badgeQr:
          badgeQr == null && nullToAbsent ? const Value.absent() : Value(badgeQr),
      department: department == null && nullToAbsent
          ? const Value.absent()
          : Value(department),
      jobTitle: jobTitle == null && nullToAbsent
          ? const Value.absent()
          : Value(jobTitle),
      isActive: Value(isActive),
      syncedAt: syncedAt == null && nullToAbsent
          ? const Value.absent()
          : Value(syncedAt),
    );
  }

  factory EmployeeCacheData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return EmployeeCacheData(
      id: serializer.fromJson<int>(json['id']),
      firstName: serializer.fromJson<String>(json['first_name']),
      lastName: serializer.fromJson<String>(json['last_name']),
      email: serializer.fromJson<String>(json['email']),
      badgeQr: serializer.fromJson<String?>(json['badge_qr']),
      department: serializer.fromJson<String?>(json['department']),
      jobTitle: serializer.fromJson<String?>(json['job_title']),
      isActive: serializer.fromJson<bool>(json['is_active']),
      syncedAt: serializer.fromJson<int?>(json['synced_at']),
    );
  }

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'first_name': serializer.toJson<String>(firstName),
      'last_name': serializer.toJson<String>(lastName),
      'email': serializer.toJson<String>(email),
      'badge_qr': serializer.toJson<String?>(badgeQr),
      'department': serializer.toJson<String?>(department),
      'job_title': serializer.toJson<String?>(jobTitle),
      'is_active': serializer.toJson<bool>(isActive),
      'synced_at': serializer.toJson<int?>(syncedAt),
    };
  }

  EmployeeCacheData copyWith({
    int? id,
    String? firstName,
    String? lastName,
    String? email,
    Value<String?> badgeQr = const Value.absent(),
    Value<String?> department = const Value.absent(),
    Value<String?> jobTitle = const Value.absent(),
    bool? isActive,
    Value<int?> syncedAt = const Value.absent(),
  }) =>
      EmployeeCacheData(
        id: id ?? this.id,
        firstName: firstName ?? this.firstName,
        lastName: lastName ?? this.lastName,
        email: email ?? this.email,
        badgeQr: badgeQr.present ? badgeQr.value : this.badgeQr,
        department: department.present ? department.value : this.department,
        jobTitle: jobTitle.present ? jobTitle.value : this.jobTitle,
        isActive: isActive ?? this.isActive,
        syncedAt: syncedAt.present ? syncedAt.value : this.syncedAt,
      );

  @override
  String toString() => 'EmployeeCacheData(id: $id, firstName: $firstName, '
      'lastName: $lastName, email: $email, badgeQr: $badgeQr, '
      'department: $department, jobTitle: $jobTitle, isActive: $isActive, '
      'syncedAt: $syncedAt)';

  @override
  int get hashCode => Object.hash(
      id, firstName, lastName, email, badgeQr, department, jobTitle, isActive, syncedAt);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is EmployeeCacheData &&
          other.id == id &&
          other.firstName == firstName &&
          other.lastName == lastName &&
          other.email == email &&
          other.badgeQr == badgeQr &&
          other.department == department &&
          other.jobTitle == jobTitle &&
          other.isActive == isActive &&
          other.syncedAt == syncedAt);
}

class EmployeeCacheCompanion extends UpdateCompanion<EmployeeCacheData> {
  final Value<int> id;
  final Value<String> firstName;
  final Value<String> lastName;
  final Value<String> email;
  final Value<String?> badgeQr;
  final Value<String?> department;
  final Value<String?> jobTitle;
  final Value<bool> isActive;
  final Value<int?> syncedAt;

  const EmployeeCacheCompanion({
    this.id = const Value.absent(),
    this.firstName = const Value.absent(),
    this.lastName = const Value.absent(),
    this.email = const Value.absent(),
    this.badgeQr = const Value.absent(),
    this.department = const Value.absent(),
    this.jobTitle = const Value.absent(),
    this.isActive = const Value.absent(),
    this.syncedAt = const Value.absent(),
  });

  EmployeeCacheCompanion.insert({
    required int id,
    required String firstName,
    required String lastName,
    required String email,
    this.badgeQr = const Value.absent(),
    this.department = const Value.absent(),
    this.jobTitle = const Value.absent(),
    this.isActive = const Value.absent(),
    this.syncedAt = const Value.absent(),
  })  : id = Value(id),
        firstName = Value(firstName),
        lastName = Value(lastName),
        email = Value(email);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (firstName.present) map['first_name'] = Variable<String>(firstName.value);
    if (lastName.present) map['last_name'] = Variable<String>(lastName.value);
    if (email.present) map['email'] = Variable<String>(email.value);
    if (badgeQr.present) map['badge_qr'] = Variable<String>(badgeQr.value);
    if (department.present) map['department'] = Variable<String>(department.value);
    if (jobTitle.present) map['job_title'] = Variable<String>(jobTitle.value);
    if (isActive.present) map['is_active'] = Variable<bool>(isActive.value);
    if (syncedAt.present) map['synced_at'] = Variable<int>(syncedAt.value);
    return map;
  }

  @override
  String toString() => 'EmployeeCacheCompanion(id: $id, firstName: $firstName, '
      'lastName: $lastName, email: $email, badgeQr: $badgeQr, '
      'department: $department, jobTitle: $jobTitle, isActive: $isActive, '
      'syncedAt: $syncedAt)';
}

// **************************************************************************
// SyncQueue
// **************************************************************************

class $SyncQueueTable extends SyncQueue
    with TableInfo<$SyncQueueTable, SyncQueueData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $SyncQueueTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultConstraints: GeneratedColumn.constraintIsAlways(
          'PRIMARY KEY AUTOINCREMENT'));
  @override
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
      'entity_type', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> entityLocalId = GeneratedColumn<String>(
      'entity_local_id', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> operation = GeneratedColumn<String>(
      'operation', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> payloadJson = GeneratedColumn<String>(
      'payload_json', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<int> retryCount = GeneratedColumn<int>(
      'retry_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultValue: const Constant(0));
  @override
  late final GeneratedColumn<String> lastError = GeneratedColumn<String>(
      'last_error', aliasedName, true,
      type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
      'status', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      defaultValue: const Constant('pending'));
  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>(
      'created_at', aliasedName, false,
      type: DriftSqlType.dateTime,
      requiredDuringInsert: false,
      defaultValue: currentDateAndTime);
  @override
  late final GeneratedColumn<DateTime> processedAt = GeneratedColumn<DateTime>(
      'processed_at', aliasedName, true,
      type: DriftSqlType.dateTime, requiredDuringInsert: false);

  @override
  List<GeneratedColumn> get $columns => [
        id, entityType, entityLocalId, operation, payloadJson,
        retryCount, lastError, status, createdAt, processedAt,
      ];

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'sync_queue';

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  SyncQueueData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SyncQueueData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}id'])!,
      entityType: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}entity_type'])!,
      entityLocalId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}entity_local_id'])!,
      operation: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}operation'])!,
      payloadJson: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}payload_json'])!,
      retryCount: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}retry_count'])!,
      lastError: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}last_error']),
      status: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}status'])!,
      createdAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      processedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}processed_at']),
    );
  }

  @override
  $SyncQueueTable createAlias(String alias) {
    return $SyncQueueTable(attachedDatabase, alias);
  }
}

class SyncQueueData extends DataClass implements Insertable<SyncQueueData> {
  final int id;
  final String entityType;
  final String entityLocalId;
  final String operation;
  final String payloadJson;
  final int retryCount;
  final String? lastError;
  final String status;
  final DateTime createdAt;
  final DateTime? processedAt;

  const SyncQueueData({
    required this.id,
    required this.entityType,
    required this.entityLocalId,
    required this.operation,
    required this.payloadJson,
    required this.retryCount,
    this.lastError,
    required this.status,
    required this.createdAt,
    this.processedAt,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['entity_type'] = Variable<String>(entityType);
    map['entity_local_id'] = Variable<String>(entityLocalId);
    map['operation'] = Variable<String>(operation);
    map['payload_json'] = Variable<String>(payloadJson);
    map['retry_count'] = Variable<int>(retryCount);
    if (!nullToAbsent || lastError != null) {
      map['last_error'] = Variable<String>(lastError);
    }
    map['status'] = Variable<String>(status);
    map['created_at'] = Variable<DateTime>(createdAt);
    if (!nullToAbsent || processedAt != null) {
      map['processed_at'] = Variable<DateTime>(processedAt);
    }
    return map;
  }

  SyncQueueCompanion toCompanion(bool nullToAbsent) {
    return SyncQueueCompanion(
      id: Value(id),
      entityType: Value(entityType),
      entityLocalId: Value(entityLocalId),
      operation: Value(operation),
      payloadJson: Value(payloadJson),
      retryCount: Value(retryCount),
      lastError: lastError == null && nullToAbsent
          ? const Value.absent()
          : Value(lastError),
      status: Value(status),
      createdAt: Value(createdAt),
      processedAt: processedAt == null && nullToAbsent
          ? const Value.absent()
          : Value(processedAt),
    );
  }

  factory SyncQueueData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SyncQueueData(
      id: serializer.fromJson<int>(json['id']),
      entityType: serializer.fromJson<String>(json['entity_type']),
      entityLocalId: serializer.fromJson<String>(json['entity_local_id']),
      operation: serializer.fromJson<String>(json['operation']),
      payloadJson: serializer.fromJson<String>(json['payload_json']),
      retryCount: serializer.fromJson<int>(json['retry_count']),
      lastError: serializer.fromJson<String?>(json['last_error']),
      status: serializer.fromJson<String>(json['status']),
      createdAt: serializer.fromJson<DateTime>(json['created_at']),
      processedAt: serializer.fromJson<DateTime?>(json['processed_at']),
    );
  }

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'entity_type': serializer.toJson<String>(entityType),
      'entity_local_id': serializer.toJson<String>(entityLocalId),
      'operation': serializer.toJson<String>(operation),
      'payload_json': serializer.toJson<String>(payloadJson),
      'retry_count': serializer.toJson<int>(retryCount),
      'last_error': serializer.toJson<String?>(lastError),
      'status': serializer.toJson<String>(status),
      'created_at': serializer.toJson<DateTime>(createdAt),
      'processed_at': serializer.toJson<DateTime?>(processedAt),
    };
  }

  SyncQueueData copyWith({
    int? id,
    String? entityType,
    String? entityLocalId,
    String? operation,
    String? payloadJson,
    int? retryCount,
    Value<String?> lastError = const Value.absent(),
    String? status,
    DateTime? createdAt,
    Value<DateTime?> processedAt = const Value.absent(),
  }) =>
      SyncQueueData(
        id: id ?? this.id,
        entityType: entityType ?? this.entityType,
        entityLocalId: entityLocalId ?? this.entityLocalId,
        operation: operation ?? this.operation,
        payloadJson: payloadJson ?? this.payloadJson,
        retryCount: retryCount ?? this.retryCount,
        lastError: lastError.present ? lastError.value : this.lastError,
        status: status ?? this.status,
        createdAt: createdAt ?? this.createdAt,
        processedAt: processedAt.present ? processedAt.value : this.processedAt,
      );

  @override
  String toString() => 'SyncQueueData(id: $id, entityType: $entityType, '
      'entityLocalId: $entityLocalId, operation: $operation, '
      'payloadJson: $payloadJson, retryCount: $retryCount, '
      'lastError: $lastError, status: $status, createdAt: $createdAt, '
      'processedAt: $processedAt)';

  @override
  int get hashCode => Object.hash(id, entityType, entityLocalId, operation,
      payloadJson, retryCount, lastError, status, createdAt, processedAt);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SyncQueueData &&
          other.id == id &&
          other.entityType == entityType &&
          other.entityLocalId == entityLocalId &&
          other.operation == operation &&
          other.payloadJson == payloadJson &&
          other.retryCount == retryCount &&
          other.lastError == lastError &&
          other.status == status &&
          other.createdAt == createdAt &&
          other.processedAt == processedAt);
}

class SyncQueueCompanion extends UpdateCompanion<SyncQueueData> {
  final Value<int> id;
  final Value<String> entityType;
  final Value<String> entityLocalId;
  final Value<String> operation;
  final Value<String> payloadJson;
  final Value<int> retryCount;
  final Value<String?> lastError;
  final Value<String> status;
  final Value<DateTime> createdAt;
  final Value<DateTime?> processedAt;

  const SyncQueueCompanion({
    this.id = const Value.absent(),
    this.entityType = const Value.absent(),
    this.entityLocalId = const Value.absent(),
    this.operation = const Value.absent(),
    this.payloadJson = const Value.absent(),
    this.retryCount = const Value.absent(),
    this.lastError = const Value.absent(),
    this.status = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.processedAt = const Value.absent(),
  });

  SyncQueueCompanion.insert({
    this.id = const Value.absent(),
    required String entityType,
    required String entityLocalId,
    required String operation,
    required String payloadJson,
    this.retryCount = const Value.absent(),
    this.lastError = const Value.absent(),
    this.status = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.processedAt = const Value.absent(),
  })  : entityType = Value(entityType),
        entityLocalId = Value(entityLocalId),
        operation = Value(operation),
        payloadJson = Value(payloadJson);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (entityType.present) map['entity_type'] = Variable<String>(entityType.value);
    if (entityLocalId.present) map['entity_local_id'] = Variable<String>(entityLocalId.value);
    if (operation.present) map['operation'] = Variable<String>(operation.value);
    if (payloadJson.present) map['payload_json'] = Variable<String>(payloadJson.value);
    if (retryCount.present) map['retry_count'] = Variable<int>(retryCount.value);
    if (lastError.present) map['last_error'] = Variable<String>(lastError.value);
    if (status.present) map['status'] = Variable<String>(status.value);
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (processedAt.present) map['processed_at'] = Variable<DateTime>(processedAt.value);
    return map;
  }

  @override
  String toString() => 'SyncQueueCompanion(...)';
}

// **************************************************************************
// EdgeConfig
// **************************************************************************

class $EdgeConfigTable extends EdgeConfig
    with TableInfo<$EdgeConfigTable, EdgeConfigData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $EdgeConfigTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
      'key', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
      'value', aliasedName, false,
      type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>(
      'updated_at', aliasedName, false,
      type: DriftSqlType.dateTime,
      requiredDuringInsert: false,
      defaultValue: currentDateAndTime);

  @override
  List<GeneratedColumn> get $columns => [key, value, updatedAt];

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'edge_config';

  @override
  Set<GeneratedColumn> get $primaryKey => {key};

  @override
  EdgeConfigData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return EdgeConfigData(
      key: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}key'])!,
      value: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}value'])!,
      updatedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $EdgeConfigTable createAlias(String alias) {
    return $EdgeConfigTable(attachedDatabase, alias);
  }
}

class EdgeConfigData extends DataClass implements Insertable<EdgeConfigData> {
  final String key;
  final String value;
  final DateTime updatedAt;

  const EdgeConfigData({
    required this.key,
    required this.value,
    required this.updatedAt,
  });

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    return {
      'key': Variable<String>(key),
      'value': Variable<String>(value),
      'updated_at': Variable<DateTime>(updatedAt),
    };
  }

  EdgeConfigCompanion toCompanion(bool nullToAbsent) {
    return EdgeConfigCompanion(
      key: Value(key),
      value: Value(value),
      updatedAt: Value(updatedAt),
    );
  }

  factory EdgeConfigData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return EdgeConfigData(
      key: serializer.fromJson<String>(json['key']),
      value: serializer.fromJson<String>(json['value']),
      updatedAt: serializer.fromJson<DateTime>(json['updated_at']),
    );
  }

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return {
      'key': serializer.toJson<String>(key),
      'value': serializer.toJson<String>(value),
      'updated_at': serializer.toJson<DateTime>(updatedAt),
    };
  }

  EdgeConfigData copyWith({String? key, String? value, DateTime? updatedAt}) =>
      EdgeConfigData(
        key: key ?? this.key,
        value: value ?? this.value,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  @override
  String toString() =>
      'EdgeConfigData(key: $key, value: $value, updatedAt: $updatedAt)';

  @override
  int get hashCode => Object.hash(key, value, updatedAt);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is EdgeConfigData &&
          other.key == key &&
          other.value == value &&
          other.updatedAt == updatedAt);
}

class EdgeConfigCompanion extends UpdateCompanion<EdgeConfigData> {
  final Value<String> key;
  final Value<String> value;
  final Value<DateTime> updatedAt;

  const EdgeConfigCompanion({
    this.key = const Value.absent(),
    this.value = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  EdgeConfigCompanion.insert({
    required String key,
    required String value,
    this.updatedAt = const Value.absent(),
  })  : key = Value(key),
        value = Value(value);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (key.present) map['key'] = Variable<String>(key.value);
    if (value.present) map['value'] = Variable<String>(value.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }

  @override
  String toString() =>
      'EdgeConfigCompanion(key: $key, value: $value, updatedAt: $updatedAt)';
}

// **************************************************************************
// Database mixin (_$EdgeDatabase)
// **************************************************************************

mixin _$EdgeDatabaseMixin on GeneratedDatabase {
  $AttendanceLogsTable get attendanceLogs =>
      this.resultSet<$AttendanceLogsTable>('attendance_logs');
  $EmployeeCacheTable get employeeCache =>
      this.resultSet<$EmployeeCacheTable>('employee_cache');
  $SyncQueueTable get syncQueue =>
      this.resultSet<$SyncQueueTable>('sync_queue');
  $EdgeConfigTable get edgeConfig =>
      this.resultSet<$EdgeConfigTable>('edge_config');
}

abstract class _$EdgeDatabase extends GeneratedDatabase {
  _$EdgeDatabase(super.e);

  late final $AttendanceLogsTable attendanceLogs = $AttendanceLogsTable(this);
  late final $EmployeeCacheTable employeeCache = $EmployeeCacheTable(this);
  late final $SyncQueueTable syncQueue = $SyncQueueTable(this);
  late final $EdgeConfigTable edgeConfig = $EdgeConfigTable(this);

  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();

  @override
  List<DatabaseSchemaEntity> get allSchemaEntities =>
      [attendanceLogs, employeeCache, syncQueue, edgeConfig];
}
